### ISSUE TITLE
Column in GridContextMenu#onBeforeOpenMenu

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#424] opened 2020-11-23 08:28 UTC
The `GridContextMenu` allows you to dynamically add/remove items, depending on the clicked row, but it does not offer the same possibility for the selected  column.
In our case, some actions are only available for specific columns and I would like to be able to add those action only for those specific columns.
My current workaround is to create my own subclass of the vaadin grid, which uses a modified version of the `gridConnector`.
It was enough to add the following code after [Line 945](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L945):
`columnId: (eventContext.column && eventContext.column.id) || ""`
The `dynamicContentHandler` in `GridContextMenu` could then be changed to a `SerializableBiPredicate<T, Column<T>`.

**Comment by web-padawan** [comment] 2022-06-23 07:09
Closing in favor of #1939 which is essentially a duplicate of this issue.

**Closed by web-padawan** 2022-06-23 07:09 UTC
Labels: enhancement
