### ISSUE TITLE
Validation inconsistency in Vaadin 24

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow-components#5330] opened 2023-08-07 07:18 UTC
### Description

I have 2 fields with a validator.
I'm using a binder and call setBean.
One value is null the other is not null ("na").
Both are invalid.
The field with a null value is displayed as valid.
The field with a "na" value is displayed as invalid.

In Vaadin 23, both fields are displayed as valid.

### Expected outcome

Both fields should have the same state, valid or invalid.
Currently it's not consistent.
![image](https://github.com/vaadin/flow-components/assets/51313578/d8752f46-cae6-4def-a8d4-657ea25081d0)

### Minimal reproducible example

https://github.com/jcgueriaud1/spring-proxy-issue/tree/validation-v24

```java
public class HelloWorldView extends HorizontalLayout {

    private Binder<FakeBean> binder = new Binder<>();

    private TextField name = new TextField("Name");
    private TextField name2 = new TextField("Name2");

    public HelloWorldView() {
        FakeBean fakeBean = new FakeBean();
        binder.forField(name).asRequired("name is required")
                .withValidator(value -> {
                    System.out.println("Validate " + value);
                    return (value.length() > 2);
                }, "Length should be > 2")
                .bind(FakeBean::getName, FakeBean::setName);
        binder.forField(name2).asRequired("name2 is required")
                .withValidator(value -> {
                    System.out.println("Validate name2 " + value);
                    return (value.length() > 2);
                }, "Length should be > 2")
                .bind(FakeBean::getName2, FakeBean::setName2);
        binder.setBean(fakeBean);
        add(name, name2);
    }

}
```

```java
public class FakeBean {

    private Long id = 1L;
    private Long id2 = 1L;
    private String name = "na";
    private String name2;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getId2() {
        return id2;
    }

    public void setId2(Long id2) {
        this.id2 = id2;
    }

    public String getName2() {
        return name2;
    }

    public void setName2(String name2) {
        this.name2 = name2;
    }
}
```

### Steps to reproduce

Open the view http://localhost:8080/

### Environment

Vaadin version(s): 24.1.4
OS: Mac

### Browsers

Issue is not browser related

**Comment by TatuLund** [comment] 2023-08-07 07:27
I think this is related https://github.com/vaadin/web-components/pull/6238

**Comment by knoobie** [comment] 2023-08-07 09:06
Wasn't that always like this? SetBean doesn't not enforce required validations - I would literally open a BFP ticket the second once you going to do that because it would break all our applications. 

All fields are correctly marked as invalid once you call binder.validate(true) (which works since V8-V24.1).

**Comment by jcgueriaud1** [comment] 2023-08-07 09:57
> Wasn't that always like this?
In Vaadin 23, both fields are displayed as valid.

**Comment by vursen** [comment] 2023-08-07 10:49
This behavior is a result of https://github.com/vaadin/web-components/pull/4413, which was implemented a year ago. The dirty flag doesn't currently address this issue.

**Comment by TatuLund** [comment] 2023-08-07 13:38
@vursen based on that it then looks like an intentional, but behavior changing change.

**Comment by Alexenon** [comment] 2023-09-08 10:44
I am not quite sure if this is similar to #5328 
But in my case, the binder doesn't validate the `Input` component, just the `TextField`
```
        TextField textField = new TextField();
        textField.setPlaceholder("Text Field");

        binder.forField(textField)
                .asRequired("Please fill this field")
                .withValidator(s -> s.length() > 3, "Field must contain at least 4 characters")
                .withValidator(s -> s.length() < 6, "Field must contain less than 6 characters")
                .bind(User::getPassword, User::setPassword);

        Input input = new Input();
        input.setPlaceholder("Input");

        binder.forField(input)
                .asRequired("Please fill this field")
                .withValidator(s -> s.length() > 3, "Field must contain at least 4 characters")
                .withValidator(s -> s.length() < 6, "Field must contain less than 6 characters")
                .bind(User::getPassword, User::setPassword);
``` 

![image](https://github.com/vaadin/flow-components/assets/58091611/6b8032cf-4359-4bbb-9f06-ef731fe7b790)

**Comment by knoobie** [comment] 2023-09-08 10:48
Input is a simple html component on the client side and has no logic to display errors or other things. It is not designed to be used with the Binder.

**Comment by knoobie** [comment] 2023-09-08 16:12
Vaadin's own components like Text field, Combo box, Datepicker and so on should be used within a CustomField.

**Comment by jcgueriaud1** [comment] 2023-12-01 13:02
But on the initial load, the validation is running and it returns false.
It looks wrong that the validation says false and the field is valid.

**Comment by vursen** [comment] 2023-12-04 07:33
> But on the initial load, the validation is running and it returns false.
> It looks wrong that the validation says false and the field is valid.

I believe it's expected behavior of Binder when you set a bean. When setting a bean, Binder updates the fields' value via `setValue`, which automatically triggers their revalidation. That revalidation isn't really needed since the bean values are considered initial. However, Binder cannot prevent it, so it clears the result instead. In theory, Binder could use `setManualValidation(true)` to prevent that revalidation now that we have this API.

> In Vaadin 24.3.0.beta1, both fields are valid.

Thank you for testing. I'm closing the issue as resolved.

**Closed by vursen** 2023-12-04 07:33 UTC
Labels: validation
