### ISSUE TITLE
Grid draggable

### ISSUE THREAD

**Issue by rlegorreta** [vaadin/flow-components#5523] opened 2023-09-28 19:56 UTC
### Description

When a Gris is draggable (i.e., grid.setRowsDraggable(true)) it send at the browser (Chrome) console the next error:

There seems to be an error in Vaadin Grid:
Cannot read properties of undefined (reading 'dragDisabled')
Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose

### Expected outcome

Nos send errors to browser console

### Minimal reproducible example

Declare a Grid and make ir draggable :

var grid = new Grid<>()

grid.setRowsGRaggable(true);

### Steps to reproduce

Create a draggable Grid

### Environment

Vaadin version(s): 
OS:  MacOS X Monterey 12.6.8

### Browsers

Chrome

**Comment by tomivirkki** [comment] 2023-09-29 06:30
I just [closed](https://github.com/vaadin/flow-components/issues/2627#issuecomment-1737474992) a related issue yesterday. Simply setting `grid.setRowsDraggable(true);` isn't enough to produce the issue, since the [DnD examples](https://vaadin.com/docs/latest/components/grid#row-reordering) on vaadin.com don't give any errors. Please attach an example project that we can use to reproduce the issue so we can take a better look.

**Comment by rlegorreta** [comment] 2023-09-30 01:18
The project is a many views project so give me time, two days at most to isolate the problem and submit the problem to components url.

**Comment by rlegorreta** [comment] 2023-09-30 01:19
Thanks for your promptly response.

**Comment by knoobie** [comment] 2023-09-30 05:21
It's probably the fastest, to tell Tomi the used Vaadin Version, the fix isn't in all versions available.

**Comment by rlegorreta** [comment] 2023-10-02 17:45
Vaadin version: 24.1.1
Spring boot 3.1.0
Kotlin 1.8.21
Spring security 6.1.1.

**Comment by knoobie** [comment] 2023-10-02 17:54
That Vaadin version still has the bug, once you are on 24.1.6++ it's fixed.

**Comment by rlegorreta** [comment] 2023-10-02 18:59
Thanks I upgrade Vaadin Flow and the error has been fixed. Thanks

**Comment by TatuLund** [comment] 2023-10-03 05:21
Closed as duplicate of https://github.com/vaadin/flow-components/issues/2627

**Closed by TatuLund** 2023-10-03 05:21 UTC
