### ISSUE TITLE
TreeGrid causes browser to hang with infinite loop /out of stack

### ISSUE THREAD

**Issue by andersforsell** [vaadin/flow-components#3621] opened 2022-08-28 07:30 UTC
### Description

The TreeGrid caused the browser to hang with out of stack memory.
The exception caught in the browser was:
"Got new data to index 1 which is not aligned with the page size of 50"

### Expected outcome

The browser should display the vaadin tree content correctly.

### Minimal reproducible example

I have tried to debug the Java code and the TreeData implementation but I cannot see that I am doing something incorrectly.
Let me know how to proceed, but I cannot easily give you a reproducible scenario since we have a large application.

### Steps to reproduce

See above

### Environment

Vaadin version(s): 23.1.6
OS: Windows 10 Enterprise

### Browsers

Chrome

**Comment by TatuLund** [comment] 2022-08-28 08:58
One case where this could happen (and which is not a bug), is if the TreeData is cyclic. This is mentioned in the documentation. TreeGrid and hierarchical data in Vaadin is strictly a tree, not a graph. Cyclic links will lead to infinite loops and stackoverlfow.

**Comment by andersforsell** [comment] 2022-08-28 10:47
I was able to explicitly do a refreshAll on the treeDataProvider after the model change to avoid this problem.
My model should never contain cycles, but it might not be worthwhile to continue analyze this since it is complicated to set up a reproducable environment for you.

**Comment by yuriy-fix** [comment] 2022-08-30 10:25
Dear @andersforsell,

Unfortunately we are not able to proceed with the investigation unless a reproducible example is provided. I'm closing the issue, but feel free to create a new issue if you would have a reproducible code snippet to share. We would also appreciate if you could give us an access to your application, so we can try to debug it.

**Closed by yuriy-fix** 2022-08-30 10:25 UTC
Labels: question
