### ISSUE TITLE
V23.3: Tooltip does not show up when the component is disabled

### ISSUE THREAD

**Issue by taefi** [vaadin/flow-components#4393] opened 2022-12-18 13:35 UTC
### Description

I have added some buttons to a view and I set the tooltip for them. The tooltip works nicely while the buttons are enabled. However, hovering the mouse on them is not triggering the tooltip overlay to show up when they have `setEnabled(false)`. 

### Expected outcome

Since the tooltips are readonly texts, I would expect them to show up on almost any components as long as the user can see them on the page, no matter if they are disabled or not. In fact, in many cases I get requests from customers to add tooltips especially on disabled buttons to provide the reason being disabled to the user, e.g. some status of the data, or lack of having enough permissions, etc.

### Minimal reproducible example

```
Button enabledButton = new Button("Hover for tooltip");
enabledButton.setTooltipText("Tooltip works fine!");

Button disabledButton = new Button("Hover for tooltip");
disabledButton.setTooltipText("Tooltip show work on disabled components!");
```

### Steps to reproduce

The above snippet code with two buttons shows the issue.

### Environment

Vaadin version(s): 23.3.0

### Browsers

Chrome, Firefox

**Comment by web-padawan** [comment] 2022-12-18 13:51
This is a known limitation and not a bug. Currently, disabled components are not focusable and do not handle mouse / touch events. We might reconsider that in the future, see https://github.com/vaadin/web-components/issues/4585.

**Comment by rolfsmeds** [comment] 2022-12-22 13:43
Closing in favor of https://github.com/vaadin/web-components/issues/4585

**Closed by rolfsmeds** 2022-12-22 13:43 UTC
