### ISSUE TITLE
There seems to be an error in Vaadin Grid: Cannot read properties of null (reading '__debounceUpdateHeaderFooterRowVisibility')

### ISSUE THREAD

**Issue by oilhands** [vaadin/flow-components#4480] opened 2023-01-04 02:56 UTC
### Description

There seems to be an error in Vaadin Grid: Cannot read properties of null (reading '__debounceUpdateHeaderFooterRowVisibility')

### Expected outcome

I shouldn't get this error

### Minimal reproducible example

This is your control calling home. I'm not sure what you want.

### Steps to reproduce

After selecting the first row, select the second row. Poof. 

### Environment

Vaadin version(s): 23.3.1
OS: Ubuntu Linux 22.04

### Browsers

Issue is not browser related

**Comment by oilhands** [comment] 2023-01-04 03:03
Oh, and no issue in 23.3.0

**Comment by knoobie** [comment] 2023-01-04 05:55
Sounds like a duplicate of https://github.com/vaadin/flow-components/issues/4476 - did you try 23.3.2?

**Comment by rolfsmeds** [comment] 2023-01-04 13:19
Quite certain this is the same issue. Closing as fixed in 23.3.2.

**Closed by rolfsmeds** 2023-01-04 13:19 UTC
Labels: vaadin-grid

**Comment by oilhands** [comment] 2023-01-04 17:46
Okay. I didn't see 23.3.2 being available. I'll check it out. Thanks.
