### ISSUE TITLE
Upload(MultiFileMemoryBuffer)...transferTo() - ignore the filename and reads the input from all files

### ISSUE THREAD

**Issue by knoxyz** [vaadin/flow-components#2342] opened 2021-11-15 14:10 UTC
### Description

transferTo() from MultiFileMemoryBuffer ignores the filtering of a single file.

So after the execution of ...
MultiFileMemoryBuffer.getInputStream(_event.getFileName()_).**transferTo**(baos);
baos contain the bytes from all files.

### Expected outcome

boas should contain only the bytes from the single filtered file.

### Actual outcome

boas contain the concatenate input from all uploaded files.

### Minimal reproducible example

```
private void addUpload() {
	 MultiFileMemoryBuffer multiBuffer = new MultiFileMemoryBuffer();
	 ByteArrayOutputStream baos = new ByteArrayOutputStream();
	 Upload multiUpload = new Upload(multiBuffer);

	  upload.addSucceededListener(event -> {

		//fix: only with baos.reset() will be the input of baos correct.
		//baos.reset();

	 	  try {
			//Caution: transferTo() ignores the filename and reads all files into baos!
	 		  multiBuffer.getInputStream(event.getFileName()).transferTo(baos);

			// the value of multiStream is correct.
		 	  InputStream multiStream = multiBuffer.getInputStream(event.getFileName());
		 	  String fileText = IOUtils.toString(multiStream , StandardCharsets.UTF_8);
		   } catch (IOException e) {
	 		  ...
	 	  }
  	 });
	 add(multiUpload)
}
```
### Steps to reproduce

Clear steps describing how to reproduce the issue.

1. Add an Upload component to a page.
2. Upload two or more files.
3. After each addSucceededListener() the baos will be containing the bytes from all files but not only from the current single file.

A fix of this problem is to execute baos.reset() for each upload.addSucceededListener() event.

But the content of multiStream is correct and also the use of MemoryBuffer instead of MultiFileMemoryBuffer works fine.
### Environment

- vaadin 21.0.4, but this problem happens also with v14
- Windows 10 and RHEL 8.x

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] IE 11

**Comment by sissbruecker** [comment] 2021-11-16 15:00
Your code works as expected:
- the succeeded file listener is called for **every single file** that is uploaded, so if you upload 3 files, it will be called 3 times, once for every file
- `multiBuffer.getInputStream(event.getFileName())` will correctly give you the input stream for the file that was just successfully uploaded, which you then append to the output stream `baos`
- you use a single output stream for all uploaded files, so after uploading 3 files your output stream will contain the contents of 3 files
- this would still be true even when not using multi-file upload. You create a single output stream for the lifetime your view, so even just uploading a number of individual files would append them to the same output stream

You probably want to create a new output stream for each file, within the succeeded listener instead, so that each file gets directed into its own output stream. If you want to get notified when all files have successfully been uploaded, use `addAllFinishedListener`.

Closing as working as intended.

**Closed by sissbruecker** 2021-11-16 15:00 UTC
Labels: bug, Severity: Minor, Impact: Low

**Comment by knoxyz** [comment] 2021-11-16 16:55
Hi sissbruecker, thank for your feedback.

For the first both points I agree with you that it works like expected.

But your 3. and 4. statements are weird for me because:
- the variable `baos` is defined not global but inside the addSucceededListener() which fire after each single upload. Therefore `boas` should be created new and empty for each single event call.
- If it's really intention that transferTo() concatenate the content of all files, it should be unnecessary to parameterize a filename for `getInputStream(event.getFileName())` because an shorter `multiBuffer.transferTo(baos)` should do the same.
- in which use case will be the current behaivor (just join all files, without an index) makes sence?

**Comment by sissbruecker** [comment] 2021-11-16 18:07
>the variable baos is defined not global but inside the addSucceededListener()

That is not correct. If you look at the code example you provided, you can see that the variable is defined outside of the scope of the listener. Thus the same instance is used for all calls of the listener. To fix this, you have to move the declaration of `baos` into the listener:
```java
upload.addSucceededListener(event -> {
  ByteArrayOutputStream baos = new ByteArrayOutputStream();

  try {
    multiBuffer.getInputStream(event.getFileName()).transferTo(baos);
    
    // TODO: actually do something with the bytes...
    // For example, assuming we have a UTF8 encoded text file, print it
    System.out.println(baos.toString("UTF-8"));
  } catch (IOException e) {
    ...
  }
});
```

> If it's really intention that transferTo() concatenate the content of all files

Concatenation is just the side-effect of how you are using this method. `transferTo` will just write the contents of the input stream into the output stream that is provided as parameter. Concatenation only happens if you always pass the same output stream. If you actually create a new output steam for each succeeded file, then you can process each file individually, in which case the `getInputStream(String filename)` method is very much needed.

**Comment by knoxyz** [comment] 2021-11-16 19:59
Hi sissbruecker,

omg, you are absolutely right!

Vaadin works indeed correctly and this side effects was only caused by my, actually obviously, wrong declaration...
Sorry for this thread.
