### ISSUE TITLE
GridPro: NPE and stale data shown when switching to new data provider

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#2360] opened 2021-11-18 20:39 UTC
### Description

Chrome latest
Vaadin 22 beta 3

Seeing old data (editor columns) in new rows added after setting a new data provider.  Also getting a NPE during the process.  Hard to explain, please see code and GIF.

### Live Demo (optional)

![gridpro-old-data](https://user-images.githubusercontent.com/2496955/142492541-3df06b13-9a61-412a-b535-b8f514e66f17.gif)

### Minimal reproducible example

```
public class TestView extends VerticalLayout {
        // setup grid
        GridPro<Person> grid = new GridPro<>();
        grid.setWidth("500px");
        grid.setHeight("200px");

        ComboBox<String> editor = new ComboBox<>();
        editor.setItems("John", "Terry", "Brandon", "Kevin");

        grid.addEditColumn(Person::getName)
                .custom(editor, Person::setName)
                .setHeader("Name");

        grid.addColumn(new LocalDateTimeRenderer<>(Person::getDob))
                .setHeader("DOB");

        // setup provider
        persons = new HashSet<>();
        provider = new ListDataProvider<>(persons);
        grid.setItems(provider);

        // add row to grid
        Button addBtn = new Button("Add", e -> {
            persons.add(new Person("Kevin", LocalDateTime.now()));
            provider.refreshAll();
        });

        // clear all grid rows
        Button clearBtn = new Button("Clear", e -> {
            persons = new HashSet<>();

            provider = new ListDataProvider<>(persons);
            grid.setItems(provider);
        });

        add(grid, addBtn, clearBtn);
    }

    public static class Person {
        String name;
        LocalDateTime dob;

        public Person(String name, LocalDateTime dob) {
            this.name = name;
            this.dob = dob;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public LocalDateTime getDob() {
            return dob;
        }

        public void setDob(LocalDateTime dob) {
            this.dob = dob;
        }
    }

}
```

### NPE Stacktrace

```
java.lang.NullPointerException
	at com.vaadin.flow.component.gridpro.EditColumnConfigurator.lambda$custom$c6d78a8a$1(EditColumnConfigurator.java:113)
	at com.vaadin.flow.component.gridpro.GridPro.lambda$setup$9b1b5227$1(GridPro.java:119)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:373)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:264)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:443)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:443)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:66)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1567)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
	at com.vaadin.cdi.CdiVaadinServlet.service(CdiVaadinServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.websocket.tyrus.TyrusServletFilter.doFilter(TyrusServletFilter.java:274)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:32)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3797)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.__run(WebAppServletContext.java:3763)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:40012)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2451)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2299)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2277)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1720)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1680)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)

```

**Comment by TatuLund** [comment] 2021-11-19 07:43
Does not happen with 21.0.6

**Comment by TatuLund** [comment] 2021-11-19 08:31
Unless your case is related to this https://github.com/vaadin/web-components/pull/3081

**Comment by tomivirkki** [comment] 2021-11-19 08:46
This is caused by the same issue as https://github.com/vaadin/flow-components/issues/2361

The fix is in the release process

**Closed by tomivirkki** 2021-11-19 08:46 UTC
Labels: bug, vaadin-grid-pro
