### ISSUE TITLE
TreeGrid refresh item doesn't work 

### ISSUE THREAD

**Issue by cervenf** [vaadin/flow-components#4976] opened 2023-04-22 07:23 UTC
### Description

Sub-items in treegrid are not properly refreshed 
The query is changed with use of AbstractBackEndHierarchicalDataProvider.
related to https://github.com/vaadin/flow-components/issues/4132

### Expected outcome

sub-items in tree grid are always refreshed

### Minimal reproducible example

https://github.com/cervenf/vaadin-24-treegrid-refresh/tree/master

### Steps to reproduce

1. expand the first item in grid and right-click on the item - the context menu is visible. Click on a filter.
2. put some value which is not present e.g. "1" - subitems are removed
3. right-click on the item again and remove "1" - nothing happened. Items are not refreshed.
4. There is no way to see items again - you need to refresh page.
![grid-not-refreshing-01](https://user-images.githubusercontent.com/1408155/233769643-43090a36-e423-4348-9c21-5b25a6d98941.gif)

### Environment

Vaadin version(s): 24
OS: windows (maybe all)
IDE (if applicable): Idea

**Comment by cervenf** [comment] 2023-06-13 16:21
Hi,
any progress on it please?

**Comment by leluna** [comment] 2023-07-12 10:08
We encountered this issue too. As a workaround, we are calling refreshAll instead of refreshItem.

**Comment by yuriy-fix** [comment] 2023-09-11 20:14
The issue seems to be addressed with https://github.com/vaadin/flow-components/pull/5340 and fix is available since 24.1.5.

**Comment by tomivirkki** [comment] 2023-10-05 10:09
Confirmed this works with the latest Vaadin 24. Closing.

https://github.com/vaadin/flow-components/assets/1222264/8f43463c-bf3f-466b-b8e2-4dac092f5511

**Closed by tomivirkki** 2023-10-05 10:09 UTC
Labels: waiting for author
