### ISSUE TITLE
Moving items from one grid to another and selecting an item causes errors

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow-components#1700] opened 2021-05-25 07:34 UTC
### Description
When first time moving items from Grid 1 to Grid 2 and selecting the first item in Grid 2, it produces Errors in the browser console. Items are moved successfully. Errors do not appear when moving items back to Grid 1 and selecting the first item in that grid, and when moving (and selecting the first item) to Grid 2 again.  Using vaadin 19.0.8.
![image](https://user-images.githubusercontent.com/80950643/119455768-97f77400-bd42-11eb-8773-cf985b1e3524.png)
![image](https://user-images.githubusercontent.com/80950643/119455929-c8d7a900-bd42-11eb-8a0f-b65ac0a03cba.png)

### Expected outcome
Items get moved to empty to second grid and first item gets selected.

### Actual outcome
Items get moved to empty to second grid and first item appears to be selected (for a client project it fails to select it), but errors in browser console appear. 

### Live Demo / Source code
https://github.com/HerbertsVaadin/problem-with-moving-between-grids
Use "Move Right"  and watch the browser console. 
It only produces the errors the first time you move the items to the right. 

### Steps to reproduce (with Vaadin 19.0.8)
1. Create two Grids
2. Populate Grid 1 with at least one item.
3. Create a button that triggers move of items from Grid 1 to Grid 2, and selects the first item in Grid 2.
4. Look at the browser console for errors. 

### Workaround
Delay selection with `getElement().executeJs("")`
```
 getElement().executeJs("").then(ce -> selectFirstItem(_rightGrid));
```

### Browsers Affected 

- [x] Chrome
- [x] Firefox
(others not checked)

Stacktrace:
```
tryCatchWrapper FlowBootstrap.js:67
    _generateCellClassNames vaadin-grid-styling-mixin.js:63
    _generateCellClassNames vaadin-grid-styling-mixin.js:58
    _updateItem vaadin-grid.js:814
    _updateItem gridConnector.js:437
    tryCatchWrapper FlowBootstrap.js:64
    _selectedItemsChanged vaadin-grid-selection-mixin.js:84
    _selectedItemsChanged vaadin-grid-selection-mixin.js:83
    runMethodEffect property-effects.js:819
    runEffectsForProperty property-effects.js:157
    runEffects property-effects.js:121
    _propertiesChanged property-effects.js:1692
    _propertiesChanged FlowClient.js:1001
    _flushProperties properties-changed.js:354
    _flushProperties property-effects.js:1536
    _invalidateProperties property-effects.js:1506
    _setProperty property-effects.js:1491
    set properties-changed.js:153
    doSelection gridConnector.js:162
    tryCatchWrapper FlowBootstrap.js:64
    anonymous vaadin-3-c872be1197fca0bba181.cache.js line 11 > eval line 995 > Function:3
    ot FlowClient.js:993
    nt FlowClient.js:946
    lt FlowClient.js:567
    Tq FlowClient.js:496
    qr FlowClient.js:1001
    PA FlowClient.js:917
    Vq FlowClient.js:997
    kr FlowClient.js:1001
    lk FlowClient.js:413
    Nq FlowClient.js:999
    Oq FlowClient.js:980
    bt FlowClient.js:1001
    tB FlowClient.js:1001
    onreadystatechange FlowClient.js:577
```

**Comment by web-padawan** [comment] 2021-05-25 08:57
Moved to `flow-components` because the issue seems related to `doSelection` invocation in Flow connector.

**Comment by web-padawan** [comment] 2022-06-13 07:09
This appears to be a duplicate of #3037 which has been fixed by https://github.com/vaadin/web-components/pull/3789. Closing.

**Closed by web-padawan** 2022-06-13 07:09 UTC
Labels: bug, vaadin-grid, Severity: Minor, Impact: Low
