### ISSUE TITLE
Grid option that expands it only as much as needed, or as much as sceen allows it to.  

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow-components#2941] opened 2022-03-27 22:53 UTC
Use case:
There is a grid, with two columns and dynamic row count (sometimes 2, sometimes 50).
The customer wants the view containing this grid to not have a vertical scroll-bar. 
If all rows can fit on the screen, it should display the grid only as high as it needs to be to show all rows.
If all rows can't fit the screen, the grid should take as much of vertical screen space as possible (without creating a view scroll-bar) and should create a scroll-bar for Grid component specifically.  
The grid itself is nested deeper than other components.
![image](https://user-images.githubusercontent.com/80950643/160304531-ccb5f000-fa49-415f-8cde-d890f0173534.png)
![image](https://user-images.githubusercontent.com/80950643/160304554-47ffef93-244e-42e5-97f1-08e151a1aa84.png)

**Comment by DiegoCardoso** [comment] 2022-03-28 11:08
Hi @HerbertsVaadin,

I guess what the user wants is already supported by Grid through `Grid#setAllRowsVisible()`. Check the feature [at the docs page](https://vaadin.com/docs/latest/ds/components/grid/#dynamic-height).

**Comment by web-padawan** [comment] 2022-03-28 11:32
Just to clarify the behavior of `setAllRowsVisible(true)`:

> If all rows can fit on the screen, it should display the grid only as high as it needs to be to show all rows.

This is supported.

> If all rows can't fit the screen, the grid should take as much of vertical screen space as possible 

This isn't supported (when all the rows are visible, there will be a scrollbar for the view, not for grid).

**Comment by jouni** [comment] 2022-03-28 12:00
Yeah, the enhancement would be about supporting max-height on a grid with all rows visible.

**Comment by web-padawan** [comment] 2022-03-28 12:28
> supporting max-height on a grid with all rows visible.

Thanks, so this is basically a duplicate of https://github.com/vaadin/web-components/issues/2150. Closing in favor of that issue.

**Closed by web-padawan** 2022-03-28 12:28 UTC
