### ISSUE TITLE
IntegerField in a grid unselected field after increase

### ISSUE THREAD

**Issue by IBims1ckoky** [vaadin/flow-components#5567] opened 2023-10-12 06:29 UTC
### Description

If you have a ComponentRenderer in a grid that adds an IntergerField and you want to increase the number with the up and down arrow keys, you leave the field after the first increase/decrease. So far only reproducible when the field is in a grid.

### Expected outcome

As he does, for example, with the field in an open dialogue popup: increase/decrease the number as often as you like and do not lose focus on the field.

### Minimal reproducible example

```java
Grid<String> grid = new Grid<>();
grid.addComponentColumn(item -> {
   return new IntegerField("Test");
});
layout.add(grid);
```

### Steps to reproduce

1. Add the snippet or something like that to the code.
2. Select the IntegerField
3. Press arrow up

Done: It increases the field value but unselects the field after that

### Environment

Vaadin version(s): 24.0.4
OS: Windows 11

### Browsers

Firefox, Edge

**Comment by vursen** [comment] 2023-11-21 13:13
Hello @IBims1ckoky!

I tested the provided example with various combinations of OS + browsers but couldn't reproduce the issue in either the latest 24.3 or 24.0.4.

Here is a video recording where I followed the reproduction steps in Windows 11 + Firefox (running under Parallels Desktop):

https://github.com/vaadin/flow-components/assets/5039436/8b5ecbd6-effc-43e5-bd20-10aea46bacad

We would appreciate it if you could provide any additional details that could help us reproduce your issue.

**Comment by IBims1ckoky** [comment] 2023-11-21 14:31
Hi! Can you show me the code of your example? :)

**Comment by vursen** [comment] 2023-11-21 14:34
> Hi! Thanks for your reply! Can you show me the code of your example? 😁

```java
@Route("grid")
public class GridView extends Div {
    public GridView() {
        Grid<String> grid = new Grid<>();
        grid.setItems("Foo", "Bar", "Baz");
        grid.addComponentColumn(item -> {
            return new IntegerField("Test");
        });
        add(grid);
    }
}
```

**Comment by rolfsmeds** [comment] 2024-01-04 14:16
Closing this as we are unable to reproduce it. Please comment if you would like it to be reopened.

**Closed by rolfsmeds** 2024-01-04 14:16 UTC
Labels: waiting for author
