### ISSUE TITLE
Paginated Grid and pagination controls

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#4000] opened 2022-11-02 08:39 UTC
### Describe your motivation

While Grid provides lazy loading and infinite scrolling, a frequent request is that Grid should also support traditional "pagination controls". Pagination in this context means a visual design where a Grid contains a single non-scrollable page of results visible at a time. You can load a different set of rows by using simple controls like "first page", "last page", "next page", "previous page", etc. There are more than one add-ons that implement this functionality, which alone is an indication that this feature is needed. It's not even too complicated to implement pagination controls on the server side, but it does take effort, especially when it comes to making the pagination controls look professional.

### Describe the solution you'd like

The optimal solution would be simple to use, at least with simple use cases such as with in-memory data - you shouldn't need to implement a custom DataProvider or something like that. 

### Describe alternatives you've considered

Should the pagination controls be entirely separate from the Grid, ie. usable also with a non-Grid pageable component?

As the number of pages increases, you need to think about controls other than just "first", "next", "previous" and "last". What if you need to find the 300th page out of 600? Pressing "next" 299 times is not an option. "Go to page" with an input field is one alternative. One possibility would be "first", "next", "+1*step", "+2*step", ..., "n * step", "prev", "last", but this leaves the question of figuring out the variables "n" and "step". Should they be automatic, based on the total number of items and the available horizontal space? Should they be configurable? With a large number of pages and a narrow Grid, you can accidentally end up with an unmanageable number of step controls (like a Chart with too many data points to display)

### Additional context

https://vaadin.com/directory/component/paginator
https://vaadin.com/directory/component/grid-pagination
https://vaadin.com/directory/component/pagination
https://vaadin.com/directory/component/pagingcomponent
https://vaadin.com/directory/component/paginationbar
https://vaadin.com/directory/component/klaudetaplutonium-pagination
https://vaadin.com/directory/component/vaadinincubator-paginator
https://vaadin.com/directory/component/vaadin-component-factoryvcf-paginator

**Comment by tomivirkki** [comment] 2022-11-02 08:42
Seems like a duplicate of https://github.com/vaadin/web-components/issues/2047

**Comment by mstahv** [comment] 2022-11-02 19:28
@OlliTietavainenVaadin, you forgot Viritin from the list. It contains PagingGrid as server side composition and a proper API to *easily* hook your backend to it. https://github.com/viritin/flow-viritin/blob/v23/src/test/java/org/vaadin/firitin/TraditionalPaging.java

**Comment by TatuLund** [comment] 2022-11-03 04:19
For reference BeanTable has paged mode, with dataprovider from callbacks implementation. Page changes will trigger new queries to callbacks. Also DataView API is supported.

https://vaadin.com/directory/component/beantable

**Comment by yuriy-fix** [comment] 2022-11-08 11:13
Closing in favour of vaadin/web-components#2047

**Closed by yuriy-fix** 2022-11-08 11:13 UTC
