### ISSUE TITLE
Eager IntegerField ignores step buttons

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow-components#5896] opened 2024-01-03 15:37 UTC
### Description

Using Vaadin 24.3.2, `IntegerField` does not fire value change events if it's configured in EAGER value change mode.

### Expected outcome

I would expect the value change listener to be called regardless of the value change mode.

### Minimal reproducible example

```
IntegerField field = new IntegerField();
field.addValueChangeListener(ev -> {
   System.out.println("Value change");
});
field.setValueChangeMode(ValueChangeMode.EAGER);
field.setStepButtonsVisible(true);
add(field);
```

### Steps to reproduce

1. Add the snippet above to a view
2. Press the step buttons
3. Notice that no value change event is fired
4. Now, remove the setValueChangeMode line
5. Repeat, and notice that value change events are fired

### Environment

Vaadin version(s): 24.3.2

**Comment by TatuLund** [comment] 2024-01-03 16:27
I think this is duplicate of https://github.com/vaadin/flow-components/issues/5863

**Closed** 2024-01-03 16:32 UTC
