### ISSUE TITLE
Button with enter shortcut listener is triggered twice when focused

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/flow-components#4757] opened 2023-03-02 02:00 UTC
### Description

If a button has `addClickShortcut(Key.ENTER)`, it gets triggered twice when hitting enter on a focused button. 

![button-double-click](https://user-images.githubusercontent.com/883698/222311164-31bdea79-080c-4de4-b49e-bca7fb7d3e9c.gif)

### Expected outcome

The button is only triggered once. 

### Minimal reproducible example

```java
var button = new Button("Add");
button.addClickShortcut(Key.ENTER);
button.addClickListener(e -> {
   Notification.show("Triggered!");
});
```

### Steps to reproduce

1. Focus button
2. Press enter

### Environment

Vaadin version(s): 24.0.0.rc1
OS: MacOS 13.1

**Comment by knoobie** [comment] 2023-03-02 04:58
Known issue https://github.com/vaadin/flow/issues/14187

**Comment by marcushellberg** [comment] 2023-03-02 14:49
Ah, I didn't think of looking in the Flow repo. I'll let the team decide what to do with the tickets.

**Comment by web-padawan** [comment] 2023-03-02 17:29
Duplicate of https://github.com/vaadin/flow/issues/14187

**Closed by web-padawan** 2023-03-02 17:29 UTC

**Comment by web-padawan** [comment] 2023-03-02 17:30
@marcushellberg Closed this issue and linked it from the original one. Thanks @knoobie for your input on this ❤️
