### ISSUE TITLE
Caption of Accordion and Details components is not longer clickable

### ISSUE THREAD

**Issue by leluna** [vaadin/flow-components#4867] opened 2023-03-24 10:33 UTC
### Description

Previously in Vaadin 23, it is possible to click on the caption to open or close an accordion or a details component. With Vaadin 24, it is no longer clickable.

### Expected outcome

The caption of the accordion should be clickable to close/open. Having to find a tiny arrow or to click on the white space intentinally is a step backward in usability.

### Minimal reproducible example

It can be directly reproduced on the documentation page https://vaadin.com/docs/latest/components/accordion 

### Steps to reproduce

Click on any caption of an accordion component in the documentation.

### Environment

Vaadin version(s):  24

### Browsers

Chrome, Firefox

**Comment by bwajtr** [comment] 2023-03-28 08:41
This is highly probably a duplicate of https://github.com/vaadin/flow-components/issues/4795

Fix was released just recently in Vaadin 24.0.2 by [this pull request](https://github.com/vaadin/web-components/pull/5700)

Closing as duplicate...

**Closed by bwajtr** 2023-03-28 08:41 UTC
