### ISSUE TITLE
[TreeGrid] Data loading can end up in a stuck state

### ISSUE THREAD

**Issue by willemv** [vaadin/flow-components#4276] opened 2022-11-30 15:44 UTC
### Description

Reattaching a `TreeGrid` in a flow application runs the risk of ending up in a stuck state.

What we are seeing in our application:
* we have a route that shows a big `TreeGrid`
* we reuse our route views (similar to using, for instance, `@UIScope` in combination with `@SpringComponent`)
* when switching from that treegrid route to another route and back again, the treegrid is shown with its initial content again
* *BUT* updates to items in the treegrid data provider are not reflected

Debugging this, we see that:
* the server-side generates the correct RPC calls. I.e. we see a UIDL message being sent from the server to the browser to update a row in the treegrid
* the `gridConnector.js` calls tries to process the update. To do so it calls the `_updateGridCache`, but that call doesn't do anything if there is still an open `callback` for the parent of the updated item present in the `treePageCallbacks` object.
* there _is_ still such a callback. That callback is never cleared.

The root cause seems to be that this callback is registered when it shouldn't be.

Hours of debugging later, that seems to be due to a combination of
* `clearCache` in `vaadin-grid-data-provider-mixin.js` replaces the `_cache` field of a grid
* `gridConnector.js` queues up creation of subcaches, and uses debounce to delay and batch these operations (I think)
* when queueing these operations, it does so by storing a reference of the cache in the `ensureSubCacheQueue` array
* the `flushEnsureSubCache` in `gridConnector.js` uses the cache reference stored in the previous step

Since the `clearCache` method can be called in between, the stored reference to the cache in the `ensureSubCacheQueue` array can have become irrelevant. I.e. `flushEnsureSubCache` is manipulating a cache that is actually not used anywhere anymore.

By changing `clearCache` in `vaadin-grid-data-provider-mixin.js` to this, I am able to avoid this problem:

```javascript
export const ItemCache = class ItemCache {
  //...
  clear() {
    this.itemCaches = {};
    this.items = {};
    this.effectiveSize = 0;
    this.size = 0;
    this.pendingRequests = {};
  }
}
//...
export const DataProviderMixin = (superClass) =>
  class DataProviderMixin extends superClass {
    // ...
    clearCache() {
      this._cache.clear(); //instead of this: this._cache = new ItemCache(this);
      this._cache.size = this.size || 0;
      this._cache.updateSize();
      this._hasData = false;
      this.__updateVisibleRows();

      if (!this._effectiveSize) {
        this._loadPage(0, this._cache);
      }
    }

```

### Expected outcome

I would expect updates to treegrid data to be shown in the treegrid.

### Minimal reproducible example

In our application I can reproduce this 
* about 1 out of 15 times in Google Chrome
* about 11 out 15 times in Apple Safari 
* not at all in Firefox

I tried but haven't been able to create a standalone reproduction of this though. Since this only manifests when you have some unlucky timings I don't think I'll be able to reproduce this in a small application.

Our application is pretty similar to this.

```java
@PageTitle("TreeGrid")
@Route(value = "treegrid", layout = MainLayout.class)
@UIScope
@SpringComponent
public class TreeGridView extends VerticalLayout
{

    public TreeGridView()
    {
        Holder a = new Holder("A", "A");
        Holder b = new Holder("B", "B");

        TreeData<Holder> treeData = new TreeData<>();
        treeData.addItem(null, a);
        treeData.addItem(a, new Holder("A_one", "original one"));
        treeData.addItem(a, new Holder("A_two", "original two"));
        treeData.addItem(null, b);
        treeData.addItem(b, new Holder("B_one", "B one"));
        Holder toUpdate = new Holder("B_two", "B two");
        treeData.addItem(b, toUpdate);
        int i = 3;
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));
        treeData.addItem(b, new Holder("B_" + i++, "B " + i));

        ItemTreeDataProvider treeDataProvider = new ItemTreeDataProvider(treeData);

        TreeGrid<Holder> treeGrid = new TreeGrid<>();
        treeGrid.setDataProvider(treeDataProvider);
        treeGrid.setSelectionMode(Grid.SelectionMode.MULTI);

        treeGrid.addHierarchyColumn(item -> item.value);
        treeGrid.addColumn(holder -> "one " + holder.getValue()).setHeader("one").setResizable(true);
        treeGrid.addColumn(holder -> "two " + holder.getValue()).setHeader("two").setResizable(true);
        treeGrid.addColumn(holder -> "three " + holder.getValue()).setHeader("three").setResizable(true);
        treeGrid.addColumn(holder -> "four " + holder.getValue()).setHeader("four").setResizable(true);
        treeGrid.addComponentColumn(holder -> {
            Select<String> select = new Select<>();
            select.setItems("one", "two", "three");
            return select;
        });
        setFlexGrow(1.0, treeGrid);
        setHeightFull();

        add(treeGrid);

        add(new Button("Update", clicked -> {
            toUpdate.setValue("updated two (" + new Date() + ")");
            treeDataProvider.refreshItem(toUpdate);
        }));
    }


    private static class ItemTreeDataProvider extends TreeDataProvider<Holder>
    {
        public ItemTreeDataProvider(TreeData<Holder> treeData)
        {
            super(treeData);
        }

        @Override
        public Object getId(Holder item)
        {
            return item.id;
        }
    }

    private static class Holder
    {
        private final String id;
        private String value;

        public Holder(String id, String value)
        {
            this.id = id;
            this.value = value;
        }

        public String getValue()
        {
            return value;
        }

        public void setValue(String value)
        {
            this.value = value;
        }
    }
}
```

You need at least one other route to be able to switch between the route with the treegrid and another
```java
@PageTitle("Start")
@Route(value = "start", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
@Uses(Icon.class)
@UIScope
@SpringComponent
public class StartView extends VerticalLayout
{
    public StartView() {
        add(new Span("Start"));
    }
}
```

### Steps to reproduce

Switch between the start and treegrid view of the sample, and press the update button in the treegrid view

Some of the time, the update will not be reflected in the treegrid.

### Environment

Vaadin version(s): 
OS: 23.2.10

### Browsers

Chrome, Safari

**Comment by willemv** [comment] 2022-12-01 07:41
I forgot that `gridConnector.js` will need to be adjusted as well to clear its `itemkeyCaches` if you change `vaadin-grid-data-provider-mixin.js` as suggested above:

```javascript

ItemCache.prototype.clearOriginal = ItemCache.prototype.clear;
ItemCache.prototype.clear = function () {
    this.clearOriginal();
    this.itemkeyCaches = {};
};
```

**Comment by DiegoCardoso** [comment] 2022-12-09 13:28
I used the snippet code to reproduce the issue, but I couldn't see it happening either in Chrome or Safari. Without a reproducible code, we can't check the bug and work on a fix for it.

**Comment by tomivirkki** [comment] 2023-01-04 14:00
I also tried with Chrome and Firefox and couldn't reproduce the issue (https://start.vaadin.com/ generated project with Vaadin version 23.3.2 used as the base).

https://user-images.githubusercontent.com/1222264/210570961-e0cef6c8-74f3-4b6a-bc72-f0ea9a77cee6.mp4

Closing. If you're still experiencing the issue, please let us know and attach a repro project as a zip file for example.

**Closed by tomivirkki** 2023-01-04 14:00 UTC
Labels: vaadin-grid, needs research
