### ISSUE TITLE
Unexpected year values with auto-open set to false (v14)

### ISSUE THREAD

**Issue by GrandyB** [vaadin/flow-components#3226] opened 2022-05-24 15:58 UTC
With auto-open enabled, typing in e.g. "01/11/93", the date picker popup is open from the moment you click into the field, and as you finish typing 93, the popup flicks over to display "1st November 1993".

This can be replicated using the v14 demo on the Vaadin site:
https://vaadin.com/docs/v14/example?embed=date-picker-basic-wc.js&import=component/datepicker/date-picker-basic.ts

However, the behaviour I believe to be a bug, is that with auto-open disabled, if you type the same thing into the text part of the field, the value is instead reflected as "1st January 0093", aka 93 AD. This value would be a fairly common use-case, and thus for our use case (not wanting auto-open on v14) would be a fairly major bug.

This can be replicated in the v14 demo for auto-open:
https://vaadin.com/docs/v14/example?embed=date-picker-auto-open-wc.js&import=component/datepicker/date-picker-auto-open.ts

**Comment by web-padawan** [comment] 2022-05-25 10:35
Confirmed. This issue also affects latest version and not only Vaadin 14:

https://user-images.githubusercontent.com/10589913/170243095-0ca2bba1-bcfc-4670-bfa3-6725aa0bfc6e.mp4

**Comment by web-padawan** [comment] 2022-05-25 10:39
There is another issue describing the underlying problem and possible solution: #1107

**Comment by yuriy-fix** [comment] 2022-05-31 10:32
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/1107

**Closed by yuriy-fix** 2022-05-31 10:32 UTC
Labels: bug, vaadin-date-picker, Severity: Minor, Impact: High
