### ISSUE TITLE
AccordionPanel not working in production

### ISSUE THREAD

**Issue by svein-loken** [vaadin/flow-components#3702] opened 2022-09-13 08:58 UTC
### Description of the bug

![image](https://user-images.githubusercontent.com/105504445/189858416-a399df81-075b-4094-a397-819f92a6cc86.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/105504445/189858167-ed010641-4507-4a0b-8230-bf3bfa8c98d6.png)

### Minimal reproducible example

npx @vaadin/cli init --empty accordion
cd accordion

```java
package com.example.application.views;
import com.vaadin.flow.component.accordion.AccordionPanel;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.router.Route;
@Route
public class AccPan extends Div {
    public AccPan() {
        add(new AccordionPanel("AccordionPanel", new Span("AccordionPanel-Content")));
    }
}
```

mvn -Pproduction spring-boot:run

### Versions

Vaadin: 23.2.0
Flow: 23.2.0
Java: JetBrains s.r.o. 17.0.2
OS: amd64 Windows 10 10.0
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0

**Comment by web-padawan** [comment] 2022-09-13 10:43
This could be fixed by adding the `@NpmPackage` and `@JsModule`, see for example `vaadin-drawer-toggle`:

https://github.com/vaadin/flow-components/blob/31de7e7525ba542f2af2eedfcb0f21e21c627fcd/vaadin-app-layout-flow-parent/vaadin-app-layout-flow/src/main/java/com/vaadin/flow/component/applayout/DrawerToggle.java#L40-L42

In case of `vaadin-accordion-panel` the code that needs to be added would look like this:

```java
@NpmPackage(value = "@vaadin/accordion", version = "23.2.0")
@NpmPackage(value = "@vaadin/vaadin-accordion", version = "23.2.0")
@JsModule("@vaadin/accordion/src/vaadin-accordion-panel.js")
```

**Comment by svein-loken** [comment] 2022-09-13 11:19
As a workaround I can confirm this is working by adding this to my project

**Comment by knoobie** [comment] 2022-09-14 08:35
Is this only caused by the fact that a single `AccordionPanel` is used or does this also affect the whole `Accordion`? If only the single `AccordionPanel`  is the culprit, that sounds less severe, since normally `Details` should be used for such cases, or? (is using `AccordionPanel` without a wrapping  `Accordion` even valid?

**Comment by web-padawan** [comment] 2022-09-14 08:46
> Is this only caused by the fact that a single AccordionPanel is used or does this also affect the whole Accordion?

This is only valid when using a single `AccordionPanel` as it lacks correct annotations.
Nothing has changed for `Accordion` in 23.2 (in fact, it hasn't changed since V14).

**Comment by svein-loken** [comment] 2022-09-15 06:13
I have used AccordionPanel alone a lot, seems to work like Details. If AccordionPanel works in development mode, it should also work in production mode, or give a warning/error.

**Comment by TatuLund** [comment] 2022-09-15 07:50
The workaround is to add the annotations mentioned in comment https://github.com/vaadin/flow-components/issues/3702#issuecomment-1245229289 to one of the views where you use AccordionPanel or extend AccordionPanel and the annotations there. These annotations are scanned build time, so they can be anywhere.

Alternatively you could add `@Uses(Accordion.class)` in your view as a workaround. This will also tell vaadin-maven-plugin to include dependencies via Accordion.java to your build.

**Closed** 2022-10-03 10:51 UTC
Labels: bug, vaadin-accordion, Severity: Major, Impact: High, workaround
