### ISSUE TITLE
Apache Netbeans log contains warning about "Duplicate entries"

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow-components#1752] opened 2021-06-03 11:38 UTC
Vaadin 14.4.7
Product Version     = Apache NetBeans IDE DEV (Build dev-0fb44eb02182e92bbb654c67781358c301fada94)
Runtime                 = OpenJDK Runtime Environment 11.0.10+9-LTS
System Locale; Encoding = en_US (nb); UTF-8

WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in vaadin__vaadin-mobile-drag-drop-1.0.0.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in mobile-drag-drop-2.3.0-rc.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-icon-2.1.0.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-iconset-svg-2.2.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-meta-2.1.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-flex-layout-2.0.3.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-overlay-behavior-2.3.4.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-resizable-behavior-2.1.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-a11y-announcer-2.1.0.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-scroll-target-behavior-2.1.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-a11y-keys-behavior-2.1.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-fit-behavior-2.2.1.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in iron-media-query-2.1.0.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in polymer-2.7.0.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in shadycss-1.8.0.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in webcomponentsjs-1.2.6.jar: META-INF/; please report to JAR creator.
WARNING [org.openide.filesystems.JarFileSystem]: Duplicate entries in vaadin-development-mode-detector-2.0.4.jar: META-INF/; please report to JAR creator.

**Comment by vlukashov** [comment] 2021-06-08 10:39
I'm closing this issue since Apache NetBeans is not one of the IDEs that the Vaadin team actively supports.

Feel free to re-open it if you find that the same issue can be reproduced by one of the IDEs mentioned in the "Development environments" section of https://github.com/vaadin/platform/releases/tag/14.6.0.

**Closed by vlukashov** 2021-06-08 10:39 UTC

**Comment by netbeansuser2019** [comment] 2021-06-17 07:18
Well, but I guess it was more related to provided Jar file than to IDE.
