### ISSUE TITLE
ComboBox.addThemeVariants() missing

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2089] opened 2021-09-03 11:14 UTC
### Description

`ComboBox.addThemeVariants()` type-safe API is missing for Vaadin 14.6.8

**Comment by web-padawan** [comment] 2021-09-03 11:36
Duplicate of #1074, sorry about the fact that it's open for so long.

**Closed by web-padawan** 2021-09-03 11:36 UTC

**Comment by web-padawan** [comment] 2021-09-03 11:38
UPD: sorry the issue was wrong, here is the correct one #454
