### ISSUE TITLE
Can't delete FooterRow(s) in Vaadin 14 

### ISSUE THREAD

**Issue by Dilyan-Galabov** [vaadin/flow-components#2561] opened 2022-01-25 13:53 UTC
**My motivation:**

The problem which I have is with Vaadin 14 FooterRow in Grid component. I want to remove already added FooterRows but that seems doesn't work.

**Solution which I want:**
To remove already created FooterRows in Vaadin Grid.

**Alternatives I've considered:**
I've tried with collection methods which grid.getFooterRows() provide to me - removeAll(), clear(), and remove() by iterating one by one.

**Additional context:**
I've seen in the Github issue: https://github.com/vaadin/flow-components/issues/1538 that there is a conversation regarding it but there is not having an answer.

**Comment by yuriy-fix** [comment] 2022-02-01 11:07
Closing as a duplicate of #1538.

**Closed by yuriy-fix** 2022-02-01 11:07 UTC
