### ISSUE TITLE
Lumo utilities get loaded despite not being listed

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow-components#1858] opened 2021-07-01 14:16 UTC
Steps to reproduce:
Create Flow starter via start.vaadin.com
Add a Div to the about view

```
        Div d = new Div();
        d.setHeight("500px");
        d.setWidth("500px");
        d.addClassName("bg-error");
        add(d);
```
The Div shows red in the application despite Lumo utilities not being declared to be loaded (theme.json contains {"lumoImports":["typography","color","spacing","badge"]} )

Vaadin version 21.0.0.alpha9
Browsers: Firefox 89.0.2 (64-Bit); Chrome 91.0.4472.114 (Official Build) (x86_64)
OS: macOS 10.14.6

Related: vaadin/web-components#2175

**Comment by web-padawan** [comment] 2021-07-06 09:19
The root cause is the same as described at https://github.com/vaadin/web-components/issues/2175#issuecomment-874601901. Closing.

**Closed by web-padawan** 2021-07-06 09:19 UTC
