### ISSUE TITLE
TimePicker coverts lowercase "pm" to "AM"

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow-components#3028] opened 2022-04-15 13:24 UTC
### Description

![image](https://user-images.githubusercontent.com/66945385/163575836-34fecaa3-bad5-4e31-a739-5e992b4dab44.png)
When we enter "pm" into the TimePicker, the field converts this value to "AM" after losing focus.

TimePicker-Bug

This case sensitivity appears to be happening on the JavaScript side. We can confirm that the PARSER field in the TimePicker class is receiving a String value that is already converted to ISO 8601 format (i.e. "2022-03-01T23:45:00") from the web component.

Since most users in the United Status do not expect to have to capitalize "PM" when entering a time, this creates a confusing experience when interacting with the Vaadin TimePicker.

### Expected outcome

Entering "pm" in lowercase should be recognized correctly by the TimePicker and not revert the time to "AM" when using 12-hour format.

### Minimal reproducible example

```java
TimePicker timePicker = new TimePicker();
add(timePicker);
```

### Steps to reproduce

Input any time using lowercase "pm" into the TimePicker in 12-hour format. Observe this component will revert the time to "AM" upon losing focus.

### Environment

- Vaadin / Flow version: 21.0.9+
- Java version: 8+
- OS version: All (Windows, Mac, Linux)

**Comment by web-padawan** [comment] 2022-04-18 07:54
Duplicate of #1179

**Closed by web-padawan** 2022-04-18 07:54 UTC
