### ISSUE TITLE
Grid FooterRow sets tabIndex of the cell to 0, messing up the tab order

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#977] opened 2021-05-11 13:29 UTC
Vaadin 14.6.0; Firefox 88.0.1 and Chrome Latest.

Paste the following example into Skeleton Starter:

```java
public class MainView extends VerticalLayout {

    public MainView() {
        final Grid<String> grid = new Grid<>();
        final Grid.Column<String> col1 = grid.addColumn(it -> it);
        final Grid.Column<String> col2 = grid.addColumn(it -> it);
        final FooterRow footerRow = grid.appendFooterRow();
        footerRow.getCell(col1).setComponent(new TextField());
        footerRow.getCell(col2).setComponent(new TextField());
        add(grid);
    }
}
```

A grid with two columns is created, hosting two text fields in the footer. Focusing the first text field and pressing Tab should focus the next text field; however instead a table cell (`td`) is selected. The reason is that `td` has tabindex of 0 for no apparent reason.

Moreover, pressing Enter in the TextField component will set the parent `td` tabindex to zero (again for no apparent reason), breaking the tab ordering (and even focusing the parent `td` immediately, at least on Firefox).

**Comment by vlukashov** [comment] 2021-05-18 11:06
This is likely a duplicate of https://github.com/vaadin/vaadin-grid/issues/1880

**Comment by sissbruecker** [comment] 2021-05-19 14:53
> A grid with two columns is created, hosting two text fields in the footer. Focusing the first text field and pressing Tab should focus the next text field; however instead a table cell (td) is selected. The reason is that td has tabindex of 0 for no apparent reason.

Tested this with the changes from https://github.com/vaadin/web-components/issues/1552 and can confirm that it has been fixed as part of that.

> Moreover, pressing Enter in the TextField component will set the parent td tabindex to zero (again for no apparent reason), breaking the tab ordering (and even focusing the parent td immediately, at least on Firefox).

This is the intended behaviour as part of the grids accessiblity / keyboard controls:
- The user can focus into the grid and navigate between cells using the arrow keys
- Pressing enter or F2 while a cell is focused the grid switches to interaction mode, which tries to focus any focusable element within the cell (such as an input), allowing the user to interact with that element. This mode also enables when focusing an input in a cell through mouse click.
- In interaction mode keyboard input, for example arrow keys, goes into the focused element, instead of triggering cell navigation
- Pressing enter or F2 or escape allows the user to exit interaction mode, which then focuses the containing cell, so that the user can continue navigating the cells using the keyboard

It's arguable whether enter should also exit interaction mode, but ATM that's how it's supposed to work. If the element in the cell wants to handle Enter in a different manner it can decide to stop propagating the keyboard event.

One thing that does not work currently is focusing a cell with a vaadin-textfield and then hitting enter. This should focus the text field, but does not. I will create a separate issue for that.

**Closed by sissbruecker** 2021-05-19 14:53 UTC
