### ISSUE TITLE
RadioButtonGroup style of setReadOnly(true) same as setEnabled(false)

### ISSUE THREAD

**Issue by AlexeiBugai** [vaadin/flow-components#1852] opened 2021-06-30 11:19 UTC
### Description
RadioButtonGroup style of setReadOnly(true) same as setEnabled(false)

### Expected outcome

RadioButtonGroup should have same 'read only' style like all others components

### Actual outcome

RadioButtonGroup style of setReadOnly(true) same as setEnabled(false)

### Minimal reproducible example

		RadioButtonGroup<String> field1 = new RadioButtonGroup<>();
		field1.setReadOnly(true);
		field1.setItems("Option one", "Option two", "Option three");
		field1.setValue("Option one");
   	        

		RadioButtonGroup<String> field2 = new RadioButtonGroup<>();
		field2.setEnabled(false);
		field2.setItems("Option one", "Option two", "Option three");
		field2.setValue("Option one");

### Steps to reproduce

1. Add 2 RadioButtonGroup components to a page.
2. Set one disabled, second one read only

### Environment

- v20.0.3
- Windows 10

### Browsers Affected

All

**Comment by yuriy-fix** [comment] 2021-07-06 10:17
Closing this as a duplicate of https://github.com/vaadin/web-components/issues/822.

**Closed by yuriy-fix** 2021-07-06 10:17 UTC
