### ISSUE TITLE
ComboBox custom value set event called twice in some cases

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/flow-components#2285] opened 2021-10-26 12:24 UTC
### Description

In some cases, listeners added via `ComboBox#addCustomValueSetListener` are called twice with the same value. This happens when the user adds a custom value to a combo box and then hit <kbd>Enter</kbd> which triggers the first `custom-valuse-set` event. After that, when the user focus out from the combo box (either by hitting <kbd>Tab</kbd> or clicking outside) another event is fired. If the application on the backend do not treat the custom entries to avoid duplication, that may lead to the same value being added twice on the combo box.

### Expected outcome

Listeners are called only once.

### Actual outcome

Listeners are called twice for the same value if user hits <kbd>Enter</kbd> after typing.

### Live Demo (optional)

It can be seen on this recording extracted from [the docs page](https://vaadin.com/docs/latest/ds/components/combo-box#custom-value-entry):
![combo-box-custom-value](https://user-images.githubusercontent.com/262432/138876609-c605f6c2-9ed3-413a-8154-b03cdc3d4ddc.gif)

While debugging it, I added a `custom-value-set` listener on DevTools to log the stack trace on both calls and that's what I got:
![image](https://user-images.githubusercontent.com/262432/138876963-fe73e770-fe49-4fde-817e-65847cd499bc.png)

I tried to reproduce this with the web-component alone, and could not see the same behavior there.

### Browsers Affected

- Chrome

**Comment by web-padawan** [comment] 2022-02-21 13:29
I can't reproduce this issue using Vaadin 22 and 23, nor in the [Vaadin 14 example](https://vaadin.com/docs/v14/ds/components/combo-box/#custom-value-entry).

Did some investigation and it turns out this was fixed by #2340 (backported to V14 via #2346).
The only version affected is Vaadin 21 and we no longer maintain it. Closing as fixed.

**Closed by web-padawan** 2022-02-21 13:29 UTC
Labels: bug, vaadin-combo-box, Severity: Minor, Impact: High
