### ISSUE TITLE
[combo-box] Pre-select value by code, not add the "focus" attribute to DOM.

### ISSUE THREAD

**Issue by guygoldwasser** [vaadin/flow-components#3115] opened 2022-05-02 13:20 UTC
### Description

vaadin 14.5.3
while select value, 2 attributes appear in selected dom, one for selection (which style to the selected sign) and focused flag that scroll into selected when reopen the combo.

While set value by code, the selection does appear but not the focus and it seems that this behave is confusing our customers.
I assume this is a bug, and if not, will be glad to get a hook while consulting if this worth its own API.

### Expected outcome

Code selection should result identical behave to manual selection

### Minimal reproducible example

ComboBox<Company> companiesCombo = new ComboBox<Company>();;
companiesCombo.setItems(companies);
companiesCombo.setValue((Company) getSelectedCompany());

### Steps to reproduce

load Combo with some set and pre set some value from the list

### Environment

Vaadin version(s): 
OS: WIN

### Browsers

Chrome

**Comment by yuriy-fix** [comment] 2022-05-03 10:08
@web-padawan could you please take a look at this one?

**Comment by web-padawan** [comment] 2022-05-03 11:44
Tested with both latest (23.1) and the Vaadin 14.8 version and the following code:

```java
ComboBox<String> comboBox = new ComboBox<>();
comboBox.setItems("Value", "Option one", "Option two");
comboBox.setValue("Value");
add(comboBox);
```

As you can see on the screenshot, the focused index is not set to the matching item:

<img width="197" alt="Screenshot 2022-05-03 at 14 33 31" src="https://user-images.githubusercontent.com/10589913/166445591-a0d29730-96b5-4834-9a04-21fd32410a2b.png">

This is different from the web component where the focused index is set correctly:

```html
<vaadin-combo-box></vaadin-combo-box>

<script>
  const comboBox = document.querySelector('vaadin-combo-box');
  comboBox.filteredItems = ['Value', 'Option one', 'Option two'];
  comboBox.value = 'Value';
</script>
```

<img width="209" alt="Screenshot 2022-05-03 at 14 43 17" src="https://user-images.githubusercontent.com/10589913/166446763-2013025c-74d0-4302-8db4-eeb739caba8f.png">

**Comment by web-padawan** [comment] 2022-05-03 13:03
I was able to reproduce this in the web component by setting `selectedItem` before `filteredItems` are set:

```html
<vaadin-combo-box item-label-path="label" item-value-path="key"></vaadin-combo-box>

<script type="module">
  const comboBox = document.querySelector('vaadin-combo-box');

  const items = [
    { label: 'Item 0', key: '0' },
    { label: 'Item 1', key: '1' },
    { label: 'Item 2', key: '2' },
  ];
  comboBox.selectedItem = items[0];
  comboBox.filteredItems = items;
</script>
```

Based on my understanding, this is what happens in Flow component. Looks like it can be fixed by updating web component [input element value check](https://github.com/vaadin/web-components/blob/8be43cf83102a6b9ccf309687446e590ce0164e8/packages/combo-box/src/vaadin-combo-box-mixin.js#L974) to also accept `this._getItemLabel(this.selectedItem)` and set focused index accordingly.

**Closed** 2022-05-05 11:51 UTC
Labels: bug, vaadin-combo-box, Severity: Minor, Impact: High
