### ISSUE TITLE
Grid Flow - render data incorrect after set empty list

### ISSUE THREAD

**Issue by i-treee** [vaadin/flow-components#2361] opened 2021-11-19 07:14 UTC
### Description
Grid displays data incorrectly after an empty list being set. 

It shows old data instead of new data.

This occurs in both Grid.setItems(emptyList()) and using filtering in Data Provider.

### Steps to reproduce
This issue can be reproduced on Vaadin Design System official page (https://vaadin.com/docs/latest/ds/components/grid/#filtering)
1. Open the latest documentation page for Grid
2. Go to Filtering section
3. Filter name column with "Zoe", the grid shows only 4 items
4. Type 'x', so the filter becomes "Zoex", the grid shows no items
5. Clear the filter, the grid should shows all items start with A, but now it shows all 4 Zoe's.
6. Type "Anna", it still shows "Zoe" items.
7. Type "Peter", it shows two "Zoe" items. (Actual there are 2 Peter's)

Note: You can compare with v14 page which works correctly.

### Environment
- Vaadin Flow v21.0.6

**Comment by tomivirkki** [comment] 2021-11-19 07:24
Hi @i-treee 

This was caused by an unfortunate regression in V21+ which has been fixed in https://github.com/vaadin/web-components/pull/3081

Until the fix gets released, you can workaround the issue with `grid.getElement().executeJs("this.__virtualizer.update()");` (or `grid.__virtualizer.update()` in JS)

**Comment by tomivirkki** [comment] 2021-11-23 07:36
The fix is released with [Vaadin 21.0.7](https://github.com/vaadin/platform/releases/tag/21.0.7)

**Closed by tomivirkki** 2021-11-23 07:36 UTC

**Comment by alexrm84** [comment] 2021-11-23 09:46
Hi, I checked the bug on version 20.0.7
The error has persisted.
The screenshots show the results of items 3 and 7 from the first message.
The buttons are also not displayed in the last column.

![screenshot 2021-11-23 12-28-48](https://user-images.githubusercontent.com/40359224/143001282-8e124da1-5646-4a47-987e-4a7aca5e73d7.png)
![screenshot 2021-11-23 12-29-53](https://user-images.githubusercontent.com/40359224/143001285-514a3e3d-2592-4c4f-a568-dab6c39387a1.png)

**Comment by tomivirkki** [comment] 2021-11-23 10:11
> Hi, I checked the bug on version 20.0.7

I assume you mean 21.0.7?
Can you provide a code example that we can use to examine the issue you're facing? The bug described in the description of this issue has been confirmed to work with the new release. You can try the new version at https://vaadin.com/docs/v21/ds/components/grid#filtering

**Comment by alexrm84** [comment] 2021-11-23 11:26
That's right, version 21.0.7
Regarding the error, the problem was in the caches.
Manual cleaning fixed the problem.
Thank you for your time.
