### ISSUE TITLE
setColumnOrder() on Grid in Vaadin Flow causes the getSortOrder() list to increment infinitely in the event of the sort listener [2 days]

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#2102] opened 2021-09-08 17:04 UTC
### Description

This was opened as requested by Tatu Lund (https://github.com/TatuLund) from the following StackOverFlow question: https://stackoverflow.com/questions/69096844/setcolumnorder-on-grid-in-vaadin-flow-seems-to-cause-the-getsortorder-list-t

I have also created a Github repo which you can run to see the bug/issue directly at: https://github.com/FollowSteph/VaadinGridBugReport To replicate just change the sort order once then click on the Reset button a number of times. Then change the sort order once more and you'll find that the List of GridSortOrder just keeps going up to match the number of times the reset button is clicked (multiplied by the number of GridSortOrder passed to grid.sort() where instead it should be two after the Reset button is clicked. This only happens if the grid.setColumnOrder() is also called.

To quote the stackoverflow question (there's a lot more details in the question): "The main issue is that the GridSortOrder list just keeps incrementing in size for the event in the sort listener rather than replacing the sortorder list. I believe this is a bug within Vaadin 14-21 because it only happens if I call setColumnOrder() in the reset method below (removing that call it works as expected). In other words calling setColumnOrder() seems to add the list of GridSortOrder to the event in the sort listener when it should be replacing it. This is actually also true if you do grid.getSortOrder() in the listener, meaning it's not just the event but also the grid that is compromised." Then further "If I remove grid.setColumnOrder() from the above then the List<GridSortOrder> works as expected and is two in the event listener. " And "With that in mind if you debug grid.setColumnOrder() it seems to call updateClientSideSorterIndicators(sortOrder) which is what I believe is the cause and is where it's being added to the GridSortOrder list."

### Expected outcome

See above.

### Actual outcome

See above.

### Live Demo (optional)

https://github.com/FollowSteph/VaadinGridBugReport

### Minimal reproducible example

https://github.com/FollowSteph/VaadinGridBugReport

### Steps to reproduce

See above along with sample code. 

### Environment

Vaadin 14-21. 

### Browsers Affected

All browsers seem to be affected.

**Comment by sissbruecker** [comment] 2021-11-02 10:59
Can confirm this is a bug. This seems to be caused by repeated calls to `Grid.updateClientSideSorterIndicators`, which leads to an incorrect number of sort orders being reported from the client.

Simplified reproduction:
```java
        Grid<String> grid = new Grid<>();
        grid.setItems(List.of("1", "2", "3"));

        Grid.Column<String> column = grid.addColumn(item -> item)
                .setHeader("Name");

        grid.setMultiSort(true);
        grid.sort(List.of(new GridSortOrder<>(column, SortDirection.ASCENDING)));
        grid.addSortListener(event -> System.out.println("sort order size: " + grid.getSortOrder().size()));

        Button updateButton = new Button("Update client sort indicators", click -> {
            // Use setColumnOrder to trigger private updateClientSideSorterIndicators
            grid.setColumnOrder(column);
        });

        add(grid, updateButton);
```

Steps:
- click `Update client sort indicators` five times
- click on column to change sort

Expected:
- Java console output: `sort order size: 1`

Actual:
- Java console output: `sort order size: 5`

**Comment by TatuLund** [comment] 2021-11-03 06:54
This issue regression after this fix to the issue https://github.com/vaadin/vaadin-grid-flow/issues/995

I.e. previously all sort indicators were cleared first. The fix added condition to optimize this so that un-necessary client originated requests would not happen.

**Comment by web-padawan** [comment] 2022-06-14 08:11
> This seems to be caused by repeated calls to Grid.updateClientSideSorterIndicators,

I investigated this a bit more, and the underlying problem appears to be caused by calling `setColumnOrder()` that results in columns staying in the same order as before (so the visual order of columns in the DOM does not change).

When columns are removed, the `vaadin-grid` web component removes `vaadin-grid-sorter` elements that are [no longer connected](https://github.com/vaadin/web-components/blob/5ddcd5872e4b1ace47bf98b3efd8e0fdb831f050/packages/grid/src/vaadin-grid-dynamic-columns-mixin.js#L115). This happens when the columns are actually reordered, but not when their order remains the same.

**Comment by web-padawan** [comment] 2022-06-14 15:44
I managed to reproduce the issue in the web component by using logic that Flow counterpart uses:

## Reproduction

<details>
<summary>HTML snippet</summary>

```html
<vaadin-grid multi-sort>
  <vaadin-grid-column id="firstname" path="name.first">
    <template class="header">
      <vaadin-grid-sorter path="name.first">First name</vaadin-grid-sorter>
    </template>
  </vaadin-grid-column>
  <vaadin-grid-column id="lastname" path="name.last">
    <template class="header">
      <vaadin-grid-sorter path="name.last">Last name</vaadin-grid-sorter>
    </template>
  </vaadin-grid-column>
</vaadin-grid>

<button id="order">Reorder</button>

<script type="module">
  import '@vaadin/polymer-legacy-adapter/template-renderer.js';
  import '@vaadin/grid';
  import '@vaadin/grid/vaadin-grid-sort-column.js';
  import { users } from '../packages/grid-pro/test/visual/users.js';

  const grid = document.querySelector('vaadin-grid');
  grid.items = users;

  const firstName = grid.querySelector('#firstname');
  const lastName = grid.querySelector('#lastname');

  const order = document.querySelector('#order');
  order.addEventListener('click', () => {
    const directions = grid._mapSorters();

    grid.removeChild(firstName);
    grid.removeChild(lastName);

    firstName.innerHTML = '';
    lastName.innerHTML = '';

    firstName.innerHTML = `
      <template class="header">
        <vaadin-grid-sorter path="name.first">First name</vaadin-grid-sorter>
      </template>
    `;

    lastName.innerHTML = `
      <template class="header">
        <vaadin-grid-sorter path="name.last">Last name</vaadin-grid-sorter>
      </template>
    `;

    grid.appendChild(lastName);
    grid.appendChild(firstName);

    grid._updateOrders(grid._columnTree, null);

    setTimeout(() => {
      const sorters = Array.from(grid.querySelectorAll('vaadin-grid-sorter'));

      sorters.forEach((sorter) => {
        sorter.direction = null;
      });

      directions.reverse().forEach(({ path, direction }) => {
        sorters.forEach((sorter) => {
          if (sorter.getAttribute('path') === path && sorter.direction !== direction) {
            sorter.direction = direction;
          }
        });
      });
    });
  });
</script>
```

</details>

Steps to reproduce:

1. Sort grid by first name (click the sorter)
2. Click the "Reorder" button to update columns
3. Check that `grid._sorters` contains orphan sorter

## Problems

There are two problems in this case that need to be fixed:

1. The active sorter being removed after the `<template>` is re-created, so [this condition](https://github.com/vaadin/web-components/blob/5ddcd5872e4b1ace47bf98b3efd8e0fdb831f050/packages/grid/src/vaadin-grid-dynamic-columns-mixin.js#L111-L113) needs to be updated to also cleanup sorters that don't have `parentNode` - that needs to be fixed in the web component.
2. When reordering columns programmatically (by removing and adding to the DOM), the `MutationObserver` does not run in case if the resulting order remains the same. This is exactly what happens in the [above comment](https://github.com/vaadin/flow-components/issues/2102#issuecomment-957332969).

The second case could be fixed by calling `grid._observer.flush()` which needs to be done after columns are detached, but before they get re-attached. It's not clear for me how to do that in `GridColumnOrderHelper` without something like `grid.getElement().executeJs("this._observer.flush()").then()` which would introduce an additional roundtrip.

**Closed** 2022-06-20 10:59 UTC
Labels: bug, Severity: Minor, Impact: High, needs research
