### ISSUE TITLE
DatePicker 22.0 : There's is still missing a handleUnparsableDateString as it was present in Vaadin 8

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#2454] opened 2021-12-21 17:07 UTC
After implementing methods setDateFormat(s), getDateFormat() in class DatePickerI18n (#911) there's still missing a method to handle a client unparsable input string on the serve as it was in Vaadin 8 DateField::handleUnparsableDateString(...)

In Java a DatePicker-Instance does not show any error after leaving it's field with an unparsable string as does with JavaScript.
As there's no possibility to handle the unparsable string on the server side, the user can not distinguish between an empty value and an unparsable string.
if the field is not requried, it looks like as if the unparsable string was accepted.

Following the demo for DatePicker V22, the component gets red for an unparsable string on TypeScript, but the component does not show up for java, so i could not test it there, but only in my code.

**Comment by rolfsmeds** [comment] 2021-12-28 13:25
Closing as duplicate of #2176 (missing validation) and #2466 (server-side fallback parsing mechanism)

**Closed by rolfsmeds** 2021-12-28 13:25 UTC
Labels: enhancement, vaadin-date-picker
