### ISSUE TITLE
Conditional edit of cells in GridPro

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#4663] opened 2023-02-09 14:25 UTC
### Describe your motivation

I have a use case , where the editability of a certain cell depends on the state of the object displayed in the row.
In the cookbook, there is already an article for this: https://cookbook.vaadin.com/grid-pro-conditional-edit

I do not think that this is the ideal solution.
According to the documentation, users should use the built in editors (using .text(...) and not .custom(...)).
And this is also what I would prefer, because if I add a custom text field editor, there are some problems for the end-user:
- editing does not start when user starts typing
- selectAll is not applied for the custom editor

The built-in editor is far better

### Describe the solution you'd like

From my point of view, the solution could be implemented via grid.addCellEditStartedListener

`rulesGrid.addCellEditStartedListener(event -> {`
`  T myItem = event.getItem();`
`  event.disableEditor(!myItem.canEditPropertyX());`
`});`

### Describe alternatives you've considered

An alternative would be the improvement of the integration of custom editors, so that e.g. a TextField as custom editor behaves exactly in the same way as the built-in text editor

**Comment by knoobie** [comment] 2023-02-09 14:42
Duplicate of https://github.com/vaadin/flow-components/issues/4524

**Comment by sissbruecker** [comment] 2023-02-10 07:53
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/4524, please add your concerns there if you have something to add.

**Closed by sissbruecker** 2023-02-10 07:53 UTC
