### ISSUE TITLE
Grid/GridPro - LitRenderer does not support 'nothing' sentinel or 'ifDefined' function to remove attributes

### ISSUE THREAD

**Issue by RhonanMS** [vaadin/flow-components#6218] opened 2024-04-19 09:52 UTC
### Description

I have a Lit template with (non-boolean) HTML attributes that should only be shown if the corresponding value for them is non-null. 
According to the Lit documentation (https://lit.dev/docs/templates/expressions/#removing-attribute) this should be possible by using the 'nothing' sentinel or the 'ifDefined' function in the Lit template:

`<p attribute=\"${item.attributeValue ?? nothing}\">${item.value}</p>`
or
`<p attribute=\"${ifDefined(item.attributeValue)}\">${item.value}</p>`

However, if I try this within a LitRenderer in my Grid, in both cases I get at least one of the following error message in the browsers' JavaScript console:

> There seems to be an error in Vaadin Grid:
> nothing is not defined
> Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose

> There seems to be an error in Vaadin Grid:
> ifDefined is not defined
> Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose

### Expected outcome

I expected the LitRenderer to support the nothing sentinel and/or the ifDefined function to render the template without the attribute if it's value is not defined in the Grid.

### Minimal reproducible example

```java
import java.util.ArrayList;
import java.util.List;

import com.vaadin.flow.component.gridpro.GridPro;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.data.renderer.LitRenderer;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;

@PageTitle("Start")
@Route(value = "start")
@RouteAlias(value = "")
public class StartView extends HorizontalLayout {

	public static class TableData {
		public String text;
		public String className;

		public TableData(String text, String className) {
			this.text = text;
			this.className = className;
		}

		public String getText() {
			return this.text;
		}

		public String getClassName() {
			return this.className;
		}
	}

	private static final String COLUMN_TEMPLATE_WITHOUT_SENTINEL = """
			<p class="${item.class}">${item.text}</p>
			""";
	private static final String COLUMN_TEMPLATE_WITH_SENTINEL = """
			<p class="${item.class ?? nothing}">${item.text}</p>
			""";
	private static final String COLUMN_TEMPLATE_WITH_IFDEFINED = """
			<p class="${ifDefined(item.class)}">${item.text}</p>
			""";

	public StartView() {
		final GridPro<TableData> grid = new GridPro<>();
		final LitRenderer<TableData> rendererNoSentinel = LitRenderer.<TableData>of(COLUMN_TEMPLATE_WITHOUT_SENTINEL)
				.withProperty("text", TableData::getText).withProperty("className", TableData::getClassName);
		grid.addColumn(rendererNoSentinel).setHeader("LitItem without 'nothing' Sentinel");
		final LitRenderer<TableData> rendererSentinel = LitRenderer.<TableData>of(COLUMN_TEMPLATE_WITH_SENTINEL)
				.withProperty("text", TableData::getText).withProperty("className", TableData::getClassName);
		grid.addColumn(rendererSentinel).setHeader("LitItem with 'nothing' Sentinel");
		final LitRenderer<TableData> rendererIfDefined = LitRenderer.<TableData>of(COLUMN_TEMPLATE_WITH_IFDEFINED)
				.withProperty("text", TableData::getText).withProperty("className", TableData::getClassName);
		grid.addColumn(rendererIfDefined).setHeader("LitItem with 'ifDefined' function");
		
		final List<TableData> data = this.createTableData();
		grid.setItems(data);
		
		this.add(grid);
		
	}

	private List<TableData> createTableData() {
		final List<TableData> data = new ArrayList<>();
		final TableData data1 = new TableData("Test 1", null);
		final TableData data2 = new TableData("Test 2", "important");
		data.add(data1);
		data.add(data2);
		return data;
	}
}
```

### Steps to reproduce

1. Run the above sample in a Vaadin 24 / Java 17 environment
2. Open the Browser JavaScript console
3. The first error message mentioned above should appear two times.
4. Comment out lines 49 to 51 (`final LitRenderer... rendererSentinel` and the following two lines) and re-run
5. The second error message mentioned above should appear two times.

### Environment

Vaadin version(s): 24.3.6, 24.3.9
OS: Windows 10
Browsers: probably independent of browsers used, Safari was not tested.

### Browsers

Chrome, Firefox, Edge

**Comment by Legioth** [comment] 2024-04-19 10:24
Seems like a duplicate of https://github.com/vaadin/flow-components/issues/5978

**Closed by Legioth** 2024-04-19 10:24 UTC
