### ISSUE TITLE
Styling for Grid column headers

### ISSUE THREAD

**Issue by celluj34** [vaadin/flow-components#5343] opened 2023-07-14 19:51 UTC
### Describe your motivation

I can style grid cell contents, but I also want to be able to style the column headers too.

### Describe the solution you'd like

Perhaps something similar to or reuse `cellPartNameGenerator`, where you can inspect some type on the `GridColumn` to determine if the item is a cell or header. Then we can continue to use `vaadin-grid::part(highlight)` in css to style.

Or perhaps `vaadin-grid-header::part(highlight)` to differentiate cells from headers.

### Describe alternatives you've considered

I have tried to use css IDs and classes to change style but I cannot figure it out. Maybe I am doing it wrong but even with using the IDs directly on the `table` element my styles are not being applied.

**Comment by rolfsmeds** [comment] 2023-08-10 10:46
The Grid currently doesn't have support for applying class or part names to header (or footer) cells. There is a feature request ticket about this here: https://github.com/vaadin/web-components/issues/1434

The best you can do right now is to use a custom renderer for your header cells' contents: https://vaadin.com/docs/latest/components/grid#column-headers-footers

One complicating factor is that the `vaadin-grid-cell-content` element that wraps it inside the cell applies some padding that prevents you from filling the entire header cell with a background color, if that's something you want to do. You can remove that padding by a two-pronged approach like this:

```
vaadin-grid::part(header-cell) {
  --my-cell-padding: 0;
}
vaadin-grid-cell-content {
  padding: var(--my-cell-padding, var(--lumo-space-xs) var(--lumo-space-m));
}
```

Closing as a duplicate of the aforementioned issue.

**Closed by rolfsmeds** 2023-08-10 10:46 UTC
Labels: feature request
