### ISSUE TITLE
GridPro: render blanks out and editor loses value when dialog is opened inside change handler

### ISSUE THREAD

**Issue by drewharvey** [vaadin/flow-components#3436] opened 2022-07-06 01:35 UTC
### Description

When a Dialog is opened inside of an editor component's change handler, the value shown by the renderer is empty and the value of the editor component is discarded.

![gridpro-editor-dialog](https://user-images.githubusercontent.com/2496955/177449134-65649eea-79ae-4693-b139-4911becf5ae2.gif)

### Expected outcome

I would expect, when the dialog is opened, for the value selected in the editor to stick.

### Minimal reproducible example

```

public void init() {
    GridPro<Person> grid = new GridPro<>();

     ComboBox<String> cb = new ComboBox<>();
     cb.addValueChangeListener(e -> {
        if (e.isFromClient()) {
              Dialog d = new Dialog();
              d.add(new Text("dsfsd"));
              d.open();
        }
     });
     cb.setItems("Jeff", "Brandon", "Kyle");

     grid.addEditColumn(Person::getName)
           .custom(cb, (item, val) -> item.setName(val))
           .setHeader("Field 1");

     grid.setItems(generatePeople());

     add(grid);
  }

  // generate grid data
  private List<Person> generatePeople() {
     List<Person> people = new ArrayList<>();
     for (int i = 0; i < 300; i++) {
        people.add(new Person(false, "Jeff"));
     }
     return people;
  }

  // grid bean
  private static class Person {
     private String name;

     public Person(String name) {
        this.name = name;
     }

     public String getName() {
        return name;
     }

     public void setName(String name) {
        this.name = name;
     }
  }
```

### Steps to reproduce

See example above.

### Environment

Vaadin version(s): tested on 23.0.9 and 23.1.3
OS: MacOS

### Browsers

Edge

**Comment by web-padawan** [comment] 2022-07-06 06:25
Duplicate of #2186

**Closed by web-padawan** 2022-07-06 06:25 UTC
