### ISSUE TITLE
Pressing Enter when button is focused AND has a clickShortCut on Key.ENTER will fire the click listener twice

### ISSUE THREAD

**Issue by willemv** [vaadin/flow-components#2958] opened 2022-03-30 19:18 UTC
### Description

When you 
* add a `Button` with a click listener
* add a click shortcut to that button
* get focus on the `Button`
* press `Enter` on your keyboard

The click listener will be called twice.

### Expected outcome

The listener should only be called once

### Actual outcome

The listener is called twice

### Live Demo (optional)

A screenshot or video with issue reproduced.

### Minimal reproducible example

```
        AtomicInteger counter = new AtomicInteger(0);

        Button counterButton = new Button("Testing", click -> {
            Notification.show("Count: " + counter.getAndIncrement());
        });
        counterButton.addClickShortcut(Key.ENTER);
        add(counterButton);
```

### Steps to reproduce

Clear steps describing how to reproduce the issue.

* add a `Button` with a click listener
* add a click shortcut to that button
* get focus on the `Button`
* press `Enter` on your keyboard

### Environment
- Vaadin Flow v23.0.3

**Comment by knoobie** [comment] 2022-03-31 07:27
Sadly working as intended https://github.com/vaadin/flow/issues/8037#issuecomment-789674976

**Comment by sissbruecker** [comment] 2022-03-31 08:14
I can see how this can be problematic, but I would also argue that it's not a component issue and, if at all, should be addressed in Flow itself. Closing the issue.

**Closed by sissbruecker** 2022-03-31 08:14 UTC
