### ISSUE TITLE
TextArea blocks input in Chrome and Edge browsers

### ISSUE THREAD

**Issue by Izum-si** [vaadin/flow-components#6361] opened 2024-06-10 12:57 UTC
### Describe the bug

In some Chrome or Edge browsers Vaadin Flow's TextArea blocks keyboard input as if the control was disabled: instead of input area only a grey rectangle is visible and the control can't even be focused.

Our users started noticing in Chrome this start of May, but it's in the last couple of weeks that the reports became more frequent and the problem apparent in Edge as well.

Firefox has no such problem.

### Expected-behavior

Input enabled and characters can be input to TextArea from keyboard.

### Reproduction

The same happens in the demo projects as well: https://vaadin.com/docs/latest/components/text-area

It doesn't happen in _every_ Chrome/Edge browser though. Some of our users have this problem, others don't. As far as we were able to determine, it never happens if the Guest browser profile is used, nor if the browser is run with all extensions disabled (that is, with command switch --disable-extensions). Disabling extensions one by one, doesn't help however.

### System Info

Windows 10, 11. Chrome v125.0.6422.142, Edge v125.0.2535.92  (also in earlier versions of both browsers - not sure exactly from which version)

**Comment by ZheSun88** [comment] 2024-06-10 13:18
I have Edge v125.0.2535.92 and Chrome 125.0.6422.142 on Windows 11. 

i am NOT able to reproduce the issue mentioned here.

**Comment by sissbruecker** [comment] 2024-06-18 11:59
I also couldn't reproduce the issue on either Windows 10 or 11, with either Chrome or Edge.

Since you mentioned that the component looks different when it doesn't work, a screenshot might be helpful. Otherwise there isn't much to go on here.

**Comment by Izum-si** [comment] 2024-06-21 10:27
As I already said, this only happens in _some_ browsers (could be tied to some extensions - since disabling extensions completely solves the problem - but we haven't been able to determine which of them or why).
I'll ask our users whom reported the problem to take some screenshots and will post them here, when I get them.
Meanwhile, I'm sure you'll get similar reports from other Vaadin users, since quite a few people use Chromium-based browsers and some are bound to have a "winning" combination of settings that causes this.

**Comment by sissbruecker** [comment] 2024-06-21 10:36
You might then also want to collect information about which extensions are installed, from the available information these currently look like the most likely candidate for causing the issue.

**Comment by yuriy-fix** [comment] 2024-07-25 13:37
Closing as not reproducible. Feel free to re-open if still valid and there are more details available.

**Comment by rolfsmeds** [comment] 2024-09-19 13:44
Closing as stale. Feel free to re-open if still valid.

**Closed by rolfsmeds** 2024-09-19 13:44 UTC
Labels: bug, waiting for author
