### ISSUE TITLE
GridPro has "Ghostdata" when having editable cells clicked

### ISSUE THREAD

**Issue by subITCSS** [vaadin/flow-components#6402] opened 2024-07-04 06:44 UTC
### Description

When clicking a cell via editOnClick the Component which is set to editable shows initially the previous data instead of the correct data which is displayed moments later.
So we have on the initial cell click a kind of ghost data. 

![buhu](https://github.com/vaadin/flow-components/assets/155952489/2a4dae1d-f6a4-4de0-978a-54ffda06e3c5)

### Expected outcome

Only the real Component and it´s data is shown at any time.

### Minimal reproducible example

grid.setEditOnClick(true)

Any type of component rendered in the cell.

### Steps to reproduce

1. Grid with Components in the cells
2. grid.SetEditOnClick(true)
3. click in cell

### Environment

Vaadin version(s): 24.4.4

**Comment by sissbruecker** [comment] 2024-07-05 09:45
Can you please share a full reproduction? Are you using custom editor components or only the built-in ones?

**Comment by sissbruecker** [comment] 2024-07-05 09:53
Seems like a duplicate of https://github.com/vaadin/web-components/issues/2550

Let's confirm this is about custom editors first.

**Comment by yuriy-fix** [comment] 2024-08-22 13:35
Closing as stale. Feel free to re-open if still valid.

**Closed by yuriy-fix** 2024-08-22 13:35 UTC
Labels: vaadin-grid-pro, waiting for author

**Comment by subITCSS** [comment] 2024-08-22 13:48
@yuriy-fix It is kind of the same - but the behavior of the fieldcontent when clicking in it seems different for me.
