### ISSUE TITLE
[spreadsheet] Double click after typing throws exception

### ISSUE THREAD

**Issue by roastedcpu** [vaadin/flow-components#3377] opened 2022-06-22 06:11 UTC
### Description

If you type something into a cell (just A1 for example) and then double click the column to resize it it'll throw an exception:

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 52
at com.vaadin.flow.component.spreadsheet.Spreadsheet.setColumnHidden(Spreadsheet.java:3445)
at com.vaadin.flow.component.spreadsheet.Spreadsheet.setColumnWidth(Spreadsheet.java:4198)
at com.vaadin.flow.component.spreadsheet.Spreadsheet.onColumnResized(Spreadsheet.java:4178)
at com.vaadin.flow.component.spreadsheet.SpreadsheetHandlerImpl.columnResized(SpreadsheetHandlerImpl.java:212)
at com.vaadin.flow.component.spreadsheet.SpreadsheetEventListener.onComponentEvent(SpreadsheetEventListener.java:138)
at com.vaadin.flow.component.spreadsheet.SpreadsheetEventListener.onComponentEvent(SpreadsheetEventListener.java:14)
```

### Expected outcome

Should not throw the reported exception

### Minimal reproducible example

*

### Steps to reproduce

See description

### Environment

Vaadin version(s): 23.1

**Comment by DiegoCardoso** [comment] 2022-06-22 06:17
This is a duplicate of https://github.com/vaadin/flow-components/issues/3329, which has been fixed but not yet released. You can verify it with a snapshot from `V23.2`.

**Closed by DiegoCardoso** 2022-06-22 06:17 UTC
