### ISSUE TITLE
AssertionError in Button upon setClassName > setText > setClassName

### ISSUE THREAD

**Issue by roelnoten** [vaadin/flow-components#5658] opened 2023-11-02 15:14 UTC
### Description

Calling setClassName for the same class with a setText in the middle on the flow Button leads to an AssertionError which breaks the entire Vaadin session.

```
2023-11-02 15:15:01,411 ERROR [io.undertow.request] (bgp-ui task-1) UT005023: Exception handling request to /ica/: java.lang.AssertionError
	at deployment.ica.war//com.vaadin.flow.internal.nodefeature.NodeList.generateChangesFromEmpty(NodeList.java:400)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at deployment.ica.war//com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:359)
	at deployment.ica.war//com.vaadin.flow.internal.StateNode.collectChanges(StateNode.java:625)
	at deployment.ica.war//com.vaadin.flow.internal.StateTree.lambda$collectChanges$0(StateTree.java:296)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at deployment.ica.war//com.vaadin.flow.internal.StateTree.collectChanges(StateTree.java:296)
	at deployment.ica.war//com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:413)
	at deployment.ica.war//com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:175)
	at deployment.ica.war//com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:212)
	at deployment.ica.war//com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:196)
	at deployment.ica.war//com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:175)
	at deployment.ica.war//com.vaadin.flow.component.UI.push(UI.java:721)
...
```

### Expected outcome

An AssertionError breaking the entire Vaadin Session should not occur on such basic api usage.

### Minimal reproducible example

```java
        Button button = new Button();
        button.setClassName("aClass", true);
        button.setText("blabla");
        button.setClassName("aClass", false);
        add(button);
```

### Steps to reproduce

See reproducible example

### Environment

Vaadin version(s): 23.3.2 (in a project with also 7.7.32 and mpr-v7)

### Browsers

Issue is not browser related

**Comment by tomivirkki** [comment] 2023-11-10 15:17
I can't reproduce the issue. Tried the given code snippet with `23.4-SNAPSHOT` and `24.3-SNAPSHOT`. I wonder if this has already been fixed.

Can you attach an example project with repro as a zip file?

**Comment by bwajtr** [comment] 2023-11-13 13:28
I also was not able to reproduce the issue... I tried with Vaadin 23.3.2, mpr-v7 (Vaadin 7.7.42) and Java 11.

**Comment by yuriy-fix** [comment] 2023-12-14 10:40
Closing as not reproducible. Feel free to re-open if still valid.

**Closed by yuriy-fix** 2023-12-14 10:40 UTC
Labels: bug, vaadin-button, Severity: Major, Impact: Low, waiting for author
