### ISSUE TITLE
Implement Grid.Column.setDescriptionGenerator()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2315] opened 2021-11-04 10:43 UTC
### Describe your motivation

Would help migration from Vaadin 8.

**Comment by TatuLund** [comment] 2021-11-05 07:38
Related to https://github.com/vaadin/flow-components/issues/2290

**Comment by TatuLund** [comment] 2021-11-05 07:39
Related to https://github.com/vaadin/web-components/issues/2528

**Comment by alvarezguille** [comment] 2021-11-09 11:07
Closed as duplicate of vaadin/web-components#2528

**Closed by alvarezguille** 2021-11-09 11:07 UTC
Labels: enhancement, vaadin-grid

**Comment by mvysny** [comment] 2021-11-10 06:54
Why was this closed as a duplicate of web-components? The web-components ticket is meant to implement stuff in pure JavaScript side, while this repo is meant to have a Java bindings for the JavaScript functionality.
