### ISSUE TITLE
TreeGrid: Empty item lines after 50 entries, using unfiltered AbstractBackEndHierarchicalDataProvider<TYPE, Void>

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#3713] opened 2022-09-13 18:09 UTC
### Description

I can see only 50 out of the 600 root items in my demo application. I have not yet found a way to make that number bigger.

### Expected outcome

Of course I would like to see a lazy-loading TreeGrid, but first and before all, all the root items need to be rendered when scrolling.

### Minimal reproducible example

```
package com.vaadin.qa.views.helloworld;


import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.hierarchy.AbstractBackEndHierarchicalDataProvider;
import com.vaadin.flow.data.provider.hierarchy.HierarchicalQuery;
import com.vaadin.flow.function.ValueProvider;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.*;
import java.util.stream.Stream;

@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class HelloWorldView extends VerticalLayout {

    public static class TreeDataProvider<TYPE> extends AbstractBackEndHierarchicalDataProvider<TYPE, Void> {

        private final ValueProvider<TYPE, Collection<TYPE>> childItemProvider;

        public TreeDataProvider(ValueProvider<TYPE, Collection<TYPE>> childItemProvider) {
            this.childItemProvider = childItemProvider;
        }

        @Override
        public int getChildCount(HierarchicalQuery<TYPE, Void> query) {
            return Math.toIntExact(fetchChildrenFromBackEnd(query).count());
        }

        @Override
        public boolean hasChildren(TYPE item) {
            return getChildCount(new HierarchicalQuery<>(null, item)) > 0;
        }

        @Override
        protected Stream<TYPE> fetchChildrenFromBackEnd(HierarchicalQuery<TYPE, Void> query) {
            return childItemProvider.apply(query.getParent()).stream();
        }
    }
    public HelloWorldView() {
        setSizeFull();

        TreeGrid<String> treeGrid = new TreeGrid<>();
        treeGrid.setWidthFull();
        treeGrid.setAllRowsVisible(true);

        final ArrayList<String> rootEnverNodes = new ArrayList<>();

        final ValueProvider<String, Collection<String>> childItemProvider = enverNode -> {
            if (enverNode == null){ // root items
                return rootEnverNodes;
            } else {
                return new ArrayList<>(); // assume no children
            }
        };

        TreeDataProvider<String> treeDataProvider = new TreeDataProvider<>(childItemProvider);

        for (int i=0; i < 600; i++){
            String enverNode = Integer.toString(i);
            rootEnverNodes.add(enverNode);
        }

        treeGrid.setDataProvider(treeDataProvider);
        ValueProvider<String, String> textProvider = (String::toString);
        treeGrid.addHierarchyColumn(textProvider);

        add(treeGrid);
    }

}

```

### Steps to reproduce

Use standard Vaadin starter, replace 'hello' view with the one above in the 'minimal' (okay... small) reproducible example.

### Environment

Vaadin version(s): 23.2
OS: MacOS Monterey Latest
Browsers Tested: Chrome, Firefox

### Browsers

Chrome, Firefox, Issue is not browser related

**Comment by enver-haase** [comment] 2022-09-14 07:18
The example also shows a very similar bug in Vaadin 14.3.1 -- only there after the 50 items shown, the same items are shown again. I am changing the example a a little in order to make it more easy to see which item is which:

**Comment by enver-haase** [comment] 2022-09-14 07:19
```
package com.infraleap;


import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.hierarchy.AbstractBackEndHierarchicalDataProvider;
import com.vaadin.flow.data.provider.hierarchy.HierarchicalQuery;
import com.vaadin.flow.function.ValueProvider;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Stream;

@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class View extends VerticalLayout {

    public static class TreeDataProvider<TYPE> extends AbstractBackEndHierarchicalDataProvider<TYPE, Void> {

        private static class CollectionMap<KEY, VALUE> {
            private final Map<KEY, Collection<VALUE>> data = new HashMap<>();
            private final Function<? super KEY, ? extends Collection<VALUE>> mappingFunction = (key -> new HashSet<>());

            public void add(KEY key, VALUE item) {
                data.computeIfAbsent(key, mappingFunction).add(item);
            }

            public Collection<VALUE> get(KEY key) {
                return data.computeIfAbsent(key, mappingFunction);
            }

            public KEY getKey(VALUE v) {
                for (KEY key : data.keySet()) {
                    Collection<VALUE> collection = data.get(key);
                    if (collection.contains(v)) {
                        return key;
                    }
                }
                throw new IllegalArgumentException("Value " + v + " was never added.");
            }

            public void remove(VALUE item) {
                for (Collection<VALUE> collection : data.values()) {
                    collection.remove(item);
                }
            }

            public boolean contains(VALUE item) {
                for (Collection<VALUE> collection : data.values()) {
                    if (collection.contains(item)) {
                        return true;
                    }
                }
                return false;
            }
        }

        private final CollectionMap<TYPE, TYPE> collectionMap = new CollectionMap<>();

        private final ValueProvider<TYPE, Collection<TYPE>> childItemProvider;

        public TreeDataProvider(ValueProvider<TYPE, Collection<TYPE>> childItemProvider) {
            this.childItemProvider = childItemProvider;
        }

        public void addItems(TYPE parent, Collection<TYPE> children) {
            children.forEach(child -> addItem(parent, child));
        }

        public TYPE getParent(TYPE child) {
            return collectionMap.getKey(child);
        }

        public TreeDataProvider<TYPE> addItem(TYPE parent, TYPE child) {
            collectionMap.add(parent, child);
            return this;
        }

        public boolean contains(TYPE item) {
            return collectionMap.contains(item);
        }

        public Collection<TYPE> getChildren(TYPE parent) {
            return collectionMap.get(parent);
        }

        public void removeItem(TYPE item) {
            collectionMap.remove(item);
        }

        public void clear() {
            collectionMap.data.clear();
        }

        @Override
        public int getChildCount(HierarchicalQuery<TYPE, Void> query) {
            return Math.toIntExact(fetchChildrenFromBackEnd(query).count());
        }

        @Override
        public boolean hasChildren(TYPE item) {
            return getChildCount(new HierarchicalQuery<>(null, item)) > 0;
        }

        @Override
        protected Stream<TYPE> fetchChildrenFromBackEnd(HierarchicalQuery<TYPE, Void> query) {
            return childItemProvider.apply(query.getParent()).stream();
        }
    }

    private static class EnverNode {
        private final String eins;
        private final String zwei;

        public EnverNode(int i){
            eins = "Item: "+i+" "+RandomStringUtils.randomAlphabetic(15);
            zwei = RandomStringUtils.randomAlphabetic(15);
        }

        public String getEins(){
            return eins;
        }

        public String getZwei(){
            return zwei;
        }
    }

    public View() {
        setSizeFull();

        TreeGrid<EnverNode> treeGrid = new TreeGrid<>();
        treeGrid.setWidthFull();
        //treeGrid.setAllRowsVisible(true);

        final ArrayList<EnverNode> rootEnverNodes = new ArrayList<>();

        final ValueProvider<EnverNode, Collection<EnverNode>> childItemProvider = enverNode -> {
            if (enverNode == null){ // root items
                return rootEnverNodes;
            } else {
                return new ArrayList<>(); // assume no children
            }
        };

        TreeDataProvider<EnverNode> treeDataProvider = new TreeDataProvider<>(childItemProvider);

        for (int i=0; i < 600; i++){
            EnverNode enverNode = new EnverNode(i);
            rootEnverNodes.add(enverNode);
        }
        treeDataProvider.addItems(null, rootEnverNodes);

        treeGrid.setDataProvider(treeDataProvider);
        ValueProvider<EnverNode, String> textProvider = (EnverNode::getEins);
        treeGrid.addHierarchyColumn(textProvider);

        add(treeGrid);
    }

}
```

**Comment by enver-haase** [comment] 2022-09-14 07:20
So, please consider backporting.

**Comment by tomivirkki** [comment] 2022-09-14 07:21
Is this a duplicate of https://github.com/vaadin/flow-components/issues/3708? At least the log shows the same exact message: "Attempted to fetch more items from server than allowed in one go: number of items requested '650', maximum items allowed '500'."

**Comment by enver-haase** [comment] 2022-09-14 07:35
Might be the same basic problem with bad paging when fetching, but here I cannot see the easy correlation between page size and number of items shown.
Note this here is the DataProvider version which is lazy loading, while #3708 is the version that uses TreeData.

TreeData is unfortunately (and unnecessarily, IMHO) greedy-loading (even the addItems() method that takes as a parameter some parent->children producing function travels the tree recursively immediately adding all items).

**Comment by enver-haase** [comment] 2022-09-14 07:37
I assume the basic underlying problem of both is that the client tries to fetch more items than what is allowed in one go, and then does not take any proper measures when not having got all the items that were requested (additional fetches).
But it's good to test both codes against a fixed version (and put them in tests for the future).

**Comment by enver-haase** [comment] 2022-09-14 12:13
@tomivirkki are you sure about the log message?  I do not see it here for this very bug. But I do see (development mode, bottom right becoming red and clicking it shows:

There seems to be an error in Vaadin Grid: Cannot read properties of undefined (reading 'filter') Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
(Firefox)

or it shows
There seems to be an error in Vaadin Grid: items is undefined Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
(Chrome)

**Comment by enver-haase** [comment] 2022-09-15 12:03
The requestor side obviously should loop until all the required items are there.
Related: https://github.com/vaadin/flow-components/issues/1629 -- it seems that not only is the fetch broken (non-looping) but also too greedy at times (fetching items that are not being rendered, unless someone would start scrolling).

**Comment by enver-haase** [comment] 2022-09-15 12:21
This bug reproduces in Vaadin 21.0.4.
This bug reproduces in Vaadin 21.0.3.
**Hence this is not the same bug as #3708.**

**Comment by enver-haase** [comment] 2022-09-15 12:36
Smaller version:
```
package com.vaadin.qa.views.helloworld;


import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.treegrid.TreeGrid;
import com.vaadin.flow.data.provider.hierarchy.AbstractBackEndHierarchicalDataProvider;
import com.vaadin.flow.data.provider.hierarchy.HierarchicalQuery;
import com.vaadin.flow.function.ValueProvider;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import org.apache.commons.lang3.RandomStringUtils;

import java.util.*;
import java.util.stream.Stream;

@PageTitle("Hello World")
@Route(value = "hello")
@RouteAlias(value = "")
public class HelloWorldView extends VerticalLayout {

    public static class TreeDataProvider<TYPE> extends AbstractBackEndHierarchicalDataProvider<TYPE, Void> {

        private final ValueProvider<TYPE, Collection<TYPE>> childItemProvider;

        public TreeDataProvider(ValueProvider<TYPE, Collection<TYPE>> childItemProvider) {
            this.childItemProvider = childItemProvider;
        }

        @Override
        public int getChildCount(HierarchicalQuery<TYPE, Void> query) {
            return Math.toIntExact(fetchChildrenFromBackEnd(query).count());
        }

        @Override
        public boolean hasChildren(TYPE item) {
            return getChildCount(new HierarchicalQuery<>(null, item)) > 0;
        }

        @Override
        protected Stream<TYPE> fetchChildrenFromBackEnd(HierarchicalQuery<TYPE, Void> query) {
            return childItemProvider.apply(query.getParent()).stream();
        }
    }

    private static class EnverNode {
        private final String one;
        private final String two;

        public EnverNode(int i){
            one = "Item: "+i+RandomStringUtils.randomAlphabetic(15);
            two = "Item: "+i+RandomStringUtils.randomAlphabetic(15);
        }

        public String getOne(){
            return one;
        }

        public String getTwo(){
            return two;
        }
    }

    public HelloWorldView() {
        setSizeFull();

        TreeGrid<EnverNode> treeGrid = new TreeGrid<>();
        treeGrid.setWidthFull();
        treeGrid.setAllRowsVisible(true);

        final ArrayList<EnverNode> rootEnverNodes = new ArrayList<>();

        final ValueProvider<EnverNode, Collection<EnverNode>> childItemProvider = enverNode -> {
            if (enverNode == null){ // root items
                return rootEnverNodes;
            } else {
                return new ArrayList<>(); // assume no children
            }
        };

        TreeDataProvider<EnverNode> treeDataProvider = new TreeDataProvider<>(childItemProvider);

        for (int i=0; i < 600; i++){
            EnverNode enverNode = new EnverNode(i);
            rootEnverNodes.add(enverNode);
        }

        treeGrid.setDataProvider(treeDataProvider);
        ValueProvider<EnverNode, String> textProvider = (EnverNode::getOne);
        treeGrid.addHierarchyColumn(textProvider);

        add(treeGrid);
    }

}

```

**Comment by tomivirkki** [comment] 2022-09-27 10:56
> are you sure about the log message? I do not see it here for this very bug

The log message is there since the code example includes `treeGrid.setAllRowsVisible(true);` (see https://github.com/vaadin/flow-components/issues/3708#issuecomment-1255954080).
If I remove the line, the warning goes away but the issue with only 50 items showing remains.

**Comment by tomivirkki** [comment] 2022-09-27 12:54
The problem is in the implementation of `TreeDataProvider` in your code snippet, specifically this method:

```java
@Override
protected Stream<TYPE> fetchChildrenFromBackEnd(HierarchicalQuery<TYPE, Void> query) {
   return childItemProvider.apply(query.getParent()).stream();
}
```

It currently returns the same list of items for every request on the root level. You should slice the requested sublist from the root items instead. Here's an example fix:

```java
@Override
protected Stream<TYPE> fetchChildrenFromBackEnd(HierarchicalQuery<TYPE, Void> query) {
    return childItemProvider.apply(query.getParent()).stream()
        .skip(query.getOffset()).limit(query.getLimit());
}
```

With this method fixed and `allRowsVisible` removed (as suggested in https://github.com/vaadin/flow-components/issues/3713#issuecomment-1259331920), the TreeGrid works as expected

**Comment by enver-haase** [comment] 2022-09-28 10:23
I can already say that the fix -even though the TreeDataProvider was lifted almost 1:1 from a customer project- does not work in said customer project.

**Comment by tomivirkki** [comment] 2022-09-28 10:34
> I can already say that the fix -even though the TreeDataProvider was lifted almost 1:1 from a customer project- does not work in said customer project.

Can you then please provide an example that produces the problem with DataProvider being used correctly?

**Comment by enver-haase** [comment] 2022-09-28 12:57
I agree that the above fix for the incorrect implementation of my DataProvider indeed makes the problem go away.

Two things may be left for fixing though:
- A mistake in using the framework should surely not trigger a warning like 'Cannot read properties of undefined (reading 'filter') Please submit an issue' or 'items is undefined Please submit an issue'.
- there should be a way to detect that there's a duplicate item in the data set either the identical item was added (or returned by the data provider) or it was otherwise 'a.equals(b)' for two items a and b. If such a check is costly at run-time then maybe have a documented debug option.

Certainly empty rows mask away the underlying problem.

**Comment by tomivirkki** [comment] 2022-09-28 13:18
This issue was prioritized with the assumption that there was a bug matching the description (`TreeGrid: Empty item lines after 50 entries, using unfiltered AbstractBackEndHierarchicalDataProvider<TYPE, Void>`) with the Grid. Since the issue isn't there, I'll close this one (instead of repurposing an already triaged bug report).

If you wish, you can create a new issue regarding improving the documentation / warning / error messages so that it will be triaged separately.

**Closed by tomivirkki** 2022-09-28 13:18 UTC
Labels: bug, vaadin-grid, Severity: Major, Impact: High, waiting for author
