### ISSUE TITLE
Reading an empty bean on radio button group/checkbox group results in required labels to be displayed

### ISSUE THREAD

**Issue by felix-office** [vaadin/flow-components#5399] opened 2023-08-29 21:53 UTC
### Description

Using `RadioButtonGroup` or `CheckboxGroup` with a binder and clearing the bound bean with `readBean(null)` or `writeBean(new Bean())` results in required labels to be displayed. 

This only happens for RadioButtonGroup and CheckboxGroup. If the bean is cleared twice in a row the label will disappear.

### Expected outcome

No required labels are shown as the fields are cleared intentionally.

### Minimal reproducible example

https://github.com/FelixGaebler/vaadin-bugs/tree/master/src/main/java/de/dataport/bugs/views/report3

### Steps to reproduce

Example:
1. Choose one or multiple workdays (checkbox group) and one travel class (radio button group)
2. Click either "Set bean" or "Read bean" 
3. See that "Required!" is displayed for the checkbox group and the radio button group
4. If you click one of the buttons again this will be cleared.

### Environment

Vaadin version(s): 24.1.5
OS: Linux

### Browsers

Issue is not browser related

**Comment by knoobie** [comment] 2023-08-30 05:26
Note: I've got a feeling that this might be a regression in v24 (pinging @vursen out of curiosity if he thinks this is related to the validation changes)

**Comment by vursen** [comment] 2023-08-30 10:02
> Note: I've got a feeling that this might be a regression in v24 (pinging @vursen out of curiosity if he thinks this is related to the validation changes)

You are right, I checked and the issue is caused by the client-side `validated` event. More specifically, the RadioGroup and CheckboxGroup web components trigger validation when there is a programmatic value change, which in turn generates a `validated` event. This kind of value change takes place when resetting a bean. The `validated` event triggers an extra round of server validation.

There is a similar issue reported for Select: #5319

**Comment by felix-office** [comment] 2023-09-20 08:00
This is still on the plan for the initial 24.2 release, correct?

**Comment by vursen** [comment] 2023-09-25 06:52
> This is still on the plan for the initial 24.2 release, correct?

We are planning to address this issue as part of a major validation refactor. Unfortunately, it's unlikely to be included in 24.2 because it's still in the stage of discussion. There is a [Github discussion](https://github.com/orgs/vaadin/discussions/4434) describing the new approach. Your feedback would be very valuable.

**Comment by felix-office** [comment] 2023-09-25 07:41
@vursen Interesting, when I put this into BFP they told me it will be fixed in 24.2 and I even repeated my claim and it was not contradicted.

**Comment by knoobie** [comment] 2023-09-25 11:59
Note the "workaround" isn't so hard to use in the meantime. 

'If the bean is cleared twice in a row the label will disappear.' was also mentioned in other issues or related problems and works.

**Comment by felix-office** [comment] 2023-09-25 12:12
@knoobie It's not about not using a workaround. It was about BFP. We had evaluated upgrading our licenses and BFP as well as the expert chat  sometimes didn't deliver what we expect for the pricing. In the internal ticket I stated:

> "I still expect this to be fixed in the initial version of Vaadin 24.2 based on the given explanation."
And it was answered with
> "Thanks for the confrmation."

Based on this I would expect it in 24.2 since I have not been contradicted. This seems like bad internal communication then and has nothing to do with this ticket. Just a bit of context of why I asked it.

**Comment by yuriy-fix** [comment] 2023-09-26 14:10
Dear @felix-office, regarding our bug ticket handling process, we intentionally avoid providing target versions. The reason for this is that it's challenging to estimate the time and effort required for fixing these issues. In some cases, we may discover the root cause and resolve it within a short timeframe, while in others, it could lead to significant refactoring across multiple components, taking much longer.
Considering that there are typically several issues in our high-priority pipeline, our internal estimates can't always be precise. We want to avoid providing our customers with imprecise target versions.
Currently, we're in the process of a major validation refactoring, as mentioned here: [link to the discussion](https://github.com/orgs/vaadin/discussions/4434). It seems there might have been a miscommunication, as there was an impression that a `24.2.0` release was promised. To prevent further frustration for you as our customer, we plan to integrate a [temporary fix](https://github.com/vaadin/web-components/pull/6537) in version `24.2.0` to address this specific use case. Please note that this fix may require adjustments or even a rewrite in the next versions to accommodate the changes resulting from the upcoming refactoring.

**Comment by felix-office** [comment] 2023-09-26 14:19
Hey @yuriy-fix, as I said, I'm fine with a major refactoring in future. This temporary fix isn't really needed for me if it only leads to more work for you guys. I only described why I had the wrong expectation. I can totally understand why you don't provide target versions but it's as simple as copy & pasting your text into any warrenty ticket which asks for a target version. Then there is no more miscommunication. Thanks for your dedication.

**Comment by vursen** [comment] 2023-11-06 08:09
The issue will be fixed as part of https://github.com/vaadin/flow-components/issues/5537.

**Comment by yuriy-fix** [comment] 2023-12-05 09:13
Resolved as a part of #5537

**Closed by yuriy-fix** 2023-12-05 09:13 UTC
Labels: bug, Severity: Major, Impact: Low, BFP, validation
