### ISSUE TITLE
Select - Dropdown indent table for combobox dropdown

### ISSUE THREAD

**Issue by subITCSS** [vaadin/flow-components#6324] opened 2024-05-27 12:56 UTC
### Describe your motivation

If the user sees a select and a combo box directly next to each other and wants to operate them, we have an unsightly ux at this point. While the combo box opens the overlay with the selection below/above the input field, the select opens the overlay directly above the input. Thus, we have an inconsistent opening behavior of both components (even if the combobox offers more possibilities than the select due to the search function) 

The background to this is that if there are 100 entries in the select, the user cannot directly see what he has selected so far and would first have to search for it again in the list.

### Describe the solution you'd like

One implementation would be if there were a method (or a new default) that allows the overlay to behave exactly like the ComboBox.

![image](https://github.com/vaadin/flow-components/assets/155952489/b069c260-f511-4233-a038-f5a86a3c841f)
![image](https://github.com/vaadin/flow-components/assets/155952489/3631a32c-213c-464a-b41a-fa6471471e02)
![image](https://github.com/vaadin/flow-components/assets/155952489/045b7e18-5fd5-4699-8960-f67f1b609ba0)

**Comment by web-padawan** [comment] 2024-05-27 13:07
Closing as duplicate of https://github.com/vaadin/web-components/issues/5101 - see that issue for a workaround.

**Closed by web-padawan** 2024-05-27 13:07 UTC
