### ISSUE TITLE
multi-select grid getSelectedItems  issue

### ISSUE THREAD

**Issue by ywuliu** [vaadin/flow-components#5406] opened 2023-08-30 16:52 UTC
### Description

Create a multi-selection grid
set dataProvider ( the backend data provider)
show items

select records 1,2,3

delete 2 in the backend.

dataProvider.refresh()

select records 4.

check grid.getSelectedItems()
you will find 1,2,3,4 all are in the selected set.

### Expected outcome

SelectedItems should only include records that are selected currently and in the new refreshed data set.

### Minimal reproducible example

Example:
-- java 
private int clicked=0;
grid g=new Grid...
grid.setSelectionMode(SelectionMode.MULTI);

Button btn= new Button("show Data");
btn.addClickListener(x->{
if(clicked==0)
{
 grid.setDataProvider(backendDataProvider);
clicked++;
}
else if(clicked==1)
{
grid.refresh();
clicked++
}
else{
Notification n= new Notification("G selected item size:"+g.getSelectedItems().size());
n.open();
}

});

VerticalLaout v= new VerticalLayout(g,v)

### Steps to reproduce

Modify the above example to a working example, 
Click the btn first, then select 1.
in the backend, remove record 1
Click btn again.

click btn again, it will show you the size is 1

### Environment

Vaadin version(s): 
OS: Mac

### Browsers

Issue is not browser related

**Comment by knoobie** [comment] 2023-08-31 05:26
Duplicate of https://github.com/vaadin/flow-components/issues/1059

**Comment by web-padawan** [comment] 2023-08-31 06:05
@knoobie Thanks for pointing out. Closing per above comment as duplicate.

**Closed by web-padawan** 2023-08-31 06:05 UTC
