### ISSUE TITLE
build without test-fails

### ISSUE THREAD

**Issue by stbischof** [vaadin/flow-components#781] opened 2021-04-05 16:26 UTC
The latest builds of the flow-components have different dates. 

`vaadin-button-flow` Apr 01 07:41:44 UTC 2021
http://tools.vaadin.com/nexus/content/groups/vaadin-prereleases/com/vaadin/vaadin-button-flow/20.0-SNAPSHOT/

`vaadin-checkbox-flow` Apr 05 15:31:17 UTC 2021
http://tools.vaadin.com/nexus/content/groups/vaadin-prereleases/com/vaadin/vaadin-checkbox-flow/20.0-SNAPSHOT/

seems that the build have some problems. especially `Vaadin Dialog Integration Tests` fails often

**Comment by vlukashov** [comment] 2021-04-06 11:18
Closing this as a duplicate of https://github.com/vaadin/flow-components/issues/777

**Closed by vlukashov** 2021-04-06 11:18 UTC
