### ISSUE TITLE
[Feature Request] allow to take Grid.Column object in Grid addColumn() method (V14)

### ISSUE THREAD

**Issue by lanmaster** [vaadin/flow-components#2381] opened 2021-11-25 11:47 UTC
## Description
In Grid i can get Grid.Column object and want to use it in hide/show columns context menu. So i can get Grid.Column, but cannot use it for addColumn. Instead i must use creator methods that invoke new addColumn(). It will be useful to have addColumn() method with already created Grid.Column as parameter.

**Comment by ZheSun88** [comment] 2021-11-26 07:09
Hi @lanmaster again, 
I moved your request to the correct repo so that our experts will handle it as early as possible. 
here actually has a [template for filling a feature request ticket](https://github.com/vaadin/flow-components/issues/new?assignees=&labels=i%3A+needs+triage&template=feature_request.md&title=), can you modify the content in this ticket (or create another one with some more details. )

Thanks for your help. 👍

**Comment by TatuLund** [comment] 2021-11-26 07:16
You can use `Grid.Column#setVisible(boolean)` to control visibility of the columns, you do not need to remove / re-add them. Also you will not gain any extra optimization with remove / re-add as Grid web component will detach / re-attach the column from the DOM when using setVisible method. See example

https://cookbook.vaadin.com/grid-column-toggle

**Comment by lanmaster** [comment] 2021-11-28 07:38
I just want to decrease traffic on refreshAll(), we have over 30 columns and about 700Kb traffic on each refresh. If half of columns will be disabled i need to exclude its data from server messages. Thanks for link, i will  remove my context menu from Grid's header and set component for selecting visible columns.

**Comment by lanmaster** [comment] 2021-11-29 08:18
One more thing related. Could you be please don't send unused data to the Grid? I mean with if there is some hidden columns - why do send more data than needed?

**Comment by yuriy-fix** [comment] 2021-11-30 11:20
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/1046

**Closed by yuriy-fix** 2021-11-30 11:20 UTC
Labels: feature request
