### ISSUE TITLE
ComboBox rendering with autofill issue with ComponentRenderer

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#6829] opened 2024-11-18 15:26 UTC
### Description

When trying to type in the value in the combobox as part of the autofill feature the ComboBox renders empty values. The reproducible example shows exactly how to replicate the issue in all browsers for the latest version of Vaadin. Below is a screenshot of what actually happens right now with the code from the example below.

![image](https://github.com/user-attachments/assets/3a460e0f-4e1c-4855-b925-6a4ab9d6cab7)

### Expected outcome

The autofill should render each value in the ComboBox rather than an empty line.

### Minimal reproducible example

```
ComboBox<DataObject> comboBox = new ComboBox<>();
comboBox.setRenderer(new ComponentRenderer<>(data -> {
		HorizontalLayout horizontalLayout = new HorizontalLayout();
		horizontalLayout.add(
				VaadinIcon.PLUS_CIRCLE.create(), 
				new Span(data.getDisplayValue()));
		horizontalLayout.setWidthFull();
		return horizontalLayout;
	}));
```

### Steps to reproduce

Run the above snippet and have say 10 items in the ComboBox then start to type the value (in the screenshot I was typing "re" which resulted in filtering out many of the values. As soon as you start to type the renderer fails. 

### Environment

Vaadin version(s): 24.5.5
OS: Windows 11

It basically applies to the latest version of Vaadin on every browser (FF, Chrome, etc.) and OS (Windows, Linux, etc.)

### Browsers

Issue is not browser related

**Comment by sissbruecker** [comment] 2024-11-19 07:57
Closing as duplicate of https://github.com/vaadin/flow-components/issues/6810

**Closed by sissbruecker** 2024-11-19 07:57 UTC
