### ISSUE TITLE
How to extract response and header response at a single call in Restassured

### ISSUE THREAD

**Issue by Vijay2871** [vaadin/flow-components#3618] opened 2022-08-26 02:31 UTC
### Description

there is a end- to end process in which first api response header is depending on 2nd and 2nd response header sepends on 3rd. I need to extract response as well as this when i call all the auth will change so in single call i need to extract everthing? how its possible

### Expected outcome

Extracting response headers and response elements(deserializing) simultaneously

### Minimal reproducible example

it fails when we deserialise and input the response

### Steps to reproduce

Call first API and extract response and headers for hitting 2nd api 

### Environment

Java

**Comment by knoobie** [comment] 2022-08-26 06:15
What is the relation to Vaadin in this construct?

**Comment by web-padawan** [comment] 2022-08-26 06:26
Based on the description, the issue is not related to Flow or components. Closing.

**Closed by web-padawan** 2022-08-26 06:26 UTC
