### ISSUE TITLE
ButtonElement.click() should fail on disabled button

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#3149] opened 2022-05-10 07:40 UTC
### Description

`ButtonElement.click()` should fail on disabled button but instead it does nothing. This promotes creation of flaky tests, or tests that fail later on for no apparent reason.

### Expected outcome

`ButtonElement.click()` should fail with an exception and an informative error message (e.g. button 'id' is disabled, can not be clicked).

### Minimal reproducible example

```java
$(ButtonElement).first().click()
```

### Steps to reproduce

Skeleton starter: have a disabled button in the main view

### Environment

Vaadin version(s): 14.7.5

**Comment by web-padawan** [comment] 2023-11-21 15:00
Duplicate of #5414 which was fixed by #5392. Closing.

**Closed by web-padawan** 2023-11-21 15:00 UTC
Labels: enhancement, Impact: Low
