### ISSUE TITLE
Date picker input not validated when typed in and invalid content is provided

### ISSUE THREAD

**Issue by epricer** [vaadin/flow-components#2176] opened 2020-10-01 17:46 UTC
Tested in chrome 85.0.4183.102, Vaadin version 14.3.8, Java based form.

When typing in a value into the text field of a previous empty date picker, providing an invalid value, and then forcing a blur to another input, the input value is not validated.

This gives the impression that the value is correct.

If the date picker has been assigned a value, and the user types an invalid value into the text field, then the validation triggers as expected.

**Comment by web-padawan** [comment] 2021-10-01 18:33
> Java based form.

Moved this issue to Flow components repo. Sorry about not answering earlier.

**Comment by TatuLund** [comment] 2022-01-20 12:21
There is a workaround to do forced validation call on blur.

```
            datePicker.addBlurListener(event -> {
                datePicker.getElement().executeJs("return this.validate();")
                        .then(value -> comp
                                .setInvalid(!value.toJson().equals("true")));
```

**Comment by TatuLund** [comment] 2022-01-20 12:57
Happens also in Vaadin 22.0.2

**Comment by TatuLund** [comment] 2022-01-20 12:57
Possibly duplicate of https://github.com/vaadin/flow-components/issues/1158

**Comment by SonReimer** [comment] 2022-01-20 13:34
Workaround , that works together with required:
```
      datePicker.addBlurListener(event -> {
          datePicker.getElement().executeJs(
        		  "if (!this.value && this.inputElement.value != '') {"
        		+ "  return this.validate();"
        		+ "} else {"
        		+ "  return true;"
        		+ "}"
        		  ).then(value -> {
	    	  if(!value.toJson().equals("true")) {
	        	  datePicker.setInvalid(true); 
	        	  datePicker.setErrorMessage("Invalid input");
	    	  }
          });  
      });    

```

**Comment by web-padawan** [comment] 2022-01-20 16:30
Note, the validation is triggeredwhen using `<vaadin-date-picker>` web component, so the [TypeScript example](https://vaadin.com/docs/latest/ds/components/date-picker) works.
The fact that DatePicker for Flow disables client side validation means we need to re-implement the same logic here.

**Comment by TatuLund** [comment] 2022-01-21 06:52
> The fact that DatePicker for Flow disables client side validation means 

This raises the question that should we add API to make it possible to turn it on if so needed. Implementing that is really straightforward.

**Comment by yuriy-fix** [comment] 2022-01-21 13:35
The issue is a duplicate of https://github.com/vaadin/flow-components/issues/1158. I will leave it open with `workaround` label.
The issue will be resolved once the logic will be finalised and enhancements mentioned in https://github.com/vaadin/flow-components/issues/1158 and https://github.com/vaadin/flow/issues/8242 are implemented.

**Comment by mvysny** [comment] 2022-04-07 11:17
To integrate the workaround with binder see the code below:
```java
@Route("")
public class MainView extends VerticalLayout {

    public static class MyDatePicker extends DatePicker implements HasValidator<LocalDate> {
        private boolean isClientSideValid = true;

        public SerializableRunnable validationChangedListener = () -> {
        };

        public MyDatePicker() {
            addBlurListener(event -> getElement()
                    .executeJs("return this.validate();")
                    .then(value -> {
                        isClientSideValid = "true".equals(value.toJson());
                        validationChangedListener.run();
                    }));
        }

        @Override
        public Validator<LocalDate> getDefaultValidator() {
            return (value, context) -> isClientSideValid ? ValidationResult.ok() : ValidationResult.error("Invalid date format");
        }
    }

    public MainView() {
        final MyDatePicker f = new MyDatePicker();
        final Binder<MyBean> binder = new Binder<>(MyBean.class);
        final Binder.Binding<MyBean, LocalDate> binding = binder.forField(f).bind("dateOfBirth");
        f.validationChangedListener = binding::validate;

        add(f, new TextField());
    }

    public static class MyBean {
        private LocalDate dateOfBirth;

        public LocalDate getDateOfBirth() {
            return dateOfBirth;
        }

        public void setDateOfBirth(LocalDate dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
        }
    }
}
```

In short, MyDatePicker validates itself on blur, then fires `validationChangedListener`. The listener calls `binding.validate()` which will re-run the Binder validation chain. Since `MyDatePicker` implements `HasValidator` its validator will also be considered, marking the field as invalid if necessary.

**Comment by SonReimer** [comment] 2022-04-08 07:13
Thanks for your example. It's very useful.
I changed it a bit to support required field messages

```
@Route("")
public class MainView extends VerticalLayout {

    public static class MyDatePicker extends DatePicker implements HasValidator<LocalDate> {
		private boolean hasInvalidInput = false;

        public SerializableRunnable validationChangedListener = () -> {
        };

		public MyDatePicker() {
			addBlurListener(event -> {
				runValidation();
			});	  
			addOpenedChangeListener(event -> {
				if (!event.isOpened()) {
					runValidation();
				}
			});
		}

		public void runValidation( ) {
			getElement()
			.executeJs("return this.validate() != true && this.inputElement.value !== \"\"")
			.then(value -> {
				hasInvalidInput = "true".equals(value.toJson());
				validationChangedListener.run();
			});
		}
		
		@Override
		public Validator<LocalDate> getDefaultValidator() {
			return (value, context) -> {
				if (!hasInvalidInput) { 
					return ValidationResult.ok();
				} else {
					return ValidationResult.error("Invalid date format");
				}
			};
		}      
    }

    public MainView() {
        final MyDatePicker f = new MyDatePicker();
        f.setLabel("Date of birth");
        final Binder<MyBean> binder = new Binder<>(MyBean.class);
        final Binder.Binding<MyBean, LocalDate> binding = binder.forField(f).asRequired("Mandatory").bind("dateOfBirth");
        f.validationChangedListener = binding::validate;

        add(f);
    }

    public static class MyBean {
        private LocalDate dateOfBirth;

        public LocalDate getDateOfBirth() {
            return dateOfBirth;
        }

        public void setDateOfBirth(LocalDate dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
        }
    }
}

```

**Comment by mvysny** [comment] 2022-04-08 07:15
Thank you, but unfortunately that doesn't work in Vaadin 14.8 since `this.inputElement` is undefined.

**Comment by SonReimer** [comment] 2022-04-08 07:17
Ahh, o.k., I'm working on a 23.x version.

**Comment by SonReimer** [comment] 2022-04-08 07:20
To apply the same workaround for DateTimePicker, the nested DateTimePickerDatePicker and DateTimePickerTimePicker should be made overridable. I'll open a issue for that.

**Comment by mvysny** [comment] 2022-06-16 06:50
Unfortunately the blur-based solution is not without faults. When you press the ArrowDown key in the date picker popup the picker is marked as invalid. Explanation: The blur listener gets called (since the popup now has the focus); for some reason `this.validate();` results in `false` (for no apparent reason), causing the component to be marked as invalid. To make matters more complex, sometimes it works, sometimes it doesn't. Probably there is some unfortunate timing.

**Comment by vursen** [comment] 2022-09-05 18:37
FYI: We have just introduced new validation behavior that is supposed to solve many different validation issues that people were complaining about, including this one. The new behavior is available under the feature flag in v23.2 for several components including DatePicker.

To enable the feature flag in your application, add the following to `vaadin-featureflags.properties`:

```
com.vaadin.experimental.enforceFieldValidation=true
```

Any feedback would be highly appreciated. For more details, please refer to https://github.com/vaadin/platform/issues/3066.

**Comment by simasch** [comment] 2022-12-16 08:16
1) @vursen The new validation behavior breaks our code as the Binding Validator is called in situations we cannot control

2) This issue is a massive blocker for us because the user can enter wrong data and then safe the form and there is no feedback that it didn't work

**Comment by vursen** [comment] 2023-01-30 09:07
> The new validation behavior breaks our code as the Binding Validator is called in situations we cannot control

@simasch Could you please provide more details? Is it the same as https://github.com/vaadin/flow-components/issues/1158#issuecomment-1354423699?

**Comment by simasch** [comment] 2023-01-30 10:01
@vursen I had situations where the validator was called more than once. And because we are executing heavy validation, this is an issue.

**Comment by vursen** [comment] 2023-06-14 06:57
The issue has been resolved by the [new validation mechanism](https://github.com/vaadin/platform/issues/3066) which is enabled by default in Vaadin 24. For any further bugs, please create separate issues.

**Closed by vursen** 2023-06-14 06:57 UTC
Labels: bug, vaadin-date-picker, Severity: Minor, Impact: High, BFP, workaround, validation
