### ISSUE TITLE
Vaadin 14: Unable to set value to Password Field using password manager at mobile Chrome and Firefox  

### ISSUE THREAD

**Issue by kyberorg** [vaadin/flow-components#2344] opened 2021-11-16 09:49 UTC
### Description

It seems like Password Managers (like Bitwarden and iCloud Keychain) are setting value to PasswordField incorrectly and therefore it cannot be retrieved using `PasswordField#getValue()` or `LoginEvent#getPassword()` methods.

Both `PasswordField` and `LoginForm` are affected.

Scope: mobile Firefox and mobile Chrome at iPhone 7 with iOS 15. 

### Expected outcome

What did you expect to happen?

Password value set correctly and can be retrieved using  `PasswordField#getValue()` or `LoginEvent#getPassword()` methods.

### Actual outcome

Password value set at least visually, but field's value cannot be retrieved.

### Live Demo (optional)

https://pass-app.kyberorg.io/  - Password Field example
https://pass-app.kyberorg.io/login - Login Form example
https://pass-app.kyberorg.io/sd -  Password Field example (without ShadyDom hack).

### Minimal reproducible example

https://github.com/kyberorg-lab/password-app 

[Password Field Example Code](https://github.com/kyberorg-lab/password-app/blob/main/src/main/java/com/example/application/views/helloworld/FieldsView.java)

[Login Form Example Code](https://github.com/kyberorg-lab/password-app/blob/main/src/main/java/com/example/application/views/about/SignUpView.java)

[Password Field Example (without ShadyDom hack) Code](https://github.com/kyberorg-lab/password-app/blob/main/src/main/java/com/example/application/views/shadowdom/ShadowDomView.java)

### Steps to reproduce

Clear steps describing how to reproduce the issue.

1. Save login/password pair to iCloud Keychain or Bitwarden for `https://pass-app.kyberorg.io` site
2. Open Firefox/Chrome at iPhone
3. Go to https://pass-app.kyberorg.io/
4. Fill in values using password manager
5. Click Show Password button
6. Notification with Username/Password should appear. 

Expected Notification Value: `Hello your-username-here, your entered Password is 'yout-password-from-password-manager-here'`

Actual Value: `Hello your-username-here, your entered Password is ''`

### Environment

- Vaadin version: 14.7.5 (Flow: 2.7.4)
- iOS 15.

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [x] iOS Firefox
- [x] iOS Chrome
- [ ] Android Chrome

**Comment by web-padawan** [comment] 2021-11-16 10:41
Duplicate of https://github.com/vaadin/web-components/issues/2758

We recommend using `vaadin-login-overlay` for better experience because it helps to avoid Shadow DOM.
Starting from Vaadin 22, all the field components are updated to use light DOM for `<input>` elements.

When using Polymer / Lit templates with Flow, check out this https://github.com/vaadin/web-components/issues/2758#issuecomment-937584628

**Closed by web-padawan** 2021-11-16 10:41 UTC

**Comment by kyberorg** [comment] 2021-11-16 10:49
@web-padawan What about solution for Java API ?

**Comment by web-padawan** [comment] 2021-11-16 11:03
@kyberorg We recommend using `LoginOverlay` as described in the [documentation](https://vaadin.com/docs/latest/ds/components/login/#modal-overlay).

**Comment by kyberorg** [comment] 2021-11-16 12:29
@web-padawan  it looks like `LoginOverlay` has the same bug.

code:

```java
@PageTitle("Login Overlay")
@Route(value = "login-overlay", layout = MainLayout.class)
public class LoginOverlayView extends Div {

    private final Span info = new Span();

    public LoginOverlayView() {
        LoginOverlay overlay = new LoginOverlay();
        overlay.addLoginListener(e -> overlay.close());

        LoginI18n i18n = LoginI18n.createDefault();
        i18n.setAdditionalInformation("To close the login form submit non-empty username and password");
        overlay.setI18n(i18n);

        overlay.addLoginListener(e -> {
            info.setText("Hello " + e.getUsername() + ", your entered Password is '" + e.getPassword() + "'");
        });

        overlay.setOpened(true);

        add(overlay, info);
    }
}
```

example: https://pass-app.kyberorg.io/login-overlay
