### ISSUE TITLE
ComboBox with page size < default fails on fetching next pages

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#3715] opened 2022-09-14 09:02 UTC
### Description

Having a combobox with 1000 string items and page size set to values 10,20,25 (< default 50) only fetches the first 10 pages and fails on fetching subsequent pages.

I think this issue is related to #2736/#2744

### Expected outcome

I would expect the comboBox to fetch all pages when scrolling.

### Minimal reproducible example

    	ComboBox<String> comboBox = new ComboBox<>();
        add(comboBox);
    	List<String> items = new ArrayList<>();
        for (int i = 0; i < 1000; i++) {
        	items.add("item #" + i);  
        }
    	comboBox.setItems(items);
    	comboBox.setPageSize(25);

### Steps to reproduce

1. Vary the page size for the example above with values 10,20,25 and 49
2. When the comboBox shows up, scroll slowly down
3. for 10,20 and 25 the combBox shows only the first 10 pages (100,200,250 items) and a progress indicator shows up
    Sometimes I get the following error:
    TypeError: pageCallbacks[page] is not a function (http://localhost:8080/VAADIN/@fs/C:/projects/others/vaadinflow/my-app23/node_modules/.vite/deps/@vaadin_flow-frontend_comboBoxConnector__js.js?v=cbe367e4:47:30)
There seems to be an error in Vaadin Combo Box: callback is not a function Please submit an issue to https://github.com/vaadin/flow-components/issues/new/choose
4. For an unset page size or page size 49 it seems to work

### Environment

Vaadin version(s): 23.2.0
OS: Windows

### Browsers

Firefox

**Comment by vursen** [comment] 2022-09-21 06:54
Confirmed the bug. Looks like the server stops responding to `setRequestedRange` requests at some point.

https://user-images.githubusercontent.com/5039436/191422021-0ddbe4ab-7bbc-49ef-94d4-8b8864d7afe7.mov

**Comment by vursen** [comment] 2022-09-22 08:12
When reproducing the bug, I see a lot of errors in the console:

```
2022-09-22T11:05:15.589+03:00  WARN 75345 --- [nio-8080-exec-2] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '165', maximum items allowed '150'.
2022-09-22T11:05:15.618+03:00  WARN 75345 --- [nio-8080-exec-5] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '180', maximum items allowed '150'.
2022-09-22T11:05:15.670+03:00  WARN 75345 --- [nio-8080-exec-7] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '195', maximum items allowed '150'.
2022-09-22T11:05:15.737+03:00  WARN 75345 --- [nio-8080-exec-9] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '210', maximum items allowed '150'.
2022-09-22T11:05:15.819+03:00  WARN 75345 --- [io-8080-exec-10] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '225', maximum items allowed '150'.
2022-09-22T11:05:15.969+03:00  WARN 75345 --- [nio-8080-exec-8] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '240', maximum items allowed '150'.
2022-09-22T11:05:39.370+03:00  WARN 75345 --- [nio-8080-exec-6] c.v.flow.data.provider.DataCommunicator  : Attempted to fetch more items from server than allowed in one go: number of items requested '165', maximum items allowed '150'.
```

**Comment by vursen** [comment] 2022-09-22 09:00
It appears that [MAX_RANGE_COUNT](https://github.com/vaadin/flow-components/blob/2a5170a86516b4fd5725d465a9107b58be2d81e7/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L25) doesn't respect the [server-side limitation](https://github.com/vaadin/flow/blob/1cacea3e2e3e8ffd66dabe433c8a22d2528c1884/flow-data/src/main/java/com/vaadin/flow/data/provider/DataCommunicator.java#L331-L339) on max size of the range.

**Comment by vursen** [comment] 2022-09-28 13:25
Will be fixed in https://github.com/vaadin/flow/issues/14630.

**Comment by stefanuebe** [comment] 2022-12-20 10:53
Same happens in grid, when using "setAllRowsVisible" without setting a concrete page size.

**Comment by sissbruecker** [comment] 2023-01-19 12:00
Closing, as the mentioned Flow issue has been resolved.

**Closed by sissbruecker** 2023-01-19 12:00 UTC
Labels: bug, awaits another ticket, vaadin-combo-box, Severity: Major, Impact: High
