### ISSUE TITLE
Dialog is not detached if another modal is opened during "close"

### ISSUE THREAD

**Issue by probert94** [vaadin/flow-components#4743] opened 2023-02-27 06:03 UTC
### Description

I have a `Dialog` which is auto added to the `UI` on open.
A registered `OpenedChangedListener` opens a new modal dialog when the other dialog gets closed.
Now I noticed, that the first dialog is closed, but not detached from the `UI`.

### Expected outcome

As the dialog has been added to the `UI` automatically, it should also be detached automatically.

### Minimal reproducible example

```
{
	TextField name = new TextField("Your name");
	Button sayHello = new Button("Say hello");
	sayHello.addClickListener(e -> {
		Dialog dlg = new Dialog();
		dlg.add(new VerticalLayout(
			new Span("Hello " + name.getValue()),
			new Button("Close", ev -> dlg.close())
		));
		dlg.addOpenedChangeListener(ev -> {
			if (!ev.isOpened()) {
				Dialog dlg2 = new Dialog();
				dlg2.add(new Span("Inner"));
				dlg2.open();
			}
		});
		dlg.addDetachListener(ev -> System.out.println("Detached"));
		dlg.getElement().addEventListener("opened-changed", event -> System.out.println(dlg.isOpened() ? "Open" : "Close"));
		dlg.open();
	});
	setMargin(true);
	setVerticalComponentAlignment(Alignment.END, name, sayHello);
	add(name, sayHello);
}
```

### Steps to reproduce

1. Download a new Vaadin starter project
2. Copy the above code into the constructor of the `MainView`.
3. Run the project
4. Click the "Say hello" button
5. Click the "Close" button in the dialog

The console should print:
- Open
- Detach
- Close

But it only prints "Open", detach and the `opened-hanged`-listener have not been called.

### Environment

Vaadin: 23.3.6
Flow: 23.3.4
Java: Eclipse Adoptium 17.0.6
OS: amd64 Windows 11 10.0

### Browsers

Issue is not browser related

### Notes
A dialog, that is auto added to the `UI` gets detached after a roundtrip to the client:
1. Server sends opened = false to the client
2. Client sends a opened-change event to the server
3. Server has a opened-changed listener, that detaches an auto added dialog

Unfortunately the new modal dialog makes the original dialog node inert and therefor the opened-changed listener is not called.

**Comment by paodb** [comment] 2023-03-01 20:31
Reproducible also in Vaadin 24.0.0.rc1. When first dialog is closed by clicking outside or by clicking escape key, the detach listener is call as exected, the issue happens only when calling close method.

**Comment by TatuLund** [comment] 2023-03-02 08:00
Is this duplicate of https://github.com/vaadin/flow-components/issues/4026 ?

**Comment by probert94** [comment] 2023-03-02 08:18
@TatuLund yes it looks like a duplicate

**Comment by ugur-vaadin** [comment] 2023-03-06 07:05
I started investigating the issue and will work on the fix.

**Comment by ugur-vaadin** [comment] 2023-03-09 07:24
I created a [PR](https://github.com/vaadin/flow-components/pull/4778) that will possibly fix this issue.

**Closed** 2023-03-28 11:20 UTC
Labels: bug, vaadin-dialog, Severity: Minor, Impact: Low, BFP

**Comment by ugur-vaadin** [comment] 2023-03-28 11:35
This issue was fixed and will be available with the next release.
