### ISSUE TITLE
TypeError when changing column visibility on an empty Grid and then filling data

### ISSUE THREAD

**Issue by nerdknight** [vaadin/flow-components#1077] opened 2020-11-14 15:08 UTC
### Description
Using Vaadin 14.4.2, when I change the columns visibility on an empty grid and then fill data to the grid a **TypeError: row is null** is shown and no data loaded.
If I first fill the grid and then change the columns visibility, the grid is filled normally.

### Expected outcome
Grid should fill with data

### Actual outcome
Error is shown no data shown on grid

### Steps to reproduce
1. Load the project attached: [VaadinGridTest.zip](https://github.com/vaadin/vaadin-grid/files/5540964/VaadinGridTest.zip)
2. Click the ToggleColumn button
3. Click FillGrid button

### Error shown on browser
![imagen](https://user-images.githubusercontent.com/5269947/99150266-01027e80-2672-11eb-80fd-290642faff8b.png)

**Comment by web-padawan** [comment] 2022-06-06 13:08
Here is a modified code example from the provided test project:

```java
package com.vaadin.flow.component.grid.it;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.grid.Grid.Column;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.bean.Person;
import com.vaadin.flow.router.Route;

@Route("vaadin-grid/toggle-column")
public class GridToggleColumnPage extends VerticalLayout {

    public GridToggleColumnPage() {
        Grid<Person> grid = new Grid<>();

        Column<Person> nameColumn = grid.addColumn(Person::getFirstName).setHeader("Name");
        Column<Person> ageColumn = grid.addColumn(Person::getAge).setHeader("Age");

        // Hide age column
        ageColumn.setVisible(false);

        Button btnToggle = new Button("Toggle columns", e -> {
            nameColumn.setVisible(!nameColumn.isVisible());
            ageColumn.setVisible(!ageColumn.isVisible());
        });

        Button btnFill = new Button("Fill grid", e -> {
            grid.setItems(new Person("foo", 20), new Person("bar", 30));
        });

        add(grid, btnToggle, btnFill);
    }
}
```

I was unable to reproduce this error with this example using the latest Vaadin version.
Closing as this is apparently a duplicate of https://github.com/vaadin/vaadin-grid/issues/2136 which was fixed by https://github.com/vaadin/vaadin-grid/pull/2144.

**Closed by web-padawan** 2022-06-06 13:08 UTC
Labels: bug, vaadin-grid, Severity: Major, Impact: Low
