### ISSUE TITLE
Devtools Button closes modal Dialog

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/flow-components#4901] opened 2023-03-30 12:10 UTC
### Description

When clicking the devtools button, the button overlay doesn't stop the mouse click and therefore closes e.g. modal Dialogs

https://user-images.githubusercontent.com/2902403/228831131-c0856e45-154b-41ba-a89e-e5d7083ccdf7.mp4

### Expected outcome

When clicking the DevTools button, the mouse click event is not propagated to the Components.

### Minimal reproducible example

```java
        var dialog = new Dialog();
        dialog.add(new Label("This is a dialog"));
        dialog.open();
```

### Steps to reproduce

- Run the snippet
- Click on the dev tools button
- See the dialog is closed, as the mouse click event is not stopped

### Environment

Vaadin version(s): 24
OS:

**Comment by Artur-** [comment] 2023-03-30 12:41
The problem is actually that the backdrop for the overlay gets the click first, as it is topmost

**Comment by yuriy-fix** [comment] 2023-04-05 12:13
@Artur- , should it be resolved in dev tools in order to bring the button as topmost?

**Comment by Artur-** [comment] 2023-04-05 12:16
I guess that is the only way

**Closed** 2023-04-06 11:14 UTC
Labels: bug, Severity: Minor, Impact: Low, DX
