### ISSUE TITLE
CheckBox in disabled state does not show title and tooltip

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#4455] opened 2022-12-28 10:24 UTC
### Description

I have a CheckBox and add a Tooltip or set the title attribute.

If the CheckBox is disabled neither is shown.

### Expected outcome

Title and Tooltip should work no matter of the state of the CheckBox

### Minimal reproducible example

```java
CheckBox checkBox = new CheckBox();
checkBox.setDisabled(true);

checkBox.setTooltipText("Test");
// or
checkBox.getElement().setAttribute("title", "Test");
```

### Steps to reproduce

See example

### Environment

Vaadin version(s): 23.3.2

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment] 2022-12-28 10:51
Duplicate of #4393

**Comment by web-padawan** [comment] 2022-12-28 10:51
Please see my comment here for an explanation: https://github.com/vaadin/flow-components/issues/4393#issuecomment-1356802983

**Closed by web-padawan** 2022-12-28 10:51 UTC

**Comment by simasch** [comment] 2022-12-28 12:05
@web-padawan That explains why the tooltip does not work. But not why the title is not shown.

This works for example for a TextField even if it's disabled:
```java
checkBox.getElement().setAttribute("title", "Test");
```

**Comment by simasch** [comment] 2022-12-28 12:17
@web-padawan Based on the linked issue I understand why the tooltip does not work. But not why the title is not shown.

This works for other disabled components like a TextField but not for a CheckBox
    checkBox.getElement().setAttribute("title", "Test");

**Comment by web-padawan** [comment] 2022-12-28 12:28
@simasch Thanks, and sorry for closing the issue hastily. Created a new one about `title`: #4456, will take a look.
