### ISSUE TITLE
SideNav should support route parameters

### ISSUE THREAD

**Issue by gpsfl** [vaadin/flow-components#5201] opened 2023-06-29 08:50 UTC
### Describe your motivation

In our application we have many different versions of our navigation menu, based on the user's configuration and permissions. Many of them link to the same Route's but with different RouteParameters.

### Describe the solution you'd like

Allow to add RouteParameters in the SideNavItem constructor and show their active state accordingly

### Describe alternatives you've considered

Allow to add custom navigation with click listeners and an API to set the active state of a SideNavItem manually

**Comment by web-padawan** [comment] 2023-06-29 09:56
Thanks for the issue. Closing as duplicate of https://github.com/vaadin/web-components/issues/5826 that covers RouteParameters support.

**Closed by web-padawan** 2023-06-29 09:56 UTC
