### ISSUE TITLE
DateTimePicker shows duplicate inputs when used in a Lit template

### ISSUE THREAD

**Issue by sissbruecker** [vaadin/flow-components#2407] opened 2021-12-06 10:08 UTC
### Description

Since v22, the DateTimePicker shows duplicate inputs (two date pickers, and two time pickers) when used in a Lit template, for example one created with Designer.

The issue comes from the recent refactoring of the web component, which now uses slotted inputs internally. Due to how templates work, the web component initializes its inputs before the Flow component adds its own slotted inputs, resulting in duplicates. A solution could be for the Flow component to clear children from the date picker and time picker slots before adding its own inputs.

### Expected outcome

DateTimePicker should show one date picker and one time picker.

### Actual outcome

DateTimePicker shows two date pickers and two time pickers.

### Live Demo (optional)

![uheRB](https://user-images.githubusercontent.com/357820/144826669-6a812f88-3f08-45df-beeb-6688403bf70a.jpg)

### Minimal reproducible example

Template:
```ts
import { LitElement, html, css, customElement } from 'lit-element';
import '@vaadin/date-time-picker';

@customElement('date-time-picker-lit-template')
export class DateTimePickerLitTemplate extends LitElement {
    render() {
        return html`
        <vaadin-date-time-picker id="date-time-picker" label="Date and Time"></vaadin-date-time-picker>
    `;
    }
}
```

Usage:
```java
public class DateTimePickerLitTemplatePage extends Div {

    public DateTimePickerLitTemplatePage() {
        DateTimePickerLitTemplate dateTimePickerLitTemplate = new DateTimePickerLitTemplate();
        add(dateTimePickerLitTemplate);
    }

    @Tag("date-time-picker-lit-template")
    @JsModule("./src/date-time-picker-lit-template.ts")
    public static class DateTimePickerLitTemplate extends LitTemplate {
        @Id("date-time-picker")
        private DateTimePicker picker;
    }
}
```

### Steps to reproduce

- run the above example
- open page in browser

### Environment

- v22 and above

### Browsers Affected

n/a

**Comment by web-padawan** [comment] 2021-12-06 10:51
Duplicate of https://github.com/vaadin/web-components/issues/3149

**Closed by web-padawan** 2021-12-06 10:51 UTC
Labels: bug, vaadin-date-time-picker
