### ISSUE TITLE
(TypeError) : this._overlayElement is undefined changing a custom Select's items

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#2299] opened 2021-11-01 12:33 UTC
### Description

I switch the items out for another set, and see a JavaScript error
"(TypeError) : this._overlayElement is undefined"

### Expected outcome

no error

### Actual outcome

error like above

### Live Demo (optional)

see screen shot

### Minimal reproducible example

See
git@github.com:enver-haase/switchitemsbug.git

**Comment by enver-haase** [comment] 2021-11-01 12:34
![Screenshot 2021-11-01 at 13 33 56](https://user-images.githubusercontent.com/7870436/139672105-935b9b61-1d80-48de-bd4c-08a13e0633ca.png)

**Comment by enver-haase** [comment] 2021-11-01 12:35
Happens only when switching the items before rendering the first time. After opening the select, then no error will occur.

**Comment by TatuLund** [comment] 2021-11-01 13:07
I think this is duplicate of https://github.com/vaadin/flow-components/issues/1086

**Comment by enver-haase** [comment] 2021-12-05 19:39
@TatuLund Why do you think that?
This is a Select, not a Combobox and I do not see any 'There seems to be an error in the Vaadin Combo Box' error on the console or anywhere, either.

**Closed** 2022-02-08 07:49 UTC
Labels: bug, Severity: Minor, Impact: Low
