### ISSUE TITLE
ComboBox should implement HasTheme

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#2090] opened 2021-09-03 11:16 UTC
Vaadin 14.6.8. ComboBox doesn't implement the HasTheme interface. It should since it has theme variants, according to https://vaadin.com/components/vaadin-combo-box/java-examples/theme-variants

**Comment by web-padawan** [comment] 2021-09-03 11:36
Duplicate of #1074, sorry about the fact that it's open for so long.

**Closed by web-padawan** 2021-09-03 11:36 UTC

**Comment by web-padawan** [comment] 2021-09-03 11:38
UPD: sorry the issue was wrong, here is the correct one https://github.com/vaadin/flow-components/issues/454
