### ISSUE TITLE
SideNavItem should have API for setting target

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow-components#5091] opened 2023-05-26 11:15 UTC
### Describe your motivation

Currently, if I add an external link to SideNav as a SideNavItem, it opens in the same tab. There is  no API to tell it to open in a new tab instead (`<a ... target="_blank">..</a>`).

### Describe the solution you'd like

A way to provide target type or indicate that it should be opened in a new tab through SideNavItem API. 

### Describe alternatives you've considered

Current workaround seems to be:
```
navItem.getElement().executeJs("requestAnimationFrame(() => this.shadowRoot.querySelector('a').target = '_blank')")
```

**Comment by rolfsmeds** [comment] 2023-12-18 10:30
In https://github.com/vaadin/flow-components/issues/5779 (a duplicate of this issue), @FDelporte proposed a `setOpenInNewTab(boolean)` API.

However, as `target` can also be used to specify a specific named window (or _browsing context_ to be precise) as the target, I could imagine that also being useful (albeit significantly more _niche_ than a new window/tab).

With that in mind, should the API instead be `setTarget(String)`? The drawback of this would of course be that the developer needs to know that the special magical value `"_blank"` is used to specify a new window/tab, which I'm not sure most Java developers are aware of.

I suppose we could have _both_ in the Flow API, so that setOpenInNewTab(true) would simply be a convenience API for `setTarget("_blank")` (and, if we want a getter, `getOpenInNewTab()` would return true if the target was set to `"_blank"` through either API.

The web component would probably suffice with a `target` attribute.

**Comment by anezthes** [comment] 2023-12-18 11:02
```
item.setTarget(Target.SELF);
item.setTarget(Target.BLANK);
item.setTarget(Target.PARENT);
item.setTarget(Target.TOP);
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target

Also consider setting `rel="noreferrer"` and `rel="noopener"` automatically on Target.BLANK.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#security_and_privacy

**Comment by rolfsmeds** [comment] 2023-12-18 11:29
I figured there was little point in an enum, as `_parent` and `_top` are, to my understanding, only relevant in framesets, which aren't really used anymore.

As for rel="noopener", https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noopener says

> Note: Setting target="_blank" on <a> elements now implicitly provides the same rel behavior as setting rel="noopener"

So I think we can skip that.

As for `rel="noreferer"`, that _could_ be useful, but OTOH, I would assume that the most common use for links in an app's navigation list is to link either to views within the same app, or to other trusted resources, so I'm not sure if the security concerns are very relevant there either?

**Comment by knoobie** [comment] 2023-12-18 14:32
> security concerns are very relevant there either 

Adding it, would also benefit the GDPR, we are forced to add it to all external links to ensure (nevertheless our trust to the domain; especially when user can configure / provide those links)

**Comment by rolfsmeds** [comment] 2023-12-18 14:43
Sounds like that should probably be opt-in then, since you'd want to add it to external links specifically, but not e.g. when opening a part of the same application in a new tab?

**Comment by rolfsmeds** [comment] 2023-12-19 17:54
Ok, so as `rel="noreferer"` is a separate concern, one related to, but not necessarily exclusive to `target="_blank"`, I think it would make sense to have a separate issue about that. @knoobie would you mind creating that issue, and describe the GDPR-related motivations for it there?

**Comment by knoobie** [comment] 2023-12-19 21:38
World is moving to fast..  couldn't find the information I was hoping for.. but at least some (now oldish) security Related discussion, but looks like it finally improved in 2023: https://owasp.org/www-community/attacks/Reverse_Tabnabbing

**Comment by rolfsmeds** [comment] 2023-12-20 20:23
Acceptance Criteria ticket created: https://github.com/vaadin/platform/issues/4850

**Closed** 2024-01-22 13:55 UTC
Labels: enhancement, vaadin-side-nav
