### ISSUE TITLE
TextArea: incorrect background-color when set to "readonly" and "invalid"

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/flow-components#2010] opened 2021-08-17 13:58 UTC
### Description

When setting a TextArea to "invalid" and "readonly" the background-color seems to be partially in front of the text. Also when scrolling, a second, lighter background-color appears.

### Expected outcome

What did you expect to happen?

A readonly TextArea is displayed, with a red background. Text and Prefix/Suffix Component are fully opaque and not tinted red.

### Actual outcome

The background color is split between a darker and lighter red. Part of the text appears behind a partially transparent red layer (instead of Infront).

### Live Demo (optional)

![image](https://user-images.githubusercontent.com/2902403/129738370-eb613798-d3e9-4328-aeb0-699c35c2bedd.png)

### Minimal reproducible example

```java
@Route(value = "TestView", layout = MainLayout.class)
public class TestView extends VerticalLayout {
    
    public TestView() {
        setSizeFull();

        TextArea textArea = new TextArea();

        textArea.setWidthFull();
        textArea.setMaxHeight("20em");

        StringBuilder value = new StringBuilder();
        for (int i = 0; i < 100; i++) {
            value.append(i).append("\n");
        }

        textArea.setValue(value.toString());

        textArea.setReadOnly(true);
        textArea.setInvalid(true);

        add(textArea);
    }
}
```

### Steps to reproduce

Create a TextArea
Set it to invalid, readonly and a minimum width
Set a multiline value
When scrolling said TextArea, the issue will be obvious.

### Environment

- Vaadin v20.0.6
- Windows 11

### Browsers Affected
All

**Comment by web-padawan** [comment] 2021-08-17 15:01
Duplicate of https://github.com/vaadin/web-components/issues/1196

**Closed by web-padawan** 2021-08-17 15:01 UTC

**Comment by mrgreywater** [comment] 2021-08-17 15:22
Thanks for the reference, it's related but not the same. This issue is about TextArea (not TextField). Also this issue is about two different red colors being displayed when scrolling.

**Comment by web-padawan** [comment] 2021-08-17 16:50
Thanks, I have added a mention of `vaadin-text-area` in that issue https://github.com/vaadin/web-components/issues/1196#issuecomment-900461588
Both components use more or less the same styles and the root cause is the same.
