### ISSUE TITLE
DataChangeEvent is not fired when GridListDataView#setFilter is called

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow-components#5303] opened 2023-07-31 09:14 UTC
### Description

DataChangeEvent is not fired when GridListDataView#setFilter is called. Note, the event is fired when filter is set via DataProvider instead. This should be analogous.

### Expected outcome

Event is fired.

### Minimal reproducible example

```java
    @Test
    public void dataView_setFilter_methodsUseFilteredData() {
        AtomicInteger refreshed = new AtomicInteger(0);
        String[] items = new String[] { "item1", "item2", "item3", "item4" };
        Grid<String> grid = new Grid<>();
        GridListDataView<String> dataView = grid.setItems(items);
        grid.getDataProvider().addDataProviderListener(e -> {
            refreshed.incrementAndGet();
        });

        dataView.setFilter(s -> s.endsWith("4"));
        Assert.assertEquals("Filter change did not fire DataChangeEvent", 1,
                refreshed.get());

        Assert.assertEquals("Filter was not applied to data size", 1,
                dataView.getItemCount());

        Assert.assertTrue("Expected item is missing from filtered data",
                dataView.contains(items[3]));
        Assert.assertFalse(
                "Item that should be filtered out is available in the data",
                dataView.contains(items[1]));

        Assert.assertEquals("Wrong item on row for filtered data.", items[3],
                dataView.getItem(0));
    }
```

### Steps to reproduce

Run the unit test

### Environment

Vaadin version(s): Vaadin 24.1.4
OS:

**Comment by sissbruecker** [comment] 2023-08-07 12:02
Closing with the same reasoning provided here: https://github.com/vaadin/flow-components/pull/5304#issuecomment-1667726101

**Comment by sissbruecker** [comment] 2023-08-07 12:45
I mean, I would say yes, conceptually that doesn't make sense. But looking at the implementation that might not be possible and may also be undesirable as developers might rely on that event in that case. I'm also not sure if the inconsistency is a big problem that needs fixing, the data provider and data view APIs work differently, and the data provider implementation has a lot of baggage that can't be changed anymore. 

But you're probably better off discussing this with the Flow team, maybe they have a different interpretation of data, data view and the data change event than I do. I'd suggest to create a ticket there to discuss the inconsistency and what the intended behavior is. If there is an outcome that requires changes to the components, then we're up for taking PRs for that.

**Closed** 2024-11-27 09:25 UTC
