### ISSUE TITLE
Login Form component triggers validation on attach

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#5266] opened 2023-07-18 14:53 UTC
### Description

When starting an application from start.vaadin.com that uses the Login Form component instead of extending LoginOverlay, validation message triggers on username field before interacting with the login fields.

### Expected outcome

I would expect username field to be focus but no validation triggered.

### Minimal reproducible example

Download a starter project from start.vaadin.com and change the default access to "Users who have logged in". 
Replace the LoginView to extend VerticalLayout (or any layout) instead of VaadinOverlay and add the LoginForm component:

```java
public class LoginView extends VerticalLayout implements BeforeEnterObserver {

    private final AuthenticatedUser authenticatedUser;
    private final LoginForm loginForm = new LoginForm();

    public LoginView(AuthenticatedUser authenticatedUser) {
        this.authenticatedUser = authenticatedUser;

        loginForm.setAction("login");
        this.setSizeFull();
        this.setAlignItems(Alignment.CENTER);
        this.setJustifyContentMode(JustifyContentMode.CENTER);
        add(loginForm);
    }

    @Override
    public void beforeEnter(BeforeEnterEvent beforeEnterEvent) {
        if (beforeEnterEvent.getLocation().getQueryParameters().getParameters().containsKey("error")) {
            loginForm.setError(true);
        }
    }
```

### Steps to reproduce

1 - Run the application with the LoginView updated as mentioned above.
2 - After login is displayed on browser, username fields is focused and validation error appears on fields without getting the chance to interact with the form yet.

![login-issue](https://github.com/vaadin/flow-components/assets/30666649/226f59b9-09d2-4b1a-9c1a-850163eb1f91)

### Environment

Vaadin version(s): 24.2.0.alpha4
OS: Windows

### Browsers

Chrome, Firefox, Edge

**Comment by sissbruecker** [comment] 2023-07-21 06:24
This is also reproducable with the plain web-component when using auto-focus, and removing and then adding the element to the DOM again:
```html
  <vaadin-login-form></vaadin-login-form>
  <script type="module">
    const element = document.querySelector('vaadin-login-form');
    element.remove();
    document.body.append(element);
  </script>
```

Which is what Vaadin router does in a Flow app. So it seems that:
- the input field is first focused
- then loses focus when form is removed from DOM
- input field validates
- form is added again
- input field gets focused again, still has validation error

**Comment by sissbruecker** [comment] 2023-08-11 08:14
We have not been able to come up with a solution to this so far. For now, we can only provide workarounds:
- Disable auto-focus on the login form: `loginForm.getElement().setAttribute("no-autofocus", "");`
- Manually implement auto-focus, by disabling the auto-focus, and then focusing the username input after a timeout:
```java
loginForm.getElement().setAttribute("no-autofocus", "");
loginForm.getElement().executeJs(
        "setTimeout(() => { this.$.vaadinLoginUsername.focus(); }, 500);");
```

Notes from my investigation:
- Ideally we would be able to identify if a focus out was triggered by the user or programmatically due to the element being removed from the DOM, but there are no good solutions for this
  - In Chrome, `focusout` is fired before the element is actually removed from the DOM, so checking for `isConnected` in the listener is not an option
  - We could check if a keyboard or pointing device was used to trigger the focus out event. However this would likely not work with all assistive technologies which can move focus without a keyboard or mouse.
- We could remove the required validation for the username and password fields in the login form, which means the fields would not validate on blur anymore, but only after clicking the submit button. In the context of the login form it's obvious that both fields are required, so that would be reasonable. At best, this could only be done in a new minor if we deem the change not too intrusive. This would also involve removing, or at least deprecating, some I18N APIs for the required error messages.
- Alternatively implement a custom required validation in the submit listener that would still show the required error messages if one of the fields has not been filled. Ideally the fields would change to a valid state after the user has entered something, like other Vaadin components do when they are invalid.
- We could check whether it is necessary that Vaadin Router moves the elements within the DOM. From basic testing it seems that router moves the elements within the same parent container, which might not be necessary. I don't have a lot of insights into router, so there might be more complex scenarios that would break with such a change.

**Comment by sissbruecker** [comment] 2023-08-11 10:24
After testing this once more, the issue is not reproducable anymore in `main` (24.2 alpha), due to a recent refactoring which introduced a delay for the auto focus. That change seems to be good enough to resolve the problem with router, so we'll apply it to 24.1 as well and then consider this issue as fixed.

**Comment by sissbruecker** [comment] 2023-08-11 10:25
Closing as resolved as part of https://github.com/vaadin/web-components/pull/6338

**Closed by sissbruecker** 2023-08-11 10:25 UTC
Labels: bug, vaadin-login, Severity: Minor, Impact: High, BFP
