### ISSUE TITLE
Deprecation Warning because of use of Label in FormLayout

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#5209] opened 2023-06-30 08:16 UTC
### Description

I see a lot of these messages:

> The Label 'Username' was not associated with a component. Labels should not be used for loose text on the page. Consider alternatives like Text, Paragraph, Span or Div. See the JavaDocs and Deprecation Warning for more Information.

The reason is that FormLayout still uses Label:

    public FormItem addFormItem(Component field, String label) {
        return addFormItem(field, new Label(label));
    }

### Expected outcome

FormLayout should not use deprecated classes.

### Minimal reproducible example

FormLayout loginForm = new FormLayout();
loginForm.setResponsiveSteps(new FormLayout.ResponsiveStep("0", 1));

    TextField username = new TextField();
    FormLayout.FormItem formItem = loginForm.addFormItem(this.username, "Username");

### Steps to reproduce

Add the snipped above an run the app

### Environment

Vaadin version(s): 24.1.1

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment] 2023-06-30 08:18
Duplicate of #5171

**Closed by web-padawan** 2023-06-30 08:18 UTC
