### ISSUE TITLE
SideNavItem: need support for HighlightCondition. Item is not rendered highlighted when route template is used

### ISSUE THREAD

**Issue by werwolfberlin** [vaadin/flow-components#6161] opened 2024-03-27 14:53 UTC
### Description

I am using the SideNav and SideNavItem with anested router layout. 
- the outer layout has the SideNav.
- the actual content has a route temolate like "item/:id?" 

navigating to "/item" will show a list of all items (nested routerlayout) and a message "Please select item" in the content. selecting an item will navigate i.e. to "/item/15" which then will show the same nested routerlayout with a highlight for the selected item (RouterLink), but the outer navigation will not highlight the selected SideNavItem anymore as it did when navigating to "/item"

### Expected outcome

The SideNavItem has a method "setHighlightCondition(HighlightCondition highlightCondition)" like the RouterLink

### Minimal reproducible example

```
 SideNav sideNav = new SideNav();
sideNav.addClassNames(LumoUtility.Border.RIGHT, LumoUtility.BorderColor.CONTRAST_10);
sideNav.addItem(
        new SideNavItem("Contracts", "/dashboard", VaadinIcon.DASHBOARD.create()),
        new SideNavItem("Permits", PermitsView.class, VaadinIcon.CART.create()),
        new SideNavItem("Admin", "/customers", VaadinIcon.USER_HEART.create()));
return sideNav;
```
        
        
```
@Route(value = "permits/:id?", layout = PermitsLayout.class)
public class PermitsView extends FlexLayout implements BeforeEnterObserver {

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        RouteParameters routeParameters = event.getRouteParameters();
        Optional<String> id = routeParameters.get("id");
        removeAll();
        if (id.isEmpty()) {
            add(new Span("Please select a Permit"));
        }
        else {
            try {
//show something related to that ID
            } catch (Exception ignore) {
            }
        }
    }
}
```       
        

### Steps to reproduce

1) create an application with AppLayout and use the SideNave snippet to create your navigation.
2) create the PermitsView class having the route template
3) start the app
4) use the menu to navigate to "Permits" (should navigate to http://localhost:8080/permits)
4a) observe that the side nav item is highlighted
5) alter the route in the browser and add a random ID to the url. i.e.: http://localhost:8080/permits/159
5a) observe that the side nav item is NOT highlighted - this cannot be configured with HighlightCondition like in RouterLink

### Environment

Vaadin version(s): 24.3.7
OS: Windows 11
Issue is os independent

### Browsers
All

**Comment by knoobie** [comment] 2024-03-27 15:18
Just 5min ago, I was wondering the same and it feels really cumbersome that such basic things are still missing.

My hacky workaround is a some kind of after navigation observer, which adds the current path of the opened "sub view" as route alias for the "correct" sidenav entry..

@rolfsmeds I was expecting "full" route template support tbh. Now this feels really weird to use.. Just looking at your https://starpass.demo.vaadin.com/ demo - the multi tier navigation on the side would also benefit from this; currently it is literally copy-pasting the current routes to the "outer" navigation tiers.. which feels really really weird.

**Comment by sissbruecker** [comment] 2024-03-27 22:14
Should be a dupe of https://github.com/vaadin/flow-components/issues/5227

**Comment by knoobie** [comment] 2024-03-27 22:16
You are right! Thanks, Sascha!

**Comment by yuriy-fix** [comment] 2024-04-04 13:02
Closing in favour of https://github.com/vaadin/flow-components/issues/5227.

**Closed by yuriy-fix** 2024-04-04 13:02 UTC
