### ISSUE TITLE
repeatedly calling chart.drawChart() seems to leak memory

### ISSUE THREAD

**Issue by kchad** [vaadin/flow-components#3362] opened 2022-06-06 10:49 UTC
### Description of the bug

While working around vaadin/flow#13851, I find repeatedly calling chart.drawChart() seems to leak memory. 
![chart_leak_suspect](https://user-images.githubusercontent.com/2698679/172146240-90e7185e-32df-45a0-a218-539536b17ddd.png)

### Expected behavior

should run forever without 'java.lang.OutOfMemoryError: Java heap space'

### Minimal reproducible example

`		addSecondListener( 
				new PropertyChangeListener() {
			@Override
			public void propertyChange(PropertyChangeEvent evt) {
				for (int i = 0; i < 10; i++) {
					chart.drawChart();
				}
			}
		});
`

### Versions

- Vaadin / Flow version: 14.8.11
- Java version: 8
- OS version: Windows 11
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by sissbruecker** [comment] 2022-10-19 10:53
I can not reproduce the memory leak in either the version specified in the OP (14.8.11) or the latest patch version (14.8.20).

Here's the reproduction I used:
<details>
<summary>Example</summary>

```java
package org.vaadin.example;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.charts.Chart;
import com.vaadin.flow.component.charts.model.ChartType;
import com.vaadin.flow.component.charts.model.Configuration;
import com.vaadin.flow.component.charts.model.ListSeries;
import com.vaadin.flow.component.charts.model.XAxis;
import com.vaadin.flow.component.charts.model.YAxis;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.router.Route;

@Route("chart")
public class ChartView extends Div {
    Chart chart;

    public ChartView() {
        setupChart();

        Button redraw = new Button("Redraw", e -> {
            for (int i = 0; i < 100; i++) {
                chart.drawChart();
            }
        });
        add(redraw);
    }

    private void setupChart() {
        chart = new Chart();
        add(chart);

        Configuration configuration = chart.getConfiguration();
        configuration.setTitle("Chart");
        chart.getConfiguration().getChart().setType(ChartType.AREA);
        configuration.addSeries(new ListSeries("Tokyo", 20, 12, 34, 23, 65, 8,
                4, 7, 76, 19, 20, 8));
        configuration.addSeries(new ListSeries("Miami", 34, 29, 23, 65, 8, 4, 7,
                7, 59, 8, 9, 19));

        XAxis x = new XAxis();
        x.setCategories("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug",
                "Sep", "Oct", "Nov", "Dec");
        configuration.addxAxis(x);

        YAxis y = new YAxis();
        y.setMin(0);
        y.setTitle("Rainfall (mm)");
        configuration.addyAxis(y);
    }
}
```

</details>

As a recent memory leak has been fixed in Vaadin Flow (https://github.com/vaadin/flow/issues/13851), you might want to test with the latest patch version if you have not done so already.

If the issue persists, please post a full reproduction that allows us to investigate the problem. As shown above, just calling `drawChart` several times is not enough to reproduce the leak, and the method does not seem to contain any logic that would cause it to retain any of the objects shown in the screenshot.

**Comment by sissbruecker** [comment] 2022-11-23 11:20
Closing due to inactivity and lack of a reproduction. Please open a new issue with a reproduction if this is still a problem.

**Closed by sissbruecker** 2022-11-23 11:20 UTC
Labels: vaadin-charts, Severity: Blocker, Impact: Low
