### ISSUE TITLE
Upload component

### ISSUE THREAD

**Issue by gidravlic** [vaadin/flow-components#3273] opened 2022-06-02 07:22 UTC
### Description of the bug

setDropLabelIcon method behavior does not match documentation. Method call setDropLabelIcon(null) don't clear default drop icon.

### Expected behavior

Method call setDropLabelIcon(null) should clear default drop icon.

### Minimal reproducible example

```java
@Route("")
public class MainView extends VerticalLayout {

    private static final long serialVersionUID = 1L;

    public MainView() {
        
        Upload upload = new Upload(new MultiFileMemoryBuffer());
        upload.setDropLabel(new Span("Files"));
        upload.setDropLabelIcon(null);
        add(upload);
}
```

### Versions

- Vaadin / Flow version: 23.0.10
- Java version: 11.0.2
- OS version: Windows 10
- Browser version (if applicable): Chrome 101

**Comment by jouni** [comment] 2022-06-02 13:14
I assume it’s the JavaDoc which is misleading (and has a spelling error):

<img width="740" alt="Screen Shot 2022-06-02 at 16 12 48" src="https://user-images.githubusercontent.com/66382/171637134-151facfa-9ab7-47c0-8852-b6fe3776e04f.png">

And I agree, it can easily be misinterpreted. It should probably say **"or `null` to revert back to the default icon defined by the component theme"**.

**Comment by web-padawan** [comment] 2022-06-02 13:26
Closing as duplicate of #1018

**Closed by web-padawan** 2022-06-02 13:26 UTC
