### ISSUE TITLE
IntegerField should not allow invalid input.

### ISSUE THREAD

**Issue by HerbertsVaadin** [vaadin/flow-components#1991] opened 2021-08-10 13:13 UTC
### Description

Migrating Vaadin V7 project to Vaadin Flow 14. Customer previously used a TextField as a number field, and they limited input by setting max length and using some validators. 
In v14 it makes sense to use IntegerField instead for this functionality, since the field should only support Integer input. 
However, IntegerField does not behave as expected. 

### Expected Results
It is expected that moving on from text field, instead of maxLength we would have to use min and max values to more precisely dictate allowed input. Specifying min / max would prevent user from inputting anything smaller or larger than respective values. Inputting non-integer values would be prevented by default.  

### Actual Results
Min / max does not prevent invalid input being written, which it should at least optionally. There's no `setPreventInvalidInput(..)` method to enable such behavior. 
Furthermore it allows negative sign to be placed wherever in the string (for example, 125-515-5122 (allows up to 2 negative signs)). 
Moreover the field is not limited to Integer value, so you can enter something larger than Interger.MAX_VALUE and smaller than Integer.MIN_VALUE. 
Binder considers integer field with such values valid, since the backend interprets it `null` as the value, and that's allowed. So client receives no feedback, and we can't process such invalid inputs on backend. 

### Minimal reproducible example
```
IntegerField integerField = new IntegerField("Integer Field");
integerField.setMax(10_000);
integerField.setMin(-1_000);
```
Then just enter values that are out of bounds for min / max.

### Environment
Vaadin platform 14.6.6
Vaadin platform 19.0.2

### Browsers Affected
Tested on Firefox and IE (Chromium).

This is somewhat related to  #1035

**Comment by fhdhsni** [comment] 2021-08-19 07:41
Currently we rely on the native `input[type=number]` for this component which comes with the limitations that you've mentioned. We're considering moving to a custom implementation in the future to provide a better default behavior.

For now you might consider listening to `blur` event and calling `setInvalid` if the value is `null`
```
integerField.addBlurListener(event -> {
    if (integerField.getValue() == null) {
        integerField.setInvalid(true);
    }
});
```
Or if you need more control you can implement your own custom client side validation
```
integerField.getElement().executeJs("""
   this.addEventListener('keypress', e => {
      // implement custom validation
      // call `e.preventDefault();` to prevent producing a character value
      // set `this.invalid = true` to indicate an error
   })
""");
```

**Comment by web-padawan** [comment] 2022-05-12 13:20
The original issue says `Tested on Firefox` and there's a [known limitation for it](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528) on Firefox where it allows user to type any character on it, differently as seen in Chrome which only numbers a few other characters (`.`,`,`,`e`) are allowed.

Closing as duplicate of https://github.com/vaadin/web-components/issues/1169 which suggests a (possibly breaking) change that would fix this.

**Closed by web-padawan** 2022-05-12 13:20 UTC
