### ISSUE TITLE
Rich Text Editor doesn't report html value change correctly

### ISSUE THREAD

**Issue by nbabb** [vaadin/flow-components#4767] opened 2023-03-03 15:59 UTC
### Description

With the following code

```
RichTextEditor rte = new RichTextEditor();
rte.setValueChangeMode(ValueChangeMode.EAGER);
rte.addValueChangeListener(ev -> System.out.println("|" + rte.asHtml().getValue() + "|"));
add(rte);
```

If I type the letter a, and then backspace this is what I see in the console.

```
|<p>a</p>|
|<p>a</p>|
```

If I repeat it I see

```
|<p>a</p>|
|null|
```

### Expected outcome

I would expect to see
```

|<p>a</p>|
|null|
```

### Minimal reproducible example

```
RichTextEditor rte = new RichTextEditor();
rte.setValueChangeMode(ValueChangeMode.EAGER);
rte.addValueChangeListener(ev -> System.out.println("|" + rte.asHtml().getValue() + "|"));
add(rte);
```

### Steps to reproduce

1. Add the snippet above
2. Type the letter a and observe the console
3. Backspace to clear the letter a and observe the console

### Environment

Vaadin version(s): 23.3.6
OS: Windows

**Comment by yuriy-fix** [comment] 2023-03-06 08:07
The issue is added to the backlog priority queue for further investigation.

**Comment by ugur-vaadin** [comment] 2023-03-13 17:38
I created a https://github.com/vaadin/flow-components/pull/4803 that will possibly fix this issue.

**Comment by ugur-vaadin** [comment] 2023-03-14 12:50
The fix was merged, and will be available once it is released.

**Closed by ugur-vaadin** 2023-03-14 12:50 UTC
Labels: bug, Severity: Major, Impact: Low, BFP
