### ISSUE TITLE
Error when setting column visible and refresh data in one go

### ISSUE THREAD

**Issue by clivemoj** [vaadin/flow-components#1067] opened 2020-12-01 12:19 UTC
### Description
On server side set hidden column visible and refresh data.
### Expected outcome
Grid displays new column with data.

### Actual outcome
Grid displays column plus error:
vaadin-grid.js?cd77:874 Uncaught TypeError: Cannot read property 'index' of null
    at HTMLElement.__getRowModel (vaadin-grid.js?cd77:874)
    at eval (vaadin-grid-column.js?582a:318)
    at Array.forEach (<anonymous>)
    at HTMLElement.__setColumnTemplateOrRenderer (vaadin-grid-column.js?582a:317)
    at HTMLElement._setFooterTemplateOrRenderer (vaadin-grid-column.js?582a:358)
    at Object.runMethodEffect [as fn] (property-effects.js?0662:819)
    at runEffectsForProperty (property-effects.js?0662:157)
    at runEffects (property-effects.js?0662:121)
    at HTMLElement._propertiesChanged (property-effects.js?0662:1692)
    at HTMLElement.s._propertiesChanged (client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:1027)
    at HTMLElement._flushProperties (properties-changed.js?2b39:354)
    at HTMLElement._flushProperties (property-effects.js?0662:1536)
    at HTMLElement._invalidateProperties (property-effects.js?0662:1506)
    at HTMLElement._setProperty (property-effects.js?0662:1491)
    at HTMLElement.Object.defineProperty.set (properties-changed.js?2b39:153)
    at HTMLElement.eval (vaadin-grid-column.js?582a:244)
    at FlattenedNodesObserver.flush (flattened-nodes-observer.js?064a:281)
    at FlattenedNodesObserver._processMutations (flattened-nodes-observer.js?064a:213)
    at MutationObserver.eval (flattened-nodes-observer.js?064a:161)

### Steps to reproduce
1. Create a page with a grid containing columns A, B and C. Column B should be set to visible=false.
2. Add a "Show B" button to the page. Serverside click listener should set B visible and repopulate the underlying data.
3. Open the page in a web browser.
4. Click Button.
-->

### Browsers Affected

- [ x] Chrome

**Comment by arenk** [comment] 2021-08-16 22:25
@denistarnam Did you find any solution/workaround so far? I'm having the same issue here.

**Comment by TatuLund** [comment] 2022-01-04 14:31
Is this duplicate of https://github.com/vaadin/flow-components/issues/2330 ?

**Comment by arenk** [comment] 2022-01-24 10:42
Seems so. At least here everything is working fine now (Vaadin 22.0.4)

**Comment by web-padawan** [comment] 2022-06-06 12:03
Closing per above comment as duplicate of #2330 which has been fixed - see https://github.com/vaadin/vaadin-grid/pull/2200.
For anyone using Vaadin 14, please upgrade to the latest release (14.8.11) to get the fix.

**Closed by web-padawan** 2022-06-06 12:03 UTC
Labels: vaadin-grid, Severity: Major, Impact: Low
