### ISSUE TITLE
TextField (and ComboBox) do not allow to translate ARIA label of 'Clear' button

### ISSUE THREAD

**Issue by felixfontein** [vaadin/flow-components#1747] opened 2021-06-02 14:40 UTC
The TextField web component has a `i18n` field for the Aria label of the Clear button: https://github.com/vaadin/web-components/blob/master/packages/vaadin-text-field/src/vaadin-text-field-mixin.js#L218 It is not possible to define it on the Java side.

The ComboBox is internally (on the web component side) using a `vaadin-text-field`, and doesn't seem to expose the i18n feature, so I'm afraid there's not much that can be done on the Java side.

**Comment by yuriy-fix** [comment] 2021-06-10 11:41
The desired outcome could be achieved with `comboBox.getElement().executeJs("$0.inputElement.i18n = {'clear': $1}", comboBox.getElement(), "Custom Value");`.

**Comment by vlukashov** [comment] 2021-06-15 10:07
Closing this as a duplicate of https://github.com/vaadin/web-components/issues/1115

**Comment by felixfontein** [comment] 2021-06-15 13:05
@vlukashov is this really a duplicate? For the other component, the ARIA label is hardcoded in the web component. For `TextField`, the ARIA label is configurable in the web component, but the corresponding flow component does not give access to that API.

**Comment by vlukashov** [comment] 2021-06-16 09:30
@felixfontein, you are right these issues are different. It was a mistake to claim that one is a duplicate of the other. I'm reopenning this issue now.

**Comment by web-padawan** [comment] 2022-01-27 12:56
In Vaadin 22 we updated text field and related components to hide clear button from screen readers. The main reason is that announcing clear / toggle buttons was confusing as they aren't keyboard focusable. So the `i18n` object was removed.

Closing as wontfix.

**Closed by web-padawan** 2022-01-27 12:56 UTC
Labels: enhancement, wontfix, vaadin-combo-box, Impact: High, a11y
