### ISSUE TITLE
Grid breaks, when adding too many header rows

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow-components#6860] opened 2024-11-24 17:22 UTC
### Description

When adding too many header rows, the client side breaks. It seems that the grid supports 8 header rows. Adding a 9th or more, leads to this error in the browser and the grid is not shown correctly. It does not matter, if header texts are set or not or if it is just one column or multiple.

```
Uncaught TypeError: Cannot read properties of null (reading 'pop')
    at GridColumnGroup._groupOrderChanged (vaadin-grid-column-group-mixin.js:142:50)
    at Object.runMethodEffect [as fn] (property-effects.js:1038:38)
    at runEffects (property-effects.js:140:16)
    at GridColumnGroup._propertiesChanged (property-effects.js:1922:7)
    at Hx.s._propertiesChanged (FlowClient.js:1072:27235)
    at GridColumnGroup._flushProperties (properties-changed.js:384:14)
    at GridColumnGroup._invalidateProperties (property-effects.js:1748:14)
    at Object.defineProperty.set (properties-changed.js:170:18)
    at vaadin-grid-helpers.js:57:12
    at Array.forEach (<anonymous>)
    at updateColumnOrders (vaadin-grid-helpers.js:51:11)
    at GridColumnGroup._groupOrderChanged (vaadin-grid-column-group-mixin.js:156:9)
    at Object.runMethodEffect [as fn] (property-effects.js:1038:38)
    at runEffects (property-effects.js:140:16)
    at GridColumnGroup._propertiesChanged (property-effects.js:1922:7)
    at Hx.s._propertiesChanged (FlowClient.js:1072:27235)
    at GridColumnGroup._flushProperties (properties-changed.js:384:14)
    at GridColumnGroup._invalidateProperties (property-effects.js:1748:14)
    at Object.defineProperty.set (properties-changed.js:170:18)
    at vaadin-grid-helpers.js:57:12
    at Array.forEach (<anonymous>)
...
```

### Expected outcome

Support for more header rows would be nice :)

### Minimal reproducible example

```java
@Route(value = "dynamic-grid-header")
public class DynamicGridHeaderView extends VerticalLayout {

    public DynamicGridHeaderView() {
        Grid<?> grid = new Grid<>();
        grid.addColumn(s -> "Hello");
        for (int i = 0; i < 9; i++) {
            grid.appendHeaderRow();
        }

        add(grid);
    }
}
```

### Steps to reproduce

1. Add the given sample to your Vaadin application
2. Start the application and open the page
3. Check the browser console

### Environment

Vaadin version(s): 24.4.17 and 24.5.5

### Browsers

Chrome

**Comment by web-padawan** [comment] 2024-11-25 08:10
This is a duplicate of #2565 (the error and the root cause is the same). See https://github.com/vaadin/flow-components/issues/2565#issuecomment-1022035080

**Closed by web-padawan** 2024-11-25 08:10 UTC
Labels: vaadin-grid
