### ISSUE TITLE
`Datepicker` component to be able to select just Months or Year

### ISSUE THREAD

**Issue by Alexenon** [vaadin/flow-components#6659] opened 2024-09-20 06:22 UTC
### Month Picker Mode:
A mode where the DatePicker component only allows the user to select a month and year (ignoring the specific day).

- The UI should present a month selection interface.
- The selected value could return the first day\last day of the selected month as a LocalDate, or simply a month-year format.

### Year Picker Mode: 
A mode where the DatePicker allows users to select just a year.
- The UI should present only year navigation.
- The selected value could return a LocalDate for the first day of the selected year or simply a year format.
- Customizable Format: Ability to format the DatePicker for different patterns such as MM/yyyy or yyyy based on the mode.

There is already [such question](https://vaadin.com/forum/t/datepicker-to-show-only-months/159486) on Vaadin Forums, but there is no good answer for this.

### Describe the solution you'd like

I know that there is a way to achieve this, by using native HTML component, but I'd like to have a vaadin component with the same functionality.
```
<input type="month" id="start" name="start" min="2018-03" value="2018-05" />
```

I don't know which exact Java API is the best. 
Examples:
- add additional methods to datePicker like `datePicker.displayMode(Timestamp.MONTH)`
- add additional methods to datePicker like `datePicker.hide(Timestamp.DAYS)`
- completely separate component like `MonthPicker`

### Additional context

Any workarounds will be great too 🗡️

**Comment by web-padawan** [comment] 2024-09-20 06:37
Duplicate of https://github.com/vaadin/web-components/issues/1865. Please see the discussion in that issue.

**Closed by web-padawan** 2024-09-20 06:37 UTC
