### ISSUE TITLE
RadioButtonGroup: `addComponentAsFirst()` changes order of items

### ISSUE THREAD

**Issue by F0rce** [vaadin/flow-components#4164] opened 2022-11-22 12:14 UTC
### Description

I added a `RadioButtonGroup<String>` with initially two values in following order: "Yes", "No" and a `Label` Component (Text: "2 items") with `addComponentAsFirst()`. With the press of a button, I clear the `ArrayList` and add three values in following order: "None", "Yes", "No", refresh the `RadioButtonGroupListDataView` and add a `Label` Component (Text; "3 items") with `addComponentAsFirst()` again, as it has been removed with the `refreshAll()` call. After I pressed the button the order of "None", "Yes", "No" (in which it was added) changed in the UI to "None", "No", "Yes".

### Expected outcome

Adding a Component with `addComponentAsFirst()` should **not** change the order of the items. 
The expected order would be "None", "Yes", "No".

### Minimal reproducible example

```java
    Label label = new Label("2 items");
    ArrayList<String> values = new ArrayList<>(Arrays.asList("Yes", "No"));

    RadioButtonGroup<String> radioGroup = new RadioButtonGroup<>();
    RadioButtonGroupListDataView<String> list = radioGroup.setItems(values);
    radioGroup.setValue("Yes");
    radioGroup.addComponentAsFirst(label);

    Button updateValues = new Button("Update Values and Labels");
    updateValues.addClickListener(
        event -> {
          values.clear();
          values.add("None");
          values.add("Yes");
          values.add("No");
          list.refreshAll();
          radioGroup.setValue("None");
          span.setText("3 items");
          radioGroup.addComponentAsFirst(span);
        });

    add(updateValues, radioGroup);
```

### Steps to reproduce

1. Add snippet to a view extending from `VerticalLayout`
2. Check the order ("Yes", "No")
3. Click the "Update Values and Label" Button
4. The Label changes it's text and a new Button ("None") should appear
5. Check the order ("None", "No", "Yes") --> incorrect!

### Environment

Vaadin version(s): 23.2.8
OS: Microsoft Windows 10 Pro (10.0.19044 Build 19044)

**Comment by A7Attia** [comment] 2022-11-22 12:16
@F0rce Thank you for sharing it, I really hope it gets resolved soon

**Comment by sirbris** [comment] 2022-11-22 12:19
@F0rce I could reproduce this issue also with DataProvider instead of ListView

**Comment by knoobie** [comment] 2022-11-23 07:08
Why are you even adding a Label as component? You can pass the caption/label string to the constructor or appropriate method of the component.

**Comment by F0rce** [comment] 2022-11-23 07:16
@knoobie the label in that case was just an example (as I wanted to simplyfy the example). In my "real" implementation I add something more complex to the front.

**Comment by knoobie** [comment] 2022-11-23 07:37
Well that explains it 😉 I would guess that the component was never intended to allow usage like that tho

**Comment by sirbris** [comment] 2022-11-23 09:58
We use it e.g. to display a label in front of the radio buttons... after refreshing the dataProvider, the label component is removed... can this be prevented?

**Comment by knoobie** [comment] 2022-11-23 10:03
A single label for all radio buttons (for the whole group?)? If yes, the normal way to archive the desired effect is to use FormLayout as wrapper for the form which would make sure that the label for the field is on the left side or above the field depending on the configuration.

**Comment by knoobie** [comment] 2022-11-23 10:39
The more you explain your needs, the more I have feeling that this whole construct is a dirty hack. I would really suggest to rethink this. You can also apply relative width to the whole label section on the form layout (which could be roughly calculated by the longest label's text) and is future proof in contrast to your re-building a custom form layout. 

CC: @rolfsmeds probably interesting for your ideas regarding grid layout or enhancing the current form layout

**Comment by sirbris** [comment] 2022-11-23 12:07
It is most definitely a workaround, but addComponentAsFirst() is an available (straight forward) method, so it doesn't seem hacky. The width for the whole form in our case is also relative, because of SplitPanels so it's really hard to mimic the old (Vaadin 8) way of displaying left hand side labels with correct widths in FormLayout. The handling of labels inside the FormLayout is also not optimal because the added component is not directly aware of the label itself, so e.g. when handling validation, the component does not know its label or am I missing something?

**Comment by rolfsmeds** [comment] 2022-11-23 12:31
RadioButtonGroups is indeed not intended to be used as a generic component container, and this usage is not really supported even though the API allows it. (The reason that API is there is that the component for some reason implements the `HasComponents` interface, which is most probably a mistake, and it should be removed. (There is a similar issue open for Tabs: https://github.com/vaadin/flow-components/issues/1636).

To have a label on the side, a better approach would be to have it _outside_ the RadioButtonGroup.

**Comment by yuriy-fix** [comment] 2022-11-29 11:08
Related to https://github.com/vaadin/flow-components/issues/4251

**Comment by yuriy-fix** [comment] 2022-11-29 11:10
Closed as per https://github.com/vaadin/flow-components/issues/4194

**Closed by yuriy-fix** 2022-11-29 11:10 UTC
Labels: vaadin-radio-button, Severity: Minor, Impact: Low
