### ISSUE TITLE
Add ComboBox.addOverlayVisibleListener()

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-components#6026] opened 2024-02-07 09:12 UTC
### Describe your motivation

The customer wants to show a 'locate me' button whenever a ComboBox showing a list of address has overlay shown. Not my design :tm: .

### Describe the solution you'd like

A `ComboBox.addOverlayVisibleListener()` function which would notify me whenever the overlay is shown or hidden.

### Describe alternatives you've considered

I tried to fiddle with focus/blur listeners but I'm always hitting some strange corner-case.

**Comment by TatuLund** [comment] 2024-02-08 10:34
This is a low hanging fruit as the component fires the low level event already, you can thus use Element API to observe it

```
        combobox.getElement().addEventListener("opened-changed", e -> {
            Notification.show(e.getEventData().toJson());
        }).addEventData("event.detail");
```

**Comment by TatuLund** [comment] 2024-02-08 10:36
But this is a duplicate of https://github.com/vaadin/flow-components/issues/5420

**Comment by mvysny** [comment] 2024-02-08 10:40
Excellent catch, thank you so much @TatuLund . Yup I agree  that this ticket is a duplicate. Let's close this ticket as duplicate then.

**Comment by DiegoCardoso** [comment] 2024-02-08 10:53
Closing as duplicate.

**Closed by DiegoCardoso** 2024-02-08 10:53 UTC
Labels: enhancement, workaround
