### ISSUE TITLE
A link with an empty path is not keyboard navigatable

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow-components#5667] opened 2023-11-07 10:48 UTC
### Description

When a view is the default view, the vaadin-side-item is not navigatable with a keyboard. You can click on it.
![image](https://github.com/vaadin/flow-components/assets/51313578/cff64371-7375-438e-a0b3-b4d89ff34570)

The first item is not keyboard navigable

### Expected outcome

I want to navigate on each link, and on the "Home" by keyboard.

If you change the value of the Route `@Route(value = "", layout = MainLayout.class)` to `@Route(value = "home", layout = MainLayout.class)` it's working.

### Minimal reproducible example

```
	private SideNav createMenu() {
		SideNav sideNav = new SideNav();
		sideNav.addItem(
			new SideNavItem(getTranslation("home"), WelcomeView.class, VaadinIcon.HOME.create()),
			new SideNavItem(getTranslation("findOwners"), OwnersFindView.class, VaadinIcon.SEARCH.create()),
			new SideNavItem(getTranslation("veterinarians"), VetsView.class, VaadinIcon.LIST.create()),
			new SideNavItem(getTranslation("error"), ErrorView.class, VaadinIcon.WARNING.create())
		);
		return sideNav;
	}
```

```
@RouteAlias(value = "index", layout = MainLayout.class)
@Route(value = "", layout = MainLayout.class)
public class WelcomeView extends Div {

    public WelcomeView() {
        add(new Span("Explanation"));
    }
}
```

### Steps to reproduce

Try to navigate with the keyboard, the `HomeView` link is skipped

### Environment

Vaadin version(s): 24.2.2
It's probably not specific to a browser since I can reproduce it in FF, Chrome and. Safari on Mac

### Browsers

Chrome, Firefox, Safari

**Comment by jcgueriaud1** [comment] 2023-11-07 10:54
https://github.com/vaadin/flow-components/assets/51313578/8de00284-3e67-44c1-a126-1df9ae775727

**Comment by web-padawan** [comment] 2023-11-07 10:54
Thanks for the issue. We actually consider this an intended behavior: https://github.com/vaadin/web-components/issues/6310.
The `tabindex="-1"` is explicitly set on links without `path`- see https://github.com/vaadin/web-components/pull/6322.

**Comment by jcgueriaud1** [comment] 2023-11-07 11:08
But there a path it's an empty path because that's the home. Or maybe that should be` path="/" `?

**Comment by jouni** [comment] 2023-11-07 11:10
Browsers don't consider `<a href="">` as a proper link. That’s why you often see `<a href="#">` used instead.

**Comment by web-padawan** [comment] 2023-11-07 11:13
In case if the home page matches the `/`, its pathname will look like this:

<img width="268" alt="Screenshot 2023-11-07 at 13 12 03" src="https://github.com/vaadin/flow-components/assets/10589913/8d2f3372-b8fb-4d7e-91b4-86507e40a961">

So the `path` attribute should also be set to `/` so that we can [match](https://github.com/vaadin/web-components/blob/0a5f72e3d2c43eb808aeba3290e108f3f0a3842a/packages/component-base/src/url-utils.js#L15) it properly.

**Comment by jcgueriaud1** [comment] 2023-11-07 11:23
You can't navigate to the home page with `<a href="#">`.
If I'm doing the same thing with a `RouterLink`. I have this:

`add(new RouterLink("Home", IndexView.class));` --> `<a highlight="" router-link="" href="">Home</a>`

![image](https://github.com/vaadin/flow-components/assets/51313578/fd843b35-fc49-4fb8-acbe-338f59fae867)

And I can use my keyboard to navigate to my home page.

To me an empty href  (the anchor is considered as a link) is different than not href (it's not a link anymore).

**Comment by jouni** [comment] 2023-11-07 14:36
> You can't navigate to the home page with <a href="#"> .

I wasn’t implying we would do that. Just saying that empty `href` attributes are sort of ignored by browsers and therefore the anchor element is not focusable.

**Comment by web-padawan** [comment] 2023-11-14 11:19
This was fixed by https://github.com/vaadin/web-components/pull/6767 (not auto-closed since I referenced wrong issue in the PR).

**Closed by web-padawan** 2023-11-14 11:19 UTC
Labels: bug, Severity: Major, Impact: Low, vaadin-side-nav
