### ISSUE TITLE
Add option for DateTimePicker to read midnight when TimePicker is blank

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/flow-components#4262] opened 2022-11-29 17:44 UTC
### Describe your motivation

I'm using a `DateTimePicker` in an GUI application that searches for items by date range.

We need to provide minute resolution in order to allow for precise searches.

However, in may cases, people searching only need date resolution. But in these cases, they have to enter a time anyway in order to make the widget valid. This is an extra tedious step. They are having to enter a value they don't care about.

### Describe the solution you'd like

I would like a new option on the `DateTimePicker` widget where you could say for example `setTimeOptional(true)` and this would change the widget's behavior so that it would interpret a blank value in the `TimePicker` portion as if it were actually `12:00 AM`, i.e., midnight, instead of returning a null value.

### Describe alternatives you've considered

None.

### Additional context

The requested change would be completely backward-compatible.

**Comment by TatuLund** [comment] 2022-11-30 07:36
I think this is duplicate of https://github.com/vaadin/flow-components/issues/1850

**Comment by TatuLund** [comment] 2022-11-30 07:37
There is also another ticket here https://github.com/vaadin/web-components/issues/668

That ticket provides also the workaroumd.

**Comment by web-padawan** [comment] 2022-11-30 08:23
Duplicate of #1850

**Closed by web-padawan** 2022-11-30 08:23 UTC
