### ISSUE TITLE
Initial minimum/maximum length validation not working on instantiation time

### ISSUE THREAD

**Issue by PAX523** [vaadin/flow-components#1417] opened 2020-08-14 06:22 UTC
If you instantiate a TextField its initial value is empty. If you specify a minimum length > 0 then the validation state should change to "invalid" because the currently empty value doesn't satisfy the constraint.

```
final TextField component = new TextField();
component.setMinLength(1);
component.setMaxLength(5);
component.setValueChangeMode(ValueChangeMode.EAGER);
component.setValue(component.getValue(());
System.out.println(component.isInvalid()); // false, but should be true
```

Resetting the current value doesn't do anything because there's a check which aborts setting if the new value equals the old one.

Validations should be re-triggered on invocations of `setMinLength()` or `setMaxLength()` (or similar methods?).

PS: I was talking with Tarek. He suggested to discuss this bug with you.

**Comment by yuriy-fix** [comment] 2021-08-10 10:31
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/1449.

**Closed by yuriy-fix** 2021-08-10 10:31 UTC
Labels: vaadin-text-field
