### ISSUE TITLE
Setting themeNames causes SubMenu to fail once

### ISSUE THREAD

**Issue by mijutu** [vaadin/flow-components#6577] opened 2024-08-26 09:54 UTC
### Description of the bug

Opening SubMenu fails once if the menu has been opened before and its theme names have been altered.

### Expected behavior

SubMenu should open normally every time.

### Minimal reproducible example

https://k2c42.dy.fi/tmp/submenu-autoclose-problem.tar.xz

Run with mvn and go to http://localhost:8080/

### Versions

- Vaadin / Flow version: 24.4.7, 24.4.10
- Java version: 17.0.12+7-Debian-2deb12u1
- Browser version: Firefox 115esr, Chromium 128

(Edited: More accurate description, even more minimal example)

**Comment by DiegoCardoso** [comment] 2024-08-28 07:19
Hi @mijutu,

Could you provide a snippet or perhaps a GH repro with the reproducible code? We would rather not download compressed files. 

Thank you in advance.

**Comment by mijutu** [comment] 2024-08-28 07:29
Don't you people have disposable virtual machines? Or disposable virtual machines in some cloud setup so scary tars wouldn't even come close to your infrastructure?

```
var m = new MenuBar();
var hl = new HorizontalLayout(m);
hl.setWidthFull();
add(hl);
add(new Paragraph(
		"""
				This demonstrates a problem that appeared on Vaadin Flow from 24.4.7 to at least 24.4.10.
				First, open and close the drop down menu. Then click removeThemeNames or addThemeNames. Then try to open the drop down menu again. It closes immediately.
				Downgrading to 24.4.6, will fix the problem.
				"""));

var mi = m.addItem("☰");
var sm = mi.getSubMenu();
sm.addItem(new Span("Qwer"));
sm.addItem(new Span("Asdf"));
sm.addItem(new Span("Zxcv"));

hl.add(new Button("removeThemeNames", event -> {
	mi.removeThemeNames("selected-menuitem");
}));
hl.add(new Button("addThemeNames", event -> {
	mi.addThemeNames("selected-menuitem");
}));
```

**Comment by web-padawan** [comment] 2024-08-28 10:22
The underlying problem is most likely the same as in https://github.com/vaadin/flow-components/issues/6580 which will be fixed by https://github.com/vaadin/web-components/pull/7702.

**Comment by DiegoCardoso** [comment] 2024-08-28 12:35
Confirmed that this issue is a regression caused by https://github.com/vaadin/web-components/pull/7524

**Closed** 2024-08-28 14:14 UTC
Labels: bug, vaadin-menu-bar, regression
