### ISSUE TITLE
ComboBox calls CustomValueSetListener twice

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow-components#2523] opened 2022-01-14 16:37 UTC
### Description

ComboBox calls CustomValueSetListener twice if a dialog is opened in the listener

### Expected outcome

CustomValueSetListener is called once

### Actual outcome

ComboBox calls CustomValueSetListener twice

### Minimal reproducible example

```
package com.mycompany.v22.test;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.html.Span;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route
public class MainView extends VerticalLayout {

    private int dialogCounter = 1;
    
    public MainView() {

        ComboBox<String> cb = new ComboBox<>();

        cb.setLabel("Type something and hit enter");
        cb.addCustomValueSetListener(cv -> {
            System.err.println("WTF, i'm called twice ? " + cv.getDetail());
            Dialog d2 = new Dialog();
            
            d2.add(new Span("Dialog " + dialogCounter));
            dialogCounter++;

            Button save = new Button("Close");
            save.addClickListener(e1 -> {
                d2.close();
            });
            
            d2.add(save);

            d2.open();

        });

        add(cb);

    }
}
```

### Steps to reproduce

Use the example code, type something to field and hit enter. You'll see two dialogs opened instead of one.

### Environment

Vaadin
22.0.2
Flow
9.0.2
Java
Eclipse Adoptium 17
OS
aarch64 Mac OS X 12.0.1
Browser
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36

### Browsers Affected

How would I know? I only have Safari and Chrome.

**Comment by web-padawan** [comment] 2022-02-21 11:10
Duplicate of #2285.

**Comment by web-padawan** [comment] 2022-02-21 12:31
Reopened as this appears to be a problem in the web component different from #2285.

**Comment by web-padawan** [comment] 2022-02-22 15:48
The fix caused a regression in `TimePicker` and will be reverted. Reopening this until we find a better fix.

**Closed** 2022-02-23 11:48 UTC
Labels: bug, vaadin-combo-box, Severity: Major, Impact: Low
