### ISSUE TITLE
DateTimePicker breaks Tab Index order

### ISSUE THREAD

**Issue by simasch** [vaadin/flow-components#3612] opened 2022-08-23 09:01 UTC
### Description

I have a form with some input fields and I use `setTabIndex` 

If one of the input fields is a `DateTimePicker `then the tab index order is broken.

### Expected outcome

The order of the tab index should work

### Minimal reproducible example

https://github.com/simasch/vaadin-tabindex

### Steps to reproduce

Tab from field to filed

### Environment

Vaadin version(s): 23.1.x

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment] 2022-08-30 11:12
Thanks for the issue. I'm checking it and there doesn't seem to be any `DateTimePicker` used in the view.
When adding it manually, by default it works and the <kbd>Tab</kbd> order is correct:

https://user-images.githubusercontent.com/10589913/187422018-40cc7471-8e64-430e-b66b-4405aca169a8.mp4

Could you please check if your example project needs to be updated? I couldn't find usage of `setTabIndex` there.

Anyways, please keep in mind that we no longer support positive `tabindex` values on input fields. 
This is mentioned in the [upgrade guide](https://vaadin.com/docs/latest/upgrading/essential-steps#miscellaneous-changes) and applies to `vaadin-date-time-picker` as well.

**Comment by simasch** [comment] 2022-08-30 11:28
About positive tab-index: 
There is my opinion on that: https://github.com/vaadin/web-components/issues/3275

**Comment by web-padawan** [comment] 2022-08-30 11:56
Ok, thanks for the update. Now I see that `tabindex="2"` set on the `vaadin-date-time-picker` actually works.
This happens because of the fact it is set on the host element, not on the `<input>` wrapped in light DOM.

However, as all the other elements use `tabindex` on the `<input>`, the Tab order becomes broken: in fact, it behaves as if `vaadin-date-time-picker` had `tabindex="1"` - it gets focused first, before all the other fields.

That said, the underlying problem is essentially a duplicate of #3275. So I'm closing this issue in favor of that one.

**Closed by web-padawan** 2022-08-30 11:56 UTC
Labels: waiting for author

**Comment by simasch** [comment] 2022-08-30 12:01
Thanks for the clarification. 
I've found a workaround by setting the tabindex on the children.
