### ISSUE TITLE
Not able to override the nested shadow dom elements using the part selector

### ISSUE THREAD

**Issue by Mehafooz** [vaadin/flow-components#6702] opened 2024-10-09 06:32 UTC
### Description of the bug

With old vaadin date picker there are nested shadow dom , so im able to override the first level of shadow dom , but not able to override the nested shadow dom
![image](https://github.com/user-attachments/assets/2ed58e58-3604-4207-b496-90fa4c286b13)

![image](https://github.com/user-attachments/assets/034dc98a-c498-4efa-bae0-d60a01d41b25)

![image](https://github.com/user-attachments/assets/3f01b725-b9ac-4797-b31a-b7e880b6dd7d)

### Expected behavior

how to override the nested shadow doms using if they are exposed by parts

### Minimal reproducible example

it is reproducable using v14

### Versions

- Vaadin / Flow version:14
- Java version:
- OS version:
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by Mehafooz** [comment] 2024-10-09 06:49
Hi @web-padawan , Im using this date picker in my angular app , using ng deep im able to override the css of the shadow dom but nested shadow dom im not able to override , so im i missing something

**Comment by Mehafooz** [comment] 2024-10-09 07:19
So when i use vaadin 22 ,it has a dependency of lumo styles version 24.x.x ,but i have another library that has dependency of lumo style 1.6.1 bcz that im getting this issue https://github.com/vaadin/web-components/issues/7956

**Comment by web-padawan** [comment] 2024-10-10 13:32
As I mentioned, using two different Vaadin web components / Lumo versions in the same application is not supported.
Please contact the author of the library you mentioned so that they upgrade dependencies to Vaadin 24 compatible.

Closing as this is not a bug on our side and the shadow DOM styling works fine after you upgrade to V24.

**Closed by web-padawan** 2024-10-10 13:32 UTC
Labels: question, V14 only
