### ISSUE TITLE
[ContextMenu] Context menu doesn't open inside of a Dialog

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/flow-components#4896] opened 2023-03-29 13:23 UTC
### Description

Since Vaadin 24 the context menu doesn't open inside a modal Dialog anymore.

### Expected outcome

Context menu opens as expected.

### Minimal reproducible example

```java
            var field = new TextField();
            var dialog = new Dialog();
            dialog.add(field);

            dialog.open();

            ContextMenu menu = new ContextMenu();
            menu.setTarget(field);
            menu.addItem("Action", event -> {
                Notification.show("Action performed.");
            });
```

### Steps to reproduce

Run the snippet, right click on the TextField an notice no context menu is opening.

### Environment

Vaadin version(s): 24.0.2
OS: Windows 11 x64

**Comment by mstahv** [comment] 2023-03-29 13:56
I most probably have that same root cause with an add-on that breaks now with v24 and modal dialogs. Something is "shuffling" the elements in the DOM. The rich text editor loses its state and you can see clear flickering:

https://user-images.githubusercontent.com/1478052/228561234-aa69e0e2-c455-4122-b6fa-56b1acf98068.mp4

**Comment by mstahv** [comment] 2023-03-29 13:57
Maybe (/most probably) related: https://github.com/vaadin/flow/issues/16067

**Comment by mrgreywater** [comment] 2023-03-29 14:38
Also inside the dialogs, calling @ClientCallable functions from javascript now aren't actually executed in java. (Might be related as well).

**Comment by mstahv** [comment] 2023-03-29 14:44
Weird, maybe another issue, because [in the add-on project](https://github.com/parttio/tinymce-for-flow/blob/master/src/main/java/org/vaadin/tinymce/TinyMce.java#L123-L127) I was just updating, it is doing its client-server comms using it and that works. Is the component, on which the @ClientCallable function is declared on, inside the modal element?  Or do they maybe become broken somehow when another "overlay" is shortly visible 🤔

**Comment by knoobie** [comment] 2023-03-29 15:46
That's intended / related / a feature of the dialog's modal state.

**Comment by mstahv** [comment] 2023-03-29 15:51
As @knoobie said. If you, instead of adding that MyUICommunicator automatically into the UI (top level component), add it inside the dialog, it will work. Server side security. Same if you try to "click" a button outside your modal dialog using JS, the server side will block it.

**Comment by mrgreywater** [comment] 2023-03-29 16:32
Okay, I understand that feature, even though I really don't like it. It still relates to this issue, as the context menu opens properly when the dialog modality is turned off. I also noticed UI.getCurrent().hasModalComponent() is false even when the dialog modality is true.

**Comment by knoobie** [comment] 2023-03-29 16:40
Calling "dialog.setModal(true)" and all "problems" are gone

**Comment by mrgreywater** [comment] 2023-03-29 16:50
Disabling Dialog Modality is a workaround, but the ContextMenu should work even with Dialog Modality turned on.

As for the javascript modality security feature, I guess I'll have to fake my own modal dialog that doesn't prevent javascript calls. I looked into attaching my ClientCallable Component to every Dialog, but it's just not an option for what I'm trying to do. I require some global functions that go from javascript -> java that are accessible at all times, and not be blocked as soon as a modal dialog opens.

**Comment by knoobie** [comment] 2023-03-29 17:14
Isn't `@AllowInert` exactly for this use case of an client event that should always be triggered?

**Comment by mrgreywater** [comment] 2023-03-29 17:17
`@AllowInert` works! It's internal, but it works great, thank you :)

**Comment by Bemat** [comment] 2023-03-31 09:49
Some problem with notification inside dialog. 

`public class MainLayout extends VerticalLayout {

    public MainLayout() {
        Button notificationButton = new Button();
        notificationButton.setText("TEST");
        notificationButton.addClickListener(event -> {
            Notification notification = Notification.show("TEST NOTIFICATION");
            notification.setDuration(5000);
            notification.setPosition(Notification.Position.MIDDLE);
        });

        Button windowButton = new Button();
        windowButton.setText("OPEN WINDOW");
        windowButton.addClickListener(event -> {
            Dialog window = new Dialog();
            Button buttonWindow = new Button();
            buttonWindow.setText("TEST");
            buttonWindow.addClickListener(e -> {
                Notification notification = Notification.show("TEST NOTIFICATION");
                notification.setDuration(5000);
                notification.setPosition(Notification.Position.MIDDLE);
            });

            Button closeButton = new Button();
            closeButton.setText("CLOSE");
            closeButton.addClickListener(e -> {
               window.close();
            });

            window.add(buttonWindow, closeButton);

            window.open();
        });

        add(notificationButton, windowButton);
    }
}`

Outside dialog notification dismiss in 5000ms but inside dialog notification closing immediately.
If dialog is open with setModal(false), notification dismiss in 5000ms as expected.

Any workaround to use modal(true) until they fix it?

**Comment by mrgreywater** [comment] 2023-03-31 09:54
@Bemat I had that same issue with 24.0.0, but I can't reproduce it with 24.0.2

**Comment by knoobie** [comment] 2023-03-31 10:01
Notification was already reported and fixed. https://github.com/vaadin/web-components/issues/5665

**Comment by mstahv** [comment] 2023-03-31 10:32
With a timeout hack that looks like a potential source for new regressions/timing issues 🤫 @tomivirkki , @mshabarov, did somebody investigate what is the root cause of this regression?

**Comment by mshabarov** [comment] 2023-04-04 06:13
@mstahv thanks for investigation and pinging me. Not yet investigated. Flow team will take a look.

**Comment by sissbruecker** [comment] 2023-04-25 10:21
This is likely related to the `flow-component-renderer` refactoring in 24. With the new logic the component is first attached to the dialog element, and later moved to the dialog overlay, which causes the element to briefly become disconnected. As part of the disconnect, the context menu closes itself:
https://github.com/vaadin/web-components/blob/e6dd0eb849a801fc01369e8ce30f94299d56ec69/packages/context-menu/src/vaadin-context-menu.js#L373-L378

A workaround is to manually add the context menu to the dialog:
```java
dialog.add(menu);
```

**Closed** 2023-04-25 13:08 UTC
Labels: bug, vaadin-context-menu, Severity: Major, Impact: Low, workaround, regression

**Comment by mperktold** [comment] 2023-05-05 13:14
> I most probably have that same root cause with an add-on that breaks now with v24 and modal dialogs. Something is "shuffling" the elements in the DOM. The rich text editor loses its state and you can see clear flickering:
> Screenflick.Movie.62.mp4

I have a very similar issue with an embedded HTML email editor, which is similar to a rich text editor. When I have such an editor inside a Vaadin dialog, it somehow refreshes whenever I open or close another dialog. I reproduced this in a new Vaadin Starter here: https://github.com/mperktold/vaadin-25-unlayer-issue-reproducer

It's not really related to context menus, so I don't think the pull request will fix my problem.

**Comment by mrgreywater** [comment] 2023-05-05 13:20
@mperktold I think this is due to the modal dialog forcing a refresh of the background element. As a workaround, you could inherit from Dialog and Override these two functions:

```java
    @Override
    public boolean isModal() {
        return false;
    }

    /**
     * Workaround to create a client-side modal dialog without the server side 'security' modality curtain.
     * This curtain causes more issues than it solves, and it's not really needed anyway.
     */
    @Override
    public void setModal(boolean modal) {
        getElement().setProperty("modeless", !modal);
    }
```

**Comment by mperktold** [comment] 2023-05-05 13:53
@mrgreywater that actually works, you're a genius!
Thank you very much!

Is there already an issue for this specific problem?
I think this is a serious regression as well.

**Comment by mrgreywater** [comment] 2023-05-05 14:01
I don't think there is an issue for this yet on github. I discussed it on the discord and knoobie and I came up with this workaround there.
