### ISSUE TITLE
[spreadsheet] Sizing is not really working for me.

### ISSUE THREAD

**Issue by czp13** [vaadin/flow-components#3294] opened 2022-06-06 16:09 UTC
### Description

Example small App:
    
 ```
    @PageTitle("Spreadsheet")
    @Route(value = "hello")
    public class SpreadsheetView extends VerticalLayout {
    
        public SpreadsheetView() {
            Spreadsheet sheet = new Spreadsheet();
    
            // Not working if just added:
            // add(sheet);
    
            // Not working
            // sheet.setWidthFull();
            /// sheet.setHeightFull();
    
            // Not working:
            // setJustifyContentMode(JustifyContentMode.CENTER);
            // setDefaultHorizontalComponentAlignment(Alignment.CENTER);
            // getStyle().set("text-align", "center");
    
            // Only working with exact pixel setups for height and width:
            //Note: would be nice to push this to documentation OR fix it to work with percentages width and height.
            sheet.setHeight("900px");
            sheet.setWidth("900px");

            // Needed:
            add(sheet);
     }
 ```

The above not working ways to setup Width and Height can produce various visuals:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/61667986/172199706-e9812c05-a758-4631-9fd1-ae1b877b48e4.png">

The only way to make it work for me to use a fixed Width and Height:
 ```
            sheet.setHeight("900px");
            sheet.setWidth("900px");
```

### Expected outcome

Updating the developer doc, and the component page would be helpful I think.

As well the best would be if the developer just added the spreadsheet and it is working out of the box, so it could have a fixed width, and height default, or fix somehow this visual problem. Not sure if it is happening with other Layouts, did not check.

### Minimal reproducible example

Use not fixed and width or height in vertical layout for Spreadsheet component.

### Steps to reproduce

1. Just use my code example pls, 
2. I generated it with Vaadin start, 
3. but really cleared, removed every other component, and line, and just added the spreadsheet component.

### Environment

Vaadin version(s): 
    <properties>
        <java.version>17</java.version>
        <vaadin.version>23.1.0.rc2</vaadin.version>
        <selenium.version>4.1.2</selenium.version>
    </properties>

OS: 
MacOs Monterey 12.0.1 

Chrome:
102.0.5005.61 (Official Build) (arm64)

### Browsers

Chrome

**Comment by web-padawan** [comment] 2022-06-06 16:16
Thanks for the issue. Closing as duplicate of #3248

**Closed by web-padawan** 2022-06-06 16:16 UTC
