### ISSUE TITLE
Joining header columns re-arranges joined columns

### ISSUE THREAD

**Issue by cmrgKoradir** [vaadin/flow-components#1937] opened 2021-07-27 08:36 UTC
When joining Grid columns, the joined column sections can end up out of order.

### REPRODUCE
Create a grid with joinable headers
 
Note the order in which the headers are if they are not joined:
![image](https://user-images.githubusercontent.com/64977051/127121306-ba30de7c-0e0f-48ae-9870-60a3796d027f.png)
![correct order](https://user-images.githubusercontent.com/64977051/127121976-21b60204-a84c-47b1-be24-24a4e91f19a9.gif)
(ignore the actual titles, just focus on the numbers therein:
```
null (i.e. no title) - 1 -2 -3 - 4 - 5
```
)

Now join the header cells
![image](https://user-images.githubusercontent.com/64977051/127122161-f69e6557-2e5c-478a-a0e8-51d6eb203734.png)

#### IS
The joined columns may end up out of order:
![wrong order](https://user-images.githubusercontent.com/64977051/127122216-84e25d37-dffb-465a-b8b3-07b279334e4b.gif)
```
4 - 3 - 2 - 1 - null - 5
```

#### SHOULD
Relative order of joined header regions should be maintained.

### Minimal reproducible example

Provided by your Support Chat:
[JoinedColumns.zip](https://github.com/vaadin/web-components/files/6883941/JoinedColumns.zip)
with the comment:
> ﻿I've a grid with two groups:
﻿Group 0 has the columns with a key which is a power of two,
﻿The other group has all the other columns.
﻿
> ﻿I log the definitions (D) and the joins (J), and I confirm that powers of two are grouped in Group 0, and all the other columns are joined in the other group.

> ﻿With few columns (e.g 350) it works as expected:
> ![image](https://user-images.githubusercontent.com/64977051/127122674-6484bb6a-c2da-45bd-87fc-b711d584b6b0.png)
> When I have more columns, the groups are shifted
﻿> ![image](https://user-images.githubusercontent.com/64977051/127122755-4db3c500-f6d8-49bf-b2d3-7eb22eac423e.png)
> and to the right I'll find the columns from the first group, and some others
> ![image](https://user-images.githubusercontent.com/64977051/127122803-8d960eec-307d-48ce-9f89-2422b46bda73.png)

### Environment

- Vaadin 14.6.5
- Linux (Ubuntu 20.04.2 LTS)

### Browsers Affected

- [x] Chrome
(others not checked)
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by alvarezguille** [comment] 2021-07-27 11:05
Thanks for reporting this. Closing as a duplicate of #1017

**Closed by alvarezguille** 2021-07-27 11:05 UTC
