### ISSUE TITLE
Using com.vaadin.flow.component.icon.Icon can lead to memory leaks in the frontend

### ISSUE THREAD

**Issue by finaris-cs** [vaadin/flow-components#6002] opened 2024-01-30 16:09 UTC
### Description

I am not quite sure when this problem was introduced, but I am facing this problem with 24.2.1 and 24.3.3
I have an icon in the headline of one of my views. When I enter and leave that view multiple times, the icon (and the whole view) keeps referenced in the JS heap though the icon itself is detached, leading to a memory leak which makes the frontend slower and slower.
Have a look at the following memory snapshots. 

![image](https://github.com/vaadin/flow-components/assets/19190710/42fa022a-ef8a-4f95-bea3-6485c5460e8d)
![image](https://github.com/vaadin/flow-components/assets/19190710/dee17704-bfbb-438e-a736-d953dc4c120c)
(tooltip confirms that all the detached html elements are of type vaadin-icon)

To verify this problem, I started my application with all images replaced with empty DIVs. 
Comparing multiple memory snapshots do not show any additional detached elements in this case. 
With the images active I have lots of them.

### Expected outcome

Any references from Vaadin to that detached images should be cleared automatically 

### Minimal reproducible example

Tried to create a simple reproduction example, but without success.
My application does nothing with the affected images (especially not keeping any references), they are just rendered on the views.

### Steps to reproduce

none

### Environment

Vaadin version(s): 24.2.1, 24.3.3, maybe others
OS: not OS-specific

**Comment by tomivirkki** [comment] 2024-02-06 14:58
I wonder if this is a Chromium bug... I was able to reproduce a memory leak in Chrome where a certain combination of `<vaadin-icon>`s would result in some of them never getting GCd. On Firefox and Safari, all instances clean up as expected.

**Comment by tomivirkki** [comment] 2024-02-07 10:33
I created an isolated html+js repro and reported the issue to Chromium https://issues.chromium.org/issues/324108023

@finaris-cs Please try setting the style `container-type: initial;` to all `<vaadin-icon>` elements in your app to see if the frontend memory leak goes away. If that's the case, then we know it's about the same issue I reported.

**Comment by finaris-cs** [comment] 2024-02-08 12:04
Just reverted my changes so that **Div** is used **HorizontalLayout**. 
As expected, the leak is back again.

added 
vaadin-icon {
    container-type: initial;
}
to my CSS, and retested, no more Leaks due to icons.

So I can confirm that 

- this seems to be a chromium related bug
- The proposed workaround works

Thank you

**Comment by tomivirkki** [comment] 2024-02-08 15:35
I'm glad to hear that the workaround solved the issue. I assume the Chromium team will fix the bug shortly and ship the fix with one of the upcoming Chrome versions.

**Comment by tomivirkki** [comment] 2024-02-20 07:53
Closing this issue since the bug has now been fixed in Chromium

**Closed by tomivirkki** 2024-02-20 07:53 UTC
Labels: bug, vaadin-icons, Severity: Blocker, Impact: Low
