### ISSUE TITLE
TabSheet.getTab(Component component) is missing

### ISSUE THREAD

**Issue by SonReimer** [vaadin/flow-components#4378] opened 2022-12-16 08:04 UTC
### Description

May be this a feature request, but this requirement seems to me very basic.
There are several scenarios where this method is needed.
At the moment the only  possibility is to override add() and remove() methods and keep mapping for implementing methods like
```
public Tab TabSheet.getTab(Component component);
```
and optionally
```
public Component Tab.getComponent();
public Stream(Tab) TabSheet.tabs();
```
In our scenario we need this to extend the Tab class and set a default focus component for the layout belonging to this Tab.
```
((ExtendedTab)sheet.getTab(personLayout)).setDefaultFocusComponent(personLayout.getChildren().findFirst().orElse(null);
```

### Environment

Vaadin version(s): 23.3.0

**Comment by tomivirkki** [comment] 2022-12-16 08:19
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/4099

Please give the issue an upvote and add your use case to it to increase its priority

**Closed by tomivirkki** 2022-12-16 08:19 UTC
