### ISSUE TITLE
Vaadin 14 grid wrong place of column after reordering

### ISSUE THREAD

**Issue by komitoff** [vaadin/flow-components#3638] opened 2022-08-31 11:43 UTC
### Description

Hello there, 
I am having a grid with loads of columns. When I grab a column which is on the most right and try to put it at 1st place in the grid, the original one, that was on first place, goes somewhere in the middle. Please check out the gif provided
![grid_column_reordering](https://user-images.githubusercontent.com/7748256/187670297-69f7cc7b-fdbf-41c2-821e-f4434fbb6556.gif)

### Expected outcome

I am expecting the the column ID goes second place instead somewhere random in the grid

### Minimal reproducible example

	demoGrid = new Grid<>();
		demoGrid.addColumn(DemoBean::getId)
                    .setHeader("ID")
                    .setKey("ID");
        demoGrid.addColumn(DemoBean::getName)
                    .setHeader("NAME")
                    .setKey("NAME");
        demoGrid.addColumn(DemoBean::getBirthDay)
                    .setHeader("BIRTHDAY")
                    .setKey("BIRTHDAY");
        demoGrid.addColumn(DemoBean::getCountry)
                    .setHeader("COUNTRY")
                    .setKey("COUNTRY");
        demoGrid.addColumn(DemoBean::getBodySize)
                    .setHeader("BODY_SIZE")
                    .setKey("BODY_SIZE");
        demoGrid.addColumn(DemoBean::getGender)
                    .setHeader("GENDER")
                    .setKey("GENDER");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C1")
				.setKey("C1");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C2")
				.setKey("C2");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C3")
				.setKey("C3");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C4")
				.setKey("C4");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C5")
				.setKey("C5");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C6")
				.setKey("C6");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C7")
				.setKey("C7");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C8")
				.setKey("C8");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C9")
				.setKey("C9");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C10")
				.setKey("C10");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C11")
				.setKey("C11");
		demoGrid.addColumn(DemoBean::getC1)
				.setHeader("C12")
				.setKey("C12");

		demoGrid.setId("TEST_PREFERENCES_GRID");
		demoGrid.addThemeVariants(GridVariant.LUMO_COMPACT, GridVariant.LUMO_ROW_STRIPES,
				GridVariant.LUMO_NO_ROW_BORDERS, GridVariant.LUMO_COLUMN_BORDERS);
		demoGrid.setItems(createDummyData());
		demoGrid.setSizeFull();
		demoGrid.getColumns().forEach(column -> column.setResizable(true));
		demoGrid.setColumnReorderingAllowed(true);

### Steps to reproduce

Please check the gif provided

### Environment

Vaadin version(s): 14.8.1
OS: windows 11

### Browsers

Chrome

**Comment by komitoff** [comment] 2022-09-02 05:29
Hi I checked out the demo provided https://vaadin.com/docs/v14/ds/components/grid 
Seems like when a scroller appears (in my case a lot of columns) a
![grid_wrong_reordering](https://user-images.githubusercontent.com/7748256/188065384-bc6f38da-ac64-448e-9dd8-66ed2da6f2f9.gif)
nd start reordering, the place of the swapped column is somehow wrong. Please check out the glif - here the State column is the firsts non-frozen column, after I got the last column and put it at first position, the State columns goes last. If i shrink the columns to remove the scroller it is working in a different way, the state column goes second (not last).

**Comment by naydennn** [comment] 2022-09-02 05:58
I have this problem also.

**Comment by DominicMut** [comment] 2022-09-02 07:27
Same here.

**Comment by yuriy-fix** [comment] 2022-09-06 10:36
Closing as a duplicate of https://github.com/vaadin/web-components/issues/4451

**Closed by yuriy-fix** 2022-09-06 10:36 UTC
Labels: bug, Severity: Minor, Impact: High, UX
