### ISSUE TITLE
[form-layout] FormItem label-position always top

### ISSUE THREAD

**Issue by dex-ds** [vaadin/flow-components#2336] opened 2021-11-13 18:08 UTC
vaadin-flow 22.0.0.beta1
Excpected behavior => label-position="left" (by default) but is always "top"
(https://vaadin.com/docs/latest/ds/components/form-layout/#side)

try to set the things by element will be ignored
![image](https://user-images.githubusercontent.com/18628242/141654458-5fceccfe-eb82-418d-8e1f-90fc7991b9ce.png)
![image](https://user-images.githubusercontent.com/18628242/141654499-e57af905-69b4-421f-916f-7b0560993a35.png)

**Comment by web-padawan** [comment] 2021-11-14 10:36
Thanks for the issue. Looks like we are missing `labelsPosition` in the `setResponsiveSteps` documentation 😕

**Comment by sissbruecker** [comment] 2021-11-16 15:46
@dex-ds This is not reproducable from our side. Please provide a minimal reproducable example that demonstrates the issue. Also please make sure to follow the issue template in the future.

**Comment by dex-ds** [comment] 2021-11-16 17:06
As described here https://vaadin.com/docs/latest/ds/components/form-layout/#side I only do this.

```
HorizontalLayout hLay = new HorizontalLayout();
FormLayout frmLay2 = new FormLayout();
frmLay2.addFormItem(cbxLang, "Language");
hLay.add(frmLay2);
```
the result is
![image](https://user-images.githubusercontent.com/18628242/142031614-38e4d78d-bb66-4f66-b48d-09c09050cc62.png)

**Comment by sissbruecker** [comment] 2021-11-16 19:01
Thanks, putting the form layout into an horizontal layout is the key here.

Contrary to what the documentation states, the form layout will actually put the labels on top, if the layout's width is below a certain size ([`20em` by default](https://github.com/vaadin/web-components/blob/master/packages/form-layout/src/vaadin-form-layout.js#L219-L221)). This is due to the responsive native of the form layout, for example on mobile devices the label might not fit next to the input, so it makes sense to move the label to the top by default. The difference between your code, and the demo in the docs, is that you put your form layout into a horizontal layout, which uses CSS Flexbox for layouting. That means your form layout will not use the full width of the container, as in the docs demo, but will only use its intrinsic width, which is rather small in this case. That means when the form layout tries to calculate where to position the labels, it will determine that its size is too small, and position the labels on top. 

To fix this you can override the default responsive behaviour, and force to display the labels always on the side. For example:
```java
formLayout.setResponsiveSteps(
        // Small form layout size: Use 1 column, still keep label aside
        new FormLayout.ResponsiveStep("0", 1, FormLayout.ResponsiveStep.LabelsPosition.ASIDE),
        // Large form layout size: Use 2 columns, label aside
        new FormLayout.ResponsiveStep("40em", 2, FormLayout.ResponsiveStep.LabelsPosition.ASIDE)
);
```

Alternatively, you can give your horizontal layout, and the form layout an explicit width so that it uses the full width of the container. Example:
```java
        FormLayout formLayout = new FormLayout();
        formLayout.addFormItem(new TextField(), "Language");

        HorizontalLayout horizontalLayout = new HorizontalLayout();
        horizontalLayout.add(formLayout);

        // Define explicit width for horizontal layout container
        horizontalLayout.setWidthFull();

        // Make form layout use up all the remaining width in the horizontal layout
        horizontalLayout.setFlexGrow(1, formLayout);

        add(horizontalLayout);
```



As far as I can see everything is working as intended here. The form layout documentation should be improved. I'll file a documentation issue for that.

Closing as working as intended.

**Closed by sissbruecker** 2021-11-16 19:01 UTC
Labels: waiting for author
