### ISSUE TITLE
Checkbox flickering on readonly

### ISSUE THREAD

**Issue by paodb** [vaadin/flow-components#3628] opened 2022-08-29 17:14 UTC
### Description

When a checkbox is added as readonly, a weird flickering happens when clicking on it:
![readonly-checkbox](https://user-images.githubusercontent.com/30666649/187253586-a294f71f-2c82-442a-a6d7-44d11f94b9e3.gif)

### Expected outcome

On click, checkbox shouldn't show any flickering.

### Minimal reproducible example

```java
Checkbox checkbox = new Checkbox("I'm readonly"); 
checkbox.setReadOnly(true);
```

As a **workaround**, adding the following style, makes the flickering stop:
```java
checkbox.getElement().getStyle().set("pointer-events", "none");
```

### Steps to reproduce

1. Add the snipped above to a view
2. Click on the readonly checkbox
3. See flickering happening

### Environment

Vaadin version(s): 23.1.7

### Browsers

Issue is not browser related

**Comment by yuriy-fix** [comment] 2022-08-30 10:27
Closing as a duplicate of https://github.com/vaadin/web-components/issues/688

**Closed by yuriy-fix** 2022-08-30 10:27 UTC
