### ISSUE TITLE
SideNav does not reflect server side current route change by UI.navigate 

### ISSUE THREAD

**Issue by anatoly-spb** [vaadin/flow-components#5157] opened 2023-06-16 12:40 UTC
### Description

I want to change current route on server side programmatically:

https://github.com/anatoly-spb/my-vaadin24-app/blob/main/src/main/java/com/example/application/views/helloworld/HelloWorldView.java#L23

When I press on "Navigate To About" I see the following:
![image](https://github.com/vaadin/flow-components/assets/13556403/4abd7311-3655-4eee-8b01-21801f6dedaf)

### Expected outcome

![image](https://github.com/vaadin/flow-components/assets/13556403/b15aadc4-d33c-4239-8ff6-611034ddbaba)

### Minimal reproducible example

```java
public class HelloWorldView extends HorizontalLayout {

    private Button sayHello;

    public HelloWorldView() {
        sayHello = new Button("Navigate to About");
        sayHello.addClickListener(e -> {
            e.getSource().getUI().ifPresent(ui->ui.navigate("about"));
        });
        sayHello.addClickShortcut(Key.ENTER);

        setMargin(true);
        setVerticalComponentAlignment(Alignment.END, sayHello);

        add(sayHello);
    }

}
```

### Steps to reproduce

1. git clone git@github.com:anatoly-spb/my-vaadin24-app.git
2. run spring boot application
3. go to into browse
4. press the "Navigate to About" button
5. the About SideNavItem has not become active, but expected 

### Environment

Vaadin version(s): 24.1.0
OS: Windows 10 64bit Pro

### Browsers

Chrome

**Comment by ugur-vaadin** [comment] 2023-07-03 21:17
Closing in favour of a related [issue](https://github.com/vaadin/web-components/issues/5825) with the same root cause. Both of the issues are likely to be resolved by a Flow [PR](https://github.com/vaadin/flow/pull/17146).

**Closed by ugur-vaadin** 2023-07-03 21:17 UTC
Labels: bug, Severity: Minor, Impact: Low, vaadin-side-nav
