### ISSUE TITLE
Tooltip.forComponent should remove previous tooltip

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-components#4736] opened 2023-02-23 10:50 UTC
### Description

If you invoke Tooltip.forComponent multiple times for a single component, you keep adding tooltips and add/detach event listeners to the component.

### Expected outcome

The previous Tooltip should be removed and replaced with the new one. The registered event listeners for the old tooltip should be removed. I can't think of a use case where it would be better to have multiple tooltips in a single component.

### Minimal reproducible example

```java
        Button button = new Button("Submit");
        Tooltip.forComponent(button).setText("First tooltip");
        Tooltip.forComponent(button).setText("Second tooltip"); 
        add(button);
```

### Steps to reproduce

1. Add the code above into a view
2. Add a breakpoint to the fourth line
3. Investigate the variable `button` and see that it contains two tooltips
4. Resume execution
5. Open the UI. Notice that only one tooltip is really visible.

### Environment

Vaadin version(s): 23.3.6
OS: n/a

### Browsers

Issue is not browser related

**Comment by gpsfl** [comment] 2023-08-31 10:04
It would be great to also have the remove method available to just remove a tooltip without setting a new one

**Comment by TatuLund** [comment] 2023-11-02 08:52
Is this duplicate of https://github.com/vaadin/flow-components/issues/5427 ?

**Comment by OlliTietavainenVaadin** [comment] 2023-11-02 10:37
> Is this duplicate of #5427 ?

No

**Comment by tomivirkki** [comment] 2023-11-08 12:49
We discussed this internally and ended up with the following [fix](https://github.com/vaadin/flow-components/pull/5676)

After the change, calling `Tooltip.forComponent` again for the same component will return an existing Tooltip handle if one has already been created for it.

This will effectively make it impossible to create multiple tooltips for a single component instance.

**Closed** 2023-11-09 07:27 UTC
Labels: bug, Severity: Minor, Impact: Low, BFP, vaadin-tooltip
