### ISSUE TITLE
vaadin-details: There is no reliable way to tell if an OpenedChangeEvent is triggered by user interaction or not

### ISSUE THREAD

**Issue by haenni** [vaadin/flow-components#4659] opened 2023-02-09 08:43 UTC
### Description

We need to distinguish events that come from an actual user versus events that were triggered programmatically. The reason for that is that we record QA test scripts based on user interaction with our app. If we are unable to make this distinction, we do not know the relevant events to record in these test scripts. This prevents us from running our automated QA tests for this component.

In some instances, we can use the property `isFromClient` of the event to make that distinction. But for vaadin-details this is unreliable because programmatically triggered events can come from the client, see https://github.com/vaadin/flow-components/issues/4654

### Expected outcome

We need a way to tell if an event is triggered by user interaction. 

On some events in vaadin 8 there used to be a property `userOriginated` for example in com.vaadin.client.widget.grid.sort.SortEvent

We would need something like that for this component.

### Minimal reproducible example

[reproducerView.zip](https://github.com/vaadin/flow-components/files/10695024/reproducerView.zip)

### Steps to reproduce

1. Replace the MainView from the vaadin demo project with the view from the attached reproducer zip file
2. Add a breakpoint in the constructor of com.vaadin.flow.component.details.Details.OpenedChangeEvent
3. Start a debug session

### Environment

Vaadin version(s): 14.9.2 / 23.3.5
OS: Windows 10 

### Browsers

Issue is not browser related

**Comment by web-padawan** [comment] 2023-02-10 09:50
This sounds like a duplicate of #4659 to me.

**Comment by haenni** [comment] 2023-02-10 10:12
@web-padawan Thanks for having a look at it.
Did you possibly mean duplicate of https://github.com/vaadin/flow-components/issues/4654 ?
In my opinion this is not a duplicate. Because https://github.com/vaadin/flow-components/issues/4654 describes just a bit odd behavior and an example of how an event can have `isFromClient == true` and not be user originated.

**Comment by rolfsmeds** [comment] 2023-02-10 11:02
This issue has been prioritized for further inspection.

Fix backport target: V14.9.

**Comment by rolfsmeds** [comment] 2023-02-10 11:09
My guess is that the programmatic opening/closing of the panels is implemented in a way that actually triggers a client-side event which is indistinguishable from an actual client-initiated event, in which case the fix would presumably be based on refactoring the implementation of the server-side open/close API, or overriding the event on the client-side somehow.

**Comment by sissbruecker** [comment] 2023-02-10 20:05
The opened change listener was indeed implement so that`isFromClient` would always be `true`. I've opened a PR with a fix that should make the event correctly report its origin, as well as not trigger an initial opened change event.

**Closed** 2023-02-13 08:27 UTC
Labels: BFP
