### ISSUE TITLE
The colspan is not respected for a RichTextEditor in FormLayout.addFormItem()

### ISSUE THREAD

**Issue by FollowSteph** [vaadin/flow-components#3062] opened 2022-04-25 19:53 UTC
### Description

This is true even if using a VerticalLayout as a wrapper. 

Below is sample code that shows the exact same code working for FormLayout.add() but not FormLayout.addFormItem(). The reason to use addFormItem() is to get the label above the component in the FormLayout.

```
public class HelloWorldView extends VerticalLayout {

    public HelloWorldView() {
        RichTextEditor richTextEditor = new RichTextEditor();

        FormLayout formLayout = new FormLayout();
        formLayout.setResponsiveSteps(new FormLayout.ResponsiveStep("0", 3, FormLayout.ResponsiveStep.LabelsPosition.TOP));
        formLayout.add(new TextField("Field 1"), new TextField("Field 2"), new TextField("Field 3"));

        add(formLayout);
        setWidthFull();

//        addRichTextEditorSimple(formLayout, richTextEditor);
        addRichTextEditorFails(formLayout, richTextEditor);
//        addRichTextEditorFailsEvenWithWrapper(formLayout, richTextEditor);
    }

    // Works as expected
    private void addRichTextEditorSimple(FormLayout formLayout, RichTextEditor richTextEditor) {
        formLayout.add(richTextEditor);
        formLayout.setColspan(richTextEditor, 3);
    }

    // Does NOT work and only difference is addFormItem() instead of add()
    private void addRichTextEditorFails(FormLayout formLayout, RichTextEditor richTextEditor) {
        formLayout.addFormItem(richTextEditor, "Document");
        formLayout.setColspan(richTextEditor, 3);
    }

    // Fails even with a wrapper
    private void addRichTextEditorFailsEvenWithWrapper(FormLayout formLayout, RichTextEditor richTextEditor) {
        VerticalLayout verticalLayout = new VerticalLayout(richTextEditor);
        verticalLayout.setSpacing(false);
        verticalLayout.setMargin(false);
        formLayout.addFormItem(verticalLayout, "Document");
        formLayout.setColspan(verticalLayout, 3);
    }
}



```

### Expected outcome

The colspan is honored for RichTextEditor in FormLayout.addFormItem()

### Minimal reproducible example

See code in the description which can consistently reproduce the error.

### Steps to reproduce

See description

### Environment

Vaadin version(s): 23.0.6 (latest)
OS: All

### Browsers

Chrome, Firefox, Safari, Edge

**Comment by web-padawan** [comment] 2022-04-26 09:05
Duplicate of #2591. Please see https://github.com/vaadin/flow-components/issues/2591#issuecomment-1025116223 for the proper solution (we should document it better).

```java
FormItem formItem = formLayout.addFormItem(richTextEditor, "Document");
formLayout.setColspan(formItem, 3);
```

**Closed by web-padawan** 2022-04-26 09:05 UTC

**Comment by FollowSteph** [comment] 2022-04-26 19:16
You are correct. I've been caught by this bug again. If I may suggest for a future feature to be able to implement it like the other add() method because it requires internal knowledge that isn't obvious.
