### ISSUE TITLE
TreeGridPro missing

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow-components#5124] opened 2023-06-05 12:34 UTC
### Describe your motivation

My customer would like TreeGridPro Java API.

### Describe the solution you'd like

Editor API just like GridPro for TreeGrid.

### Describe alternatives you've considered

DIY... but customer thinks it should be our code for completeness.

### Additional context

Contact me for customer name.

**Comment by tomivirkki** [comment] 2023-06-05 12:53
Same as https://github.com/vaadin/flow-components/issues/1537

**Comment by yuriy-fix** [comment] 2023-06-07 12:34
Closing as a duplicate of https://github.com/vaadin/flow-components/issues/1537

**Closed by yuriy-fix** 2023-06-07 12:34 UTC
